/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XOfH8XB7NIG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { ScrollArea } from "@/components/ui/scroll-area"

export function VideoEditor() {
  return (
    <div className="flex flex-col h-screen">
      <div className="flex flex-1">
        <div className="w-1/3 p-4">
          <div className="flex flex-col h-full">
            <div className="relative mb-4">
              <SearchIcon className="absolute w-5 h-5 left-3 top-3 text-muted-foreground" />
              <Input type="search" placeholder="Search" className="pl-10" />
            </div>
            <ScrollArea className="flex-1 border rounded-md">
              <div className="p-2">
                <div className="pb-2 mb-4 border-b">
                  <h3 className="font-bold">Clip 1</h3>
                  <p className="text-sm text-muted-foreground">
                    This is the text flow here is that you can invite partners to join, it creates a part...
                  </p>
                </div>
                <div className="pb-2 mb-4 border-b">
                  <h3 className="font-bold">Clip 2</h3>
                  <p className="text-sm text-muted-foreground">
                    This is the text flow here is that you can invite partners to join, it creates a part...
                  </p>
                </div>
                <div className="pb-2 mb-4 border-b">
                  <h3 className="font-bold">Clip 3</h3>
                  <p className="text-sm text-muted-foreground">
                    This is the text flow here is that you can invite partners to join, it creates a part...
                  </p>
                </div>
              </div>
            </ScrollArea>
          </div>
        </div>
        <div className="w-2/3 p-4">
          <ScrollArea className="h-full border rounded-md">
            <div className="p-4">
              <h2 className="mb-4 text-xl font-bold">This tool is called</h2>
              <div className="mb-4">
                <p className="text-sm text-muted-foreground">Ren LaForme</p>
                <p>
                  Hey, this is Ren and I'm testing this tool called Descript. If you don't know much about me, I'm a
                  digital tools reporter at the Poynter Institute.
                </p>
              </div>
              <div className="mb-4">
                <p className="text-sm text-muted-foreground">Ren LaForme</p>
                <p>
                  This text won't be audible because I typed it in. But if I used the new Lyrebird feature, it totally
                  would. That's pretty cool, but also carries some concerns for the news industry.
                </p>
              </div>
            </div>
          </ScrollArea>
        </div>
      </div>
      <div className="h-32 p-4 border-t">
        <ScrollArea className="h-full border rounded-md">
          <div className="flex p-2">
            <div className="flex items-center justify-center w-24 h-12 mr-2 bg-gray-200 border rounded-md">
              <p className="text-xs">00:02</p>
            </div>
            <div className="flex items-center justify-center w-24 h-12 mr-2 bg-gray-200 border rounded-md">
              <p className="text-xs">00:03</p>
            </div>
            <div className="flex items-center justify-center w-24 h-12 mr-2 bg-gray-200 border rounded-md">
              <p className="text-xs">00:04</p>
            </div>
            <div className="flex items-center justify-center w-24 h-12 mr-2 bg-gray-200 border rounded-md">
              <p className="text-xs">00:05</p>
            </div>
            <div className="flex items-center justify-center w-24 h-12 mr-2 bg-gray-200 border rounded-md">
              <p className="text-xs">00:06</p>
            </div>
            <div className="flex items-center justify-center w-24 h-12 mr-2 bg-gray-200 border rounded-md">
              <p className="text-xs">00:07</p>
            </div>
            <div className="flex items-center justify-center w-24 h-12 mr-2 bg-gray-200 border rounded-md">
              <p className="text-xs">00:08</p>
            </div>
            <div className="flex items-center justify-center w-24 h-12 mr-2 bg-gray-200 border rounded-md">
              <p className="text-xs">00:09</p>
            </div>
            <div className="flex items-center justify-center w-24 h-12 mr-2 bg-gray-200 border rounded-md">
              <p className="text-xs">00:10</p>
            </div>
          </div>
        </ScrollArea>
      </div>
    </div>
  )
}

function SearchIcon(props: { className: string }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
