# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/product_horse',
                'doc_host': 'https://maxtheman.github.io',
                'git_url': 'https://github.com/maxtheman/product_horse',
                'lib_path': 'product_horse'},
  'syms': {'product_horse.core': {'product_horse.core.foo': ('core.html#foo', 'product_horse/core.py')}}}
