# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_api.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/08_api.ipynb 3
from dataclasses import dataclass
from typing import Any, List

# %% ../nbs/08_api.ipynb 4
# Create User and add files
# db.save user
# upload one or many files
# for each file in files
#   filesystem.save file
#   db.save that the file belongs to the user
#   if file is NOT text
#       kick off transcription job for file

# Internal: Transcription job
# given a file
# get transcription and utterances
# ai.extract speaker names
# update speaker names in transcript with simple find/replace
# save transcription and utterances to database

# Get transcriptions
# Get list of all transcriptions and users from db

# Create Schema
# Given text, ai.create schema.
# Save Schema to db

# Extract info
# given schema and transcriptions
# for transcription in transcriptions
#   extract info into temp_data using ai w/schema
# download temp_data as csv
