# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_api.ipynb.

# %% auto 0
__all__ = ['FileDict', 'create_and_save_schema', 'extract_info_from_transcriptions', 'get_relevant_utterances_from_query',
           'save_files_and_transcriptions', 'extract_data_given_users', 'get_user_names_and_transcript_counts',
           'make_video']

# %% ../nbs/08_api.ipynb 3
from typing import Any, List, TypedDict, Tuple, Sequence
from product_horse.filesystems import (
    AbstractFileSystem,
    FilePathType,
)
from product_horse.db import (
    AbstractDatabase,
    UnvalidatedUser,
    UnvalidatedFileMetadata,
    User,
    FileMetadata,
    UnvalidatedTranscription,
    Transcription,
    Schema,
    UnvalidatedSchema,
    UnvalidatedUtterance,
    Utterance,
)
from .audio_video import AudioEditor, AssemblyAiTranscript, make_video_from_utterances
from .extraction import AIModelClient, Questions, Answers, QADataManager
from .search import SearchEngine

# %% ../nbs/08_api.ipynb 4
class FileDict(TypedDict):
    content: bytes
    name: str


def _create_user_and_add_files(
    user_data: dict[str, Any],
    files: List[FileDict],
    db: AbstractDatabase,
    fs: AbstractFileSystem,
    authorized: bool = True,  # Is the user authorized to save these files?
) -> Tuple[User, List[FileMetadata]]:
    """
    Create a new user and add files for the user.

    Args:
        user_data (dict[str, Any]): User data dictionary.
        files (List[FileDict]): List of file dictionaries containing content and name.
        db (AbstractDatabase): Database instance for saving user and file metadata.
        fs (AbstractFileSystem): File system instance for saving files.
        authorized (bool, optional): Whether the files are authorized. Defaults to True.

    Returns:
        Tuple[User, List[FileMetadata]]: The created user object and a list of file metadata objects created.
    """
    unvalidated_user = UnvalidatedUser(**user_data)
    print(unvalidated_user)
    user: User = db.save_user(unvalidated_user)
    metadata: List[FileMetadata] = []

    for file_info in files:
        file_path = fs.build_user_path(user, FilePathType.USER_ID_BASE)
        path = fs.create_folder(file_path)
        file_content = file_info["content"]
        file = fs.create_file(
            file_path, file_content, file_info["name"], authorized=authorized
        )
        # Save file metadata to database
        unvalidated_metadata = UnvalidatedFileMetadata(
            user_id=user.id, file_name=file_info["name"], file_path=file.uri
        )
        metadata.append(db.save_file_metadata(unvalidated_metadata))

    return user, metadata

# %% ../nbs/08_api.ipynb 5
async def _transcribe_file_and_extract_speakers(
    file_metadata: FileMetadata,
    db: AbstractDatabase,
    audio_editor: AudioEditor,
) -> Tuple[Transcription, List[str]]:
    """
    Transcribe an audio file, extract speaker names, and save the transcription to the database.

    Args:
        file_metadata (FileMetadata): The metadata of the file to transcribe.
        db (AbstractDatabase): Database instance for saving transcription data.
        audio_editor (AssemblyAIClient): AssemblyAI client instance for transcription.

    Returns:
        Tuple[Transcription, List[str]]: The created transcription object and a list of extracted speaker names.
    """
    transcription_result: AssemblyAiTranscript = await audio_editor.transcribe(
        str(file_metadata.file_path)
    )
    utterances: List[UnvalidatedUtterance] = transcription_result.utterances
    speaker_names: List[str] = list(
        set([utterance.speaker for utterance in utterances])
    )

    # Future - update speaker names in the transcript using AI + find and replace

    # Save transcription to the database
    unvalidated_transcription = UnvalidatedTranscription(
        file_id=file_metadata.id, text=transcription_result.text
    )
    transcription: Transcription = db.save_transcription(
        unvalidated_transcription, utterances
    )

    return transcription, speaker_names

# %% ../nbs/08_api.ipynb 6
async def create_and_save_schema(
    text: str, db: AbstractDatabase, ai_model_client: AIModelClient
) -> Schema:
    """
    Create a schema from the given text using an AI model and save it to the database.

    Args:
        text (str): The text to create a schema from.
        db (AbstractDatabase): The database instance.
        ai_model_client (AIModelClient): The AI model client instance.

    Returns:
        Schema: The saved schema object.
    """
    questions = await ai_model_client.create_schema(text)
    unvalidated_schema = UnvalidatedSchema(
        input_text=text, json_schema=questions.model_dump()
    )
    schema = db.save_schema(unvalidated_schema)
    return schema

# %% ../nbs/08_api.ipynb 7
import asyncio


async def extract_info_from_transcriptions(
    schema: Schema,
    transcriptions: Sequence[Transcription],
    db: AbstractDatabase,
    ai_model_client: AIModelClient,
) -> Sequence[Answers]:
    """
    Extract information from transcriptions based on a schema and yields each extraction.

    Args:
        schema (Schema): The schema to use for extraction. Converted to questions internally.
        transcriptions (Sequence[Transcription]): The list of transcriptions to extract information from.
        db (AbstractDatabase): The database instance.
        ai_model_client (AIModelClient): The AI model client instance.

    Yields:
        Iterator[Tuple[Transcription, dict]]: An iterator of tuples containing the transcription and extracted answers.
    """
    questions = Questions(**schema.json_schema)

    tasks = [
        ai_model_client.extract_information(transcription.text, questions)
        for transcription in transcriptions
    ]

    # Use asyncio.gather to run them concurrently and wait for all to complete
    answers: list[Answers] = await asyncio.gather(*tasks)

    return answers

# %% ../nbs/08_api.ipynb 8
async def get_relevant_utterances_from_query(
    query: str, transcripts: Sequence[Transcription], db: AbstractDatabase
) -> Sequence[Utterance]:
    """
    Returns time-sorted utterances from a query
    """
    # allow for several clips from each transcript
    clips_requested = int(max(len(transcripts) * 2, 50))
    search_engine = SearchEngine(
        seconds_buffer=8, similarity_top_k=clips_requested, db=db
    )
    utterances = await search_engine.get_utterances_from_query(query, transcripts)

    return utterances

# %% ../nbs/08_api.ipynb 9
async def save_files_and_transcriptions(
    user_id: str,
    user_name: str,
    file_paths: list[str],
    db: AbstractDatabase,
    fs: AbstractFileSystem,
    audio_editor: AudioEditor,
):
    """Save the files and transcriptions to the database."""
    if user_id is None:  # type: ignore
        raise ValueError("User ID is required")
    user_data = {"external_id": user_id, "name": user_name}
    file_dicts: list[FileDict] = []
    for file in file_paths:
        with open(file, "rb") as f:  # Open the file in binary mode
            content = f.read()
        file_dicts.append({"content": content, "name": file})
    _, metadata = _create_user_and_add_files(user_data, file_dicts, db, fs)
    transcriptions: list[Tuple[Transcription, list[str]]] = []
    for file_metadata in metadata:
        transcription = await _transcribe_file_and_extract_speakers(
            file_metadata, db, audio_editor
        )
        transcriptions.append(transcription)
    return f"{len(transcriptions)} transcriptions saved."

# %% ../nbs/08_api.ipynb 10
async def extract_data_given_users(
    user_ids: List[str],
    db: AbstractDatabase,
    ai_model_client: AIModelClient,
    app_working_directory: str,
):
    schema = db.get_latest_schema()
    if schema is None:
        raise ValueError("No schema found")
    questions = Questions(**schema.json_schema)
    transcriptions = db.get_transcriptions_by_user_ids(user_ids)
    results = await extract_info_from_transcriptions(
        schema, transcriptions, db, ai_model_client
    )

    qa_data_manager = QADataManager()

    for transcription, answers in zip(transcriptions, results):
        metadata = db.get_file_metadata(transcription.file_id)
        if metadata is None:
            raise ValueError(f"No metadata found for file_id {transcription.file_id}")
        user = db.get_user(metadata.user_id)
        if user is None:
            raise ValueError(f"No user found for user_id {metadata.user_id}")
        qa_data_manager.add_answers(
            questions,
            answers,
            document_name=str(metadata.file_name),
            user_id=str(user.name),
        )

    output_file_path = f"{app_working_directory}/output.csv"
    qa_data_manager.merge_rows_by_user()
    qa_data_manager.to_csv(file_path=output_file_path)
    return output_file_path

# %% ../nbs/08_api.ipynb 11
def get_user_names_and_transcript_counts(db: AbstractDatabase) -> Sequence[tuple[str, str]]:
    users = db.get_all_users()
    user_ids = [user.id for user in users]
    if len(user_ids) == 0:
        return []
    last_user_id = user_ids[-1]
    options: list[tuple[str, str]] = []
    for user in users:
        transcriptions = db.get_transcriptions(user.id)
        options.append(
            (f"{user.name} ({len(transcriptions)}) calls transcribed", str(user.id))
        )
    assert str(last_user_id) == options[-1][1]
    return options

# %% ../nbs/08_api.ipynb 12
async def make_video(query: str, user_ids: list[str], db: AbstractDatabase) -> str:
    transcripts = db.get_transcriptions_by_user_ids(user_ids)
    utterances = await get_relevant_utterances_from_query(query, transcripts, db)
    video_path = make_video_from_utterances(utterances, db, query)
    return video_path
