# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_api.ipynb.

# %% auto 0
__all__ = ['FileDict', 'get_relevant_utterances_from_query', 'save_files_and_transcriptions',
           'get_user_names_and_transcript_counts']

# %% ../nbs/08_api.ipynb 3
from typing import Any, List, TypedDict, Tuple, Sequence
from product_horse.filesystems import (
    AbstractFileSystem,
    FilePathType,
)
from product_horse.db import (
    AbstractDatabase,
    DBType,
    UnvalidatedUser,
    UnvalidatedFileMetadata,
    User,
    FileMetadata,
    UnvalidatedTranscription,
    Transcription,
    Schema,
    UnvalidatedSchema,
    UnvalidatedUtterance,
    Utterance,
    UtteranceSegment,
    Employee,
    Video,
)
from product_horse.audio_video import (
    AudioEditor,
    create_video_from_utterances,
)
from .search import SearchEngine

# %% ../nbs/08_api.ipynb 4
class FileDict(TypedDict):
    content: bytes
    name: str


def _create_user_and_add_files(
    user_data: dict[str, Any],
    files: List[FileDict],
    db: AbstractDatabase[DBType],
    fs: AbstractFileSystem,
    employee: Employee,
) -> Tuple[User, List[FileMetadata]]:
    """
    Create a new user and add files for the user.

    Args:
        user_data (dict[str, Any]): User data dictionary.
        files (List[FileDict]): List of file dictionaries containing content and name.
        db (AbstractDatabase): Database instance for saving user and file metadata.
        fs (AbstractFileSystem): File system instance for saving files.
        authorized (bool, optional): Whether the files are authorized. Defaults to True.

    Returns:
        Tuple[User, List[FileMetadata]]: The created user object and a list of file metadata objects created.
    """
    unvalidated_user = UnvalidatedUser(**user_data)
    user: User = db.save_user(unvalidated_user)
    metadata: List[FileMetadata] = []

    for file_info in files:
        file_path = fs.build_user_path(user, FilePathType.USER_ID_BASE)
        fs.create_folder(file_path)
        file_content = file_info["content"]
        file = fs.create_file(
            file_path, file_content, file_info["name"], authorized=True
        )
        # Save file metadata to database
        unvalidated_metadata = UnvalidatedFileMetadata(
            user_id=user.id,
            file_name=file_info["name"],
            file_path=file.uri,
            created_by_id=employee.id,
            company_id=employee.company_id,
        )
        metadata.append(
            db.as_employee(employee).save_file_metadata(unvalidated_metadata)
        )

    return user, metadata

# %% ../nbs/08_api.ipynb 5
async def _transcribe_file_and_extract_speakers(
    file_metadata: FileMetadata,
    db: AbstractDatabase[DBType],
    audio_editor: AudioEditor,
    employee: Employee,
) -> Tuple[Transcription, List[str]]:
    """
    Transcribe an audio file, extract speaker names, and save the transcription to the database.

    Args:
        file_metadata (FileMetadata): The metadata of the file to transcribe.
        db (AbstractDatabase): Database instance for saving transcription data.
        audio_editor (AssemblyAIClient): AssemblyAI client instance for transcription.

    Returns:
        Tuple[Transcription, List[str]]: The created transcription object and a list of extracted speaker names.
    """
    transcription_result = await audio_editor.transcribe(
        str(file_metadata.file_path), employee
    )
    utterances: List[UnvalidatedUtterance] = transcription_result.utterances
    speaker_names: List[str] = list(
        set([utterance.speaker for utterance in utterances])
    )

    # Future - update speaker names in the transcript using AI + find and replace

    # Save transcription to the database
    unvalidated_transcription = UnvalidatedTranscription(
        file_id=file_metadata.id,
        text=transcription_result.text,
        company_id=employee.company_id,
        created_by_id=employee.id,
    )
    transcription: Transcription = db.as_employee(employee).save_transcription(
        unvalidated_transcription, utterances
    )

    return transcription, speaker_names

# %% ../nbs/08_api.ipynb 8
async def get_relevant_utterances_from_query(
    query: str,
    transcripts: Sequence[Transcription],
    db: AbstractDatabase[DBType],
    employee: Employee,
) -> Sequence[Utterance]:
    """
    Returns time-sorted utterances from a query
    """
    # allow for several clips from each transcript
    clips_requested = int(min(len(transcripts) * 2, 50))
    search_engine = SearchEngine(
        seconds_buffer=2, similarity_top_k=clips_requested, db=db, employee=employee
    )
    utterances = await search_engine.get_utterances_from_query(query, transcripts)

    return utterances

# %% ../nbs/08_api.ipynb 9
async def save_files_and_transcriptions(
    user_id: str,
    user_name: str,
    file_paths: list[str],
    db: AbstractDatabase[DBType],
    fs: AbstractFileSystem,
    audio_editor: AudioEditor,
    employee: Employee,
):
    """Save the files and transcriptions to the database."""
    if user_id is None:  # type: ignore
        raise ValueError("User ID is required")
    user_data = {"external_id": user_id, "name": user_name}
    file_dicts: list[FileDict] = []
    for file in file_paths:
        with open(file, "rb") as f:  # Open the file in binary mode
            content = f.read()
        file_dicts.append({"content": content, "name": file})
    _, metadata = _create_user_and_add_files(user_data, file_dicts, db, fs, employee)
    transcriptions: list[Tuple[Transcription, list[str]]] = []
    for file_metadata in metadata:
        transcription = await _transcribe_file_and_extract_speakers(
            file_metadata, db, audio_editor, employee
        )
        transcriptions.append(transcription)
    return f"{len(transcriptions)} transcriptions saved."

# %% ../nbs/08_api.ipynb 11
def get_user_names_and_transcript_counts(
    db: AbstractDatabase[DBType],
) -> Sequence[tuple[str, str]]:
    """Only relevant for gradio"""
    users = db.get_all_users()
    user_ids = [user.id for user in users]
    if len(user_ids) == 0:
        return []
    last_user_id = user_ids[-1]
    options: list[tuple[str, str]] = []
    for user in users:
        transcriptions = db.get_transcriptions(user.id)
        options.append(
            (f"{user.name} ({len(transcriptions)}) calls transcribed", str(user.id))
        )
    assert str(last_user_id) == options[-1][1]
    return options
