"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_audio.ipynb.

# %% auto 0
__all__ = ['AudioEditor']

# %% ../nbs/02_audio.ipynb 5
from typing import List
import asyncio
import os
import assemblyai as aai  # type: ignore
import requests
from dotenv import load_dotenv
from product_horse.db import (
    CreateTranscription,
    UnvalidatedWord,
    UnvalidatedUtterance,
    Employee,
)

# For experimental viz replacement
# from multiprocess import Pool
# import cairo
# import subprocess as sp
# from functools import lru_cache

if not os.getenv("DATABASE_URL"):
    load_dotenv(dotenv_path="../.env.local")

# %% ../nbs/02_audio.ipynb 9
class AudioEditor:
    api_key: str | None = None

    def __init__(
        self,
        api_key: str | None = os.getenv("ASSEMBLY_API_KEY")
        if os.getenv("ASSEMBLY_API_KEY")
        else None,
    ):
        if not api_key:
            raise ValueError("ASSEMBLYAI_API_KEY environment variable not found")
        self.api_key = api_key

    def upload_for_transcript(self, file_path: str) -> str:
        """Uploads a file for transcription and returns the file URL."""
        if not file_path.startswith("https://"):
            with open(file_path, "rb") as file:
                audio_file = file.read()
        else:
            audio_file = requests.get(file_path).content
        if not self.api_key:
            raise ValueError("ASSEMBLYAI_API_KEY environment variable not found")
        response = requests.post(
            "https://api.assemblyai.com/v2/upload",
            headers={
                "Authorization": self.api_key,
                "Content-Type": "application/octet-stream",
            },
            data=audio_file,
        )
        if response.status_code != 200:
            raise Exception(f"Failed to upload file: {response.text}")
        file_url = response.json()["upload_url"]
        return file_url

    async def transcribe(
        self, file_url: str, employee: Employee
    ) -> CreateTranscription:
        """Transcribes a file and returns the transcript."""
        aai.settings.api_key = self.api_key
        config = aai.TranscriptionConfig(speaker_labels=True)
        transcript_future = aai.Transcriber().transcribe_async(file_url, config)
        transcript = await asyncio.to_thread(transcript_future.result)
        text_well_formed: bool = (
            transcript.utterances
            and transcript.text
            and len(transcript.text) > 0
            and len(transcript.utterances) > 0
        )  # type: ignore
        if not text_well_formed:
            raise Exception(f"No text or utterances found in audio file: {file_url}")
        if transcript.status != "error" and text_well_formed:
            # Convert each utterance and its words to the correct Pydantic models
            if not transcript.utterances:
                raise Exception(f"No utterances found in audio file: {file_url}")
            transcript_text = "\n".join(
                [
                    f"Speaker {utterance.speaker}: {utterance.text}"
                    for utterance in transcript.utterances
                ]
            )
            utterances: list[UnvalidatedUtterance] = [
                UnvalidatedUtterance(
                    confidence=u.confidence,
                    end=u.end,
                    speaker=u.speaker or "speaker not detected",
                    start=u.start,
                    text=u.text,
                    words=[
                        UnvalidatedWord(
                            text=w.text,
                            start=w.start,
                            end=w.end,
                            confidence=w.confidence,
                            speaker=w.speaker if w.speaker else "speaker not detected",
                            company_id=employee.company_id,
                            created_by_id=employee.id,
                        )
                        for w in u.words
                    ],
                    company_id=employee.company_id,
                    created_by_id=employee.id,
                )
                for u in transcript.utterances
            ]
            return CreateTranscription(
                text=transcript_text,
                utterances=utterances,
                company_id=employee.company_id,
                created_by_id=employee.id,
            )
        else:
            raise Exception(f"{transcript.error} - {transcript.status}")

    def make_webvtt(self, utterances: List[UnvalidatedUtterance]):
        # https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API
        # add later
        pass
