# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_audio_video.ipynb.

# %% auto 0
__all__ = ['word_validator', 'AssemblyAiTranscript', 'AudioEditor']

# %% ../nbs/03_audio_video.ipynb 3
from dataclasses import dataclass
from typing import List, Any
from pydantic import BaseModel, TypeAdapter
from .db import Word, Utterance
import assemblyai as aai
import requests
import os
from dotenv import load_dotenv

load_dotenv()

# %% ../nbs/03_audio_video.ipynb 5
word_validator = TypeAdapter(List[Word])


class AssemblyAiTranscript(BaseModel):
    text: str
    utterances: List[Utterance]


class AudioEditor:
    api_key: str | None = None
    def __init__(
        self,
        api_key: str | None = os.getenv("ASSEMBLY_API_KEY")
        if os.getenv("ASSEMBLY_API_KEY")
        else None,
    ):
        if not api_key:
            raise ValueError("ASSEMBLYAI_API_KEY environment variable not found")
        self.api_key = api_key

    def upload_for_transcript(self, file_path: str) -> str:
        """Uploads a file for transcription and returns the file URL."""
        if not file_path.startswith("https://"):
            with open(file_path, "rb") as file:
                audio_file = file.read()
        else:
            audio_file = requests.get(file_path).content
        if not self.api_key:
            raise ValueError("ASSEMBLYAI_API_KEY environment variable not found")
        response = requests.post(
            "https://api.assemblyai.com/v2/upload",
            headers={
                "Authorization": self.api_key,
                "Content-Type": "application/octet-stream",
            },
            data=audio_file,
        )
        if response.status_code != 200:
            raise Exception(f"Failed to upload file: {response.text}")
        file_url = response.json()["upload_url"]
        return file_url

    async def transcribe(self, file_url: str) -> AssemblyAiTranscript:
        """Transcribes a file and returns the transcript."""
        aai.settings.api_key = self.api_key
        config = aai.TranscriptionConfig(speaker_labels=True)
        transcript = aai.Transcriber().transcribe(file_url, config)
        if transcript.status != "error" and transcript.utterances and transcript.text:
            # Convert each utterance and its words to the correct Pydantic models
            transcript_text = "\n".join(
                [
                    f"Speaker {utterance.speaker}: {utterance.text}"
                    for utterance in transcript.utterances
                ]
            )
            utterances = [
                Utterance(
                    confidence=u.confidence,
                    end=u.end,
                    speaker=u.speaker or "speaker not detected",
                    start=u.start,
                    text=u.text,
                    words=word_validator.validate_python(
                        u.words, from_attributes=True
                    ),  # Convert words for each utterance
                )
                for u in transcript.utterances
            ]
            return AssemblyAiTranscript(text=transcript_text, utterances=utterances)
        else:
            raise Exception(f"{transcript.error}")

    def make_webvtt(self, utterances: List[Utterance]):
        # https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API
        # add later
        pass
