"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_audio_video.ipynb.

# %% auto 0
__all__ = ['AudioEditor', 'save_mp4_animation_to_file', 'put_words_over_video_subset', 'write_video', 'render_clip',
           'render_clips', 'create_video_from_clips', 'filter_clips_by_utterance_segments',
           'create_video_from_utterances']

# %% ../nbs/03_audio_video.ipynb 5
from typing import List, Tuple, cast, Sequence
import asyncio
from pathlib import Path
from moviepy.editor import (  # type: ignore
    VideoFileClip,
    AudioFileClip,
    CompositeVideoClip,
    TextClip,
    VideoClip,
    concatenate_videoclips,  # type: ignore
)
import os
import shutil
from seewav import visualize  # type: ignore
import assemblyai as aai  # type: ignore
import requests
from dotenv import load_dotenv
from product_horse.db import (
    UtteranceSegment,
    Word,
    UnvalidatedVideo,
    CreateTranscription,
    Video,
    RenderStatus,
    Clip,
    VideoType,
    User,
    UnvalidatedUtterance,
    Employee,
    CreateClip,
    AbstractDatabase,
    DBType,
    FileType,
)
from .filesystems import FilePathType, AbstractFileSystem, LocalFileSystem
from rich.console import Console
import io
import tempfile


# For experimental viz replacement
# from multiprocess import Pool
# import cairo
# import subprocess as sp
# from functools import lru_cache

if not os.getenv("DATABASE_URL"):
    load_dotenv(dotenv_path="../.env.local")

# %% ../nbs/03_audio_video.ipynb 9
from product_horse.db import (
    SqlModelDatabase,
    UnvalidatedWord,
    UnvalidatedUser,
    UnvalidatedTranscription,
    UnvalidatedFileMetadata,
    CreateEmployee,
    UnvalidatedCompany,
    PermissionLevel,
)

# %% ../nbs/03_audio_video.ipynb 10
class AudioEditor:
    api_key: str | None = None

    def __init__(
        self,
        api_key: str | None = os.getenv("ASSEMBLY_API_KEY")
        if os.getenv("ASSEMBLY_API_KEY")
        else None,
    ):
        if not api_key:
            raise ValueError("ASSEMBLYAI_API_KEY environment variable not found")
        self.api_key = api_key

    def upload_for_transcript(self, file_path: str) -> str:
        """Uploads a file for transcription and returns the file URL."""
        if not file_path.startswith("https://"):
            with open(file_path, "rb") as file:
                audio_file = file.read()
        else:
            audio_file = requests.get(file_path).content
        if not self.api_key:
            raise ValueError("ASSEMBLYAI_API_KEY environment variable not found")
        response = requests.post(
            "https://api.assemblyai.com/v2/upload",
            headers={
                "Authorization": self.api_key,
                "Content-Type": "application/octet-stream",
            },
            data=audio_file,
        )
        if response.status_code != 200:
            raise Exception(f"Failed to upload file: {response.text}")
        file_url = response.json()["upload_url"]
        return file_url

    async def transcribe(
        self, file_url: str, employee: Employee
    ) -> CreateTranscription:
        """Transcribes a file and returns the transcript."""
        aai.settings.api_key = self.api_key
        config = aai.TranscriptionConfig(speaker_labels=True)
        transcript_future = aai.Transcriber().transcribe_async(file_url, config)
        transcript = await asyncio.to_thread(transcript_future.result)
        text_well_formed: bool = (
            transcript.utterances
            and transcript.text
            and len(transcript.text) > 0
            and len(transcript.utterances) > 0
        )  # type: ignore
        if not text_well_formed:
            raise Exception(f"No text or utterances found in audio file: {file_url}")
        if transcript.status != "error" and text_well_formed:
            # Convert each utterance and its words to the correct Pydantic models
            if not transcript.utterances:
                raise Exception(f"No utterances found in audio file: {file_url}")
            transcript_text = "\n".join(
                [
                    f"Speaker {utterance.speaker}: {utterance.text}"
                    for utterance in transcript.utterances
                ]
            )
            utterances: list[UnvalidatedUtterance] = [
                UnvalidatedUtterance(
                    confidence=u.confidence,
                    end=u.end,
                    speaker=u.speaker or "speaker not detected",
                    start=u.start,
                    text=u.text,
                    words=[
                        UnvalidatedWord(
                            text=w.text,
                            start=w.start,
                            end=w.end,
                            confidence=w.confidence,
                            speaker=w.speaker if w.speaker else "speaker not detected",
                            company_id=employee.company_id,
                            created_by_id=employee.id,
                        )
                        for w in u.words
                    ],
                    company_id=employee.company_id,
                    created_by_id=employee.id,
                )
                for u in transcript.utterances
            ]
            return CreateTranscription(
                text=transcript_text,
                utterances=utterances,
                company_id=employee.company_id,
                created_by_id=employee.id,
            )
        else:
            raise Exception(f"{transcript.error} - {transcript.status}")

    def make_webvtt(self, utterances: List[UnvalidatedUtterance]):
        # https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API
        # add later
        pass

# %% ../nbs/03_audio_video.ipynb 17
def save_mp4_animation_to_file(
    audio_path: str,
    output_path: str,
    tmp_directory: str,
    seek: int = 0,  # start at the beginning
    duration: float = 10.0,  # duration in seconds
    rate: int = 24,  # frames per second
    bars: int = 30,  # number of bars in the visualization
    fg_color: Tuple[float, float, float] = (0.2, 0.5, 0.8),  # foreground color
    bg_color: Tuple[float, float, float] = (1, 1, 1),  # background color
    size: Tuple[int, int] = (640, 480),  # size of the output video
) -> None:
    """
    Generate the visualisation for the `audio` file, using a `tmp` folder and saving the final
    video in `out`.
    `seek` and `durations` gives the extract location if any.
    `rate` is the framerate of the output video.

    `bars` is the number of bars in the animation.
    `speed` is the base speed of transition. Depending on volume, actual speed will vary
        between 0.5 and 2 times it.
    `time` amount of audio shown at once on a frame.
    `oversample` higher values will lead to more frequent changes.
    `fg_color` is the rgb color to use for the foreground.
    `bg_color` is the rgb color to use for the background.
    `size` is the `(width, height)` in pixels to generate.
    """
    if size == (0, 0):
        raise ValueError("Size must be provided")
    visualize(
        audio=Path(audio_path),
        out=Path(output_path),
        seek=seek,
        tmp=Path(tmp_directory),
        duration=duration,
        rate=rate,
        bars=bars,
        fg_color=fg_color,
        bg_color=bg_color,
        size=size,
    )

# %% ../nbs/03_audio_video.ipynb 19
def put_words_over_video_subset(
    file_path: str,
    words: Sequence[Word],
    target_resolution: Tuple[int, int],
    start: float,
    end: float = 0.0,
    position: str = "center",
) -> CompositeVideoClip:
    """Adds words to a video clip.
    - start: The starting time (in seconds) of the video segment.
    - end: The ending time (in seconds) of the video segment. If end is 0.0, the entire video from start to the end is used.
    - word_start is indexed against the start of the transcript, not necessarily the video clip. So the start of the video clip is used as an offset."""
    console = Console()
    console.print(file_path, style="green")
    if type(target_resolution) != tuple:
        raise ValueError("Target resolution must be a tuple")
    if len(words) == 0:
        raise ValueError("No words to add to video")
    clips_with_words: list[VideoClip] = []
    previous_word_end = 0.0
    # start of this video_clip should be used as 0
    try:  # catching exceptions on VideoFileClip creation
        if end > 0:
            print("file_path", file_path)
            video_clip_full = VideoFileClip(
                file_path, target_resolution=target_resolution
            )
            video_clip = video_clip_full.subclip(start, end)
        else:
            video_clip = VideoFileClip(file_path, target_resolution=target_resolution)
        text_positions = {
            "center": ("center", "center"),
            "bottom-third": ("center", "bottom"),
        }
    except Exception as e:
        console.print(e, style="red")
        raise e
    try:
        check_frame = video_clip.get_frame(0)
        if check_frame is None:
            raise ValueError("Video clip is has no video")
    except Exception as e:
        console.print(e, style="red")
        raise e
    text_position = text_positions.get(position, (0.5, 0.5))
    for word in words:
        word_start = float(word.start) / 1000
        word_start_adj = word_start - start
        word_end = float(word.end) / 1000
        word_end_adj = word_end - start
        final_end = cast(float, video_clip.duration)  # type: ignore
        if word_start_adj > final_end:
            console.print(
                f"word_start_adj is greater than final_end {word_start_adj} > {final_end}, {word.text}",
                style="red",
            )
            continue
        if word_end_adj > final_end:
            console.print(f"Adjusting end time for word '{word.text}'", style="yellow")
            word_end_adj = final_end
        word_text = word.text
        word_color = (
            "white"
            if word.speaker == "A"
            else "yellow"
            if word.speaker == "B"
            else "grey"
        )
        word_clip = TextClip(
            word_text,
            fontsize=48,
            size=(
                target_resolution[1],
                target_resolution[0] / 3,
            ),  # because of the weird resolution flipping issue
            color=word_color,
            stroke_color="black",
            font="Arial",
            stroke_width=2,
        )
        gap_before_word = word_start_adj - previous_word_end
        # Set duration to include the gap before the word
        duration = word_end_adj - word_start_adj + gap_before_word
        word_clip = word_clip.set_duration(duration)
        clips_with_words.append(word_clip)

        previous_word_end = word_end_adj
    final_word_clip = concatenate_videoclips(clips_with_words).set_position(
        text_position
    )
    final_clip = CompositeVideoClip([video_clip, final_word_clip])
    if (
        abs(final_clip.duration - video_clip.duration) > 0.1
    ):  # Allow small tolerance#type: ignore
        console.print(
            f"Adjusting final clip duration from {final_clip.duration} to {video_clip.duration}",  # type: ignore
            style="yellow",
        )
        final_clip = final_clip.set_duration(video_clip.duration)  # type: ignore
    return final_clip

# %% ../nbs/03_audio_video.ipynb 20
def write_video(
    video_path: str, video_clip: VideoFileClip | VideoClip | CompositeVideoClip
):
    console = Console()
    print("threads", os.cpu_count())
    try:
        video_clip.write_videofile(
            video_path,
            fps=video_clip.fps,  # type: ignore
            audio_codec="aac",
            preset="p4",  # Changed from "ultrafast" to "p4" for NVENC
            codec="h264_nvenc",  # Changed from "libx264" to "h264_nvenc"
            threads=os.cpu_count(),
            ffmpeg_params=['-movflags', 'faststart']
        )
        # | 3551/4343 [08:35<02:15,  5.83it/s, now=Non -- size was 1920x1080
        # '-g', '30', '-bf', '0'] didn't help
        # reducing size by 4x didn't help much
        #  '-tune', 'zerolatency' didn't help at all
        return True
    except Exception as e:
        console.print(e, style="red")
        raise e

# %% ../nbs/03_audio_video.ipynb 23
def render_clip(
    clip: Clip,
    temp_directory: str,
    local_path_for_clip: str,
) -> CompositeVideoClip | VideoClip:
    """Renders a clip from utterances for a given transcript.
    If not all words are used, only applicable words should be added to UtteranceSegment, and custom_start/custom_end should be equal to the start/end of the first/last words.
    If all words are used, start/end should be equal to the start/end of the entire video."""
    mp4_animation_path = f"{temp_directory}/{clip.id}.mp4"
    if len(clip.words) == 0:
        raise ValueError("No words to render")
    first_word = clip.words[0]
    last_word = clip.words[-1]
    if first_word.start != clip.start_ms:
        raise ValueError("Start times of first word and custom_start do not match")
    if last_word.end != clip.end_ms:
        raise ValueError("End times of last word and custom_end do not match")
    console = Console()
    size = (int(clip.resolution_x), int(clip.resolution_y))
    size = (
        size[1],
        size[0],
    )  # explicitly reverse the tuple to match moviepy's weird resolution flipping
    safe_end = min(clip.end_ms / 1000, clip.duration)
    safe_start = min(clip.start_ms / 1000, safe_end)
    if clip.video_type is not VideoType.video:
        print("using audio")
        if (
            clip.duration < 900
        ):  # if you remove this you will get failures with exit status 254 from ffmeg:
            raise ValueError(
                f"Duration of {local_path_for_clip} is too short to render a video"
            )
        try:
            working_clip: AudioFileClip = AudioFileClip(local_path_for_clip).subclip(
                safe_start, safe_end
            )  # type: ignore
        except Exception as e:
            console.print(e, style="red")
            raise e
        working_clip.write_audiofile(temp_directory + f"/{clip.id}.mp3")
        working_clip.close()
        save_mp4_animation_to_file(
            audio_path=local_path_for_clip,
            output_path=mp4_animation_path,
            tmp_directory=temp_directory,
            duration=clip.duration_ms/1000,
            rate=clip.fps,
            size=(size[1], size[0]), # weird resolution flipping
        )
        word_clip = put_words_over_video_subset(
            file_path=mp4_animation_path,
            words=clip.words,
            target_resolution=size,
            start=safe_start,
            # end=end, Do NOT put end here -- you want to use the entire video on this path, you already clipped it.
            position="center",
        )
    else:
        print("using video")
        word_clip = put_words_over_video_subset(
            file_path=local_path_for_clip,
            words=clip.words,
            target_resolution=size,
            start=safe_start,
            end=safe_end,
            position="bottom-third",
        )
        try:
            frame = word_clip.get_frame(0)
            if frame is None:
                raise ValueError("Word clip has no video")
        except Exception as e:
            console.print(e, style="red")
            raise e
    try:
        word_clip.get_frame(0)
    except Exception as e:
        console.print(e, style="red")
        raise e
    return word_clip

# %% ../nbs/03_audio_video.ipynb 24
async def render_clips(
    clip_list: Sequence[Clip],
    temp_server_directory: str,
    temp_server_file_system: AbstractFileSystem,
    file_system_for_getting_data: AbstractFileSystem,
    size: Tuple[int, int] = (0, 0),
) -> List[CompositeVideoClip | VideoClip]:
    """Renders clips, conditionally with metadata.
    Clips must be saved to DB before being passed to this function."""
    final_clips: List[CompositeVideoClip | VideoClip] = []
    for clip in clip_list:
        if clip.file_path is None:
            raise ValueError("No file path to render")
        if clip.resolution_x == 0 or clip.resolution_y == 0:
            if size == (0, 0):
                raise ValueError("Clip size is 0")
            clip.resolution_x = size[0]
            clip.resolution_y = size[1]
        with file_system_for_getting_data.file_stream(clip.file_path) as source_stream:
            file_extension = Path(clip.file_path).suffix
            temp_file_path = f"{temp_server_directory}/{clip.id}{file_extension}"
            with temp_server_file_system.file_stream(
                temp_file_path, mode="wb"
            ) as destination_stream:
                shutil.copyfileobj(source_stream, destination_stream, length=8192)

            final_clip = render_clip(
                clip,
                temp_server_directory,
                local_path_for_clip=temp_file_path,
            )
            if clip.hide_metadata:
                pass
            else:
                metadata_banner = TextClip(
                    clip.metadata_to_render,
                    fontsize=48,
                    color="white",
                    stroke_color="black",
                    font="Arial",
                    stroke_width=2,
                )
                metadata_banner = metadata_banner.set_position(
                    (0.05, 0.05),
                    relative=True,
                ).set_duration(clip.duration_ms/1000)  # type: ignore - moviepy types are crappy
                final_clip = CompositeVideoClip([final_clip, metadata_banner])
                final_clip.fps = clip.fps
            final_clips.append(final_clip)
    return final_clips

# %% ../nbs/03_audio_video.ipynb 28
def create_video_from_clips(
    clips: Sequence[Clip] | List[VideoClip | CompositeVideoClip],
    video: Video,
    temp_file_path: str,
    max_fps: int,
    target_resolution: Tuple[int, int],
):
    """
    Create a video from a list of clips.
    Save video after return
    """
    if isinstance(clips[0], Clip):
        video_clips = [VideoFileClip(clip.file_path) for clip in clips]  # type: ignore
    else:
        video_clips = clips
    final_video = concatenate_videoclips(video_clips, method="compose")
    if video.render_status == RenderStatus.complete:
        raise ValueError("Video is already complete")
    if video.render_status == RenderStatus.failed:
        raise ValueError("Video failed to render")
    try:
        with final_video as video_render:
            print(f"Writing video to {video.file_path}")
            write_video(temp_file_path, video_render)
        video.resolution_x = target_resolution[1]
        video.resolution_y = target_resolution[0]
        video.fps = max_fps
        video.render_status = RenderStatus.complete
    except Exception as e:
        video.render_status = RenderStatus.failed
        raise e
    return temp_file_path

# %% ../nbs/03_audio_video.ipynb 30
def filter_clips_by_utterance_segments(
    clips: list[CreateClip], utterance_segments: list[UtteranceSegment]
) -> list[CreateClip]:
    """
    Filter clips by utterance segments
    You get one clip per utterance segment, containing only the words between
    the segment's start and end words (inclusive).
    """
    filtered_clips: list[CreateClip] = []
    for segment in utterance_segments:
        for clip in clips:
            start_word = segment.segment_start_word
            end_word = segment.segment_end_word
            
            if start_word is None or end_word is None: #type: ignore
                continue
            
            # Find the indices of start and end words in the clip
            start_index = next((i for i, w in enumerate(clip.words) if w.id == start_word.id), None)
            end_index = next((i for i, w in enumerate(clip.words) if w.id == end_word.id), None)
            
            if start_index is not None and end_index is not None:
                # Include words from start_index to end_index (inclusive)
                matching_words = clip.words[start_index:end_index+1]
                
                if matching_words:
                    filtered_clip = clip.model_copy(
                        update={
                            "words": matching_words,
                            "start_ms": matching_words[0].start,
                            "end_ms": matching_words[-1].end,
                        }
                    )
                    print('words kept',len(filtered_clip.words))
                    filtered_clips.append(filtered_clip)
                    break  # Move to the next segment after finding a matching clip
    return filtered_clips

# %% ../nbs/03_audio_video.ipynb 33
async def create_video_from_utterances(
    video_id: str,
    db: AbstractDatabase[DBType],
    remote_file_system: AbstractFileSystem,
    local_file_system: LocalFileSystem,
    employee: Employee,
    user: User,
    utterance_segments: List[UtteranceSegment],
    final_destination: str,
    title: str,
    size: Tuple[int, int] = (0, 0),
    force_size: bool = False,
) -> Video:
    video_shell = db.as_employee(employee).get_video(video_id)
    if video_shell is None:
        raise ValueError("Video not found")
    transcript_ids = list(set(str(u.transcription_id) for u in utterance_segments))
    transcript_metadatas = db.as_employee(
        employee
    ).get_file_metadata_from_list_of_transcript_ids(transcript_ids)

    clips_and_metrics = db.as_employee(employee).prepare_clips_from_metadata(
        transcript_metadatas, employee, hide_metadata=False
    )

    filtered_clips = filter_clips_by_utterance_segments(
        clips_and_metrics.clips, utterance_segments
    )

    if size == (0, 0) and (clips_and_metrics.max_resolution_x, clips_and_metrics.max_resolution_y) != (0, 0):
        size = (clips_and_metrics.max_resolution_x, clips_and_metrics.max_resolution_y)
    elif size == (0, 0) and (clips_and_metrics.max_resolution_x, clips_and_metrics.max_resolution_y) == (0, 0):
        raise ValueError("No size provided")
    else:
        size = (size[1], size[0])

    if force_size:
        size = (size[1], size[0])

    video_updated = video_shell.model_copy(
        update={
            "title": title,
            "file_path": final_destination,
            "created_by_id": employee.id,
            "company_id": employee.company_id,
            "fps": clips_and_metrics.max_fps,
            "resolution_x": clips_and_metrics.max_resolution_x,
            "resolution_y": clips_and_metrics.max_resolution_y,
            "render_status": RenderStatus.processing
        }
    )
    video = db.as_employee(employee).save_video(video_updated)

    saved_clips = db.as_employee(employee).save_clips(filtered_clips, video.id)
    if video.fps is None or video.resolution_x is None or video.resolution_y is None:
        raise ValueError("Video fps, resolution_x, and resolution_y must be set")

    with local_file_system.temporary_user_directory(user) as temp_directory:
        clips_to_render = await render_clips(
            saved_clips,
            temp_directory,
            file_system_for_getting_data=remote_file_system,
            temp_server_file_system=local_file_system,
            size=size,
        )
        with tempfile.NamedTemporaryFile(delete=False, suffix=".mp4") as temp_file:
            temp_file_path = temp_file.name
            video_path = create_video_from_clips(
                clips_to_render,
                video,
                temp_file_path,
                video.fps,
                (video.resolution_x, video.resolution_y),
            )
            with open(video_path, "rb") as f:
                video_buffer = io.BytesIO(f.read())
                try:
                    final_video = await remote_file_system.create_file(
                        final_destination,
                        video_buffer,
                        name=f"{video.id}.mp4",
                        authorized=True,
                    )
                except Exception as e:
                    video.render_status = RenderStatus.failed
                    db.as_employee(employee).save_video(video)
                    raise e
        video.file_path = final_video.uri
        video_final = db.as_employee(employee).save_video(video)

    return video_final
