"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['run_test_case_with_pdb', 'AbstractQueue', 'InMemoryQueue', 'foo']

# %% ../nbs/00_core.ipynb 3
import unittest
import pdb


def run_test_case_with_pdb(
    test_case_class: type[unittest.TestCase], pdb_flag: bool = True
):
    """Run a unittest test case with pdb enabled"""

    class PdbTestResult(unittest.TestResult):
        def addError(self, test: unittest.TestCase, err):
            super().addError(test, err)
            _, _, tb = err
            pdb.post_mortem(tb)

        def addFailure(self, test: unittest.TestCase, err):
            super().addFailure(test, err)
            _, _, tb = err
            pdb.post_mortem(tb)

    suite = unittest.TestSuite()
    suite.addTest(unittest.TestLoader().loadTestsFromTestCase(test_case_class))
    runner = unittest.TextTestRunner(resultclass=PdbTestResult, verbosity=2)
    if not pdb_flag:
        runner = unittest.TextTestRunner(verbosity=2)
        runner.run(suite)
    else:
        runner.run(suite)

# %% ../nbs/00_core.ipynb 4
from abc import ABC, abstractmethod
from typing import Any

class AbstractQueue(ABC):
    @abstractmethod
    def enqueue(self, item: Any) -> None:
        """Add an item to the queue."""
        raise NotImplementedError

    @abstractmethod
    def dequeue(self) -> Any:
        """Remove and return an item from the queue."""
        raise NotImplementedError


    @abstractmethod
    def is_empty(self) -> bool:
        """Check if the queue is empty."""
        raise NotImplementedError
    
    @abstractmethod
    def start_workers(self, num_workers: int) -> None:
        """Start worker threads that process jobs from the queue."""
        raise NotImplementedError

    @abstractmethod
    def stop_workers(self) -> None:
        """Stop all worker threads."""
        raise NotImplementedError


# %% ../nbs/00_core.ipynb 5
import queue
import threading
from typing import Any

class InMemoryQueue(AbstractQueue):
    def __init__(self, maxsize: int = 0):
        self._queue: queue.Queue[Any] = queue.Queue(maxsize=maxsize)
        self._workers: list[threading.Thread] = []

    def enqueue(self, item: Any) -> None:
        self._queue.put(item)

    def dequeue(self) -> Any:
        return self._queue.get()

    def is_empty(self) -> bool:
        return self._queue.empty()

    def _worker(self):
        while True:
            job = self.dequeue()
            if job is None:  # Poison pill means shutdown
                break
            job()

    def start_workers(self, num_workers: int) -> None:
        for _ in range(num_workers):
            thread = threading.Thread(target=self._worker, daemon=True)
            thread.start()
            self._workers.append(thread)

    def stop_workers(self) -> None:
        for _ in self._workers:
            self.enqueue(None)  # Send poison pill to each worker
        for worker in self._workers:
            worker.join()
        self._workers.clear()

# %% ../nbs/00_core.ipynb 7
def foo():
    pass
