# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['run_test_case_with_pdb', 'AbstractQueue', 'foo']

# %% ../nbs/00_core.ipynb 3
from typing import Callable
import unittest
import pdb


def run_test_case_with_pdb(
    test_case_class: type[unittest.TestCase], pdb_flag: bool = True
):
    """Run a unittest test case with pdb enabled"""

    class PdbTestResult(unittest.TestResult):
        def addError(self, test: unittest.TestCase, err):
            super().addError(test, err)
            _, _, tb = err
            pdb.post_mortem(tb)

        def addFailure(self, test: unittest.TestCase, err):
            super().addFailure(test, err)
            _, _, tb = err
            pdb.post_mortem(tb)

    suite = unittest.TestSuite()
    suite.addTest(unittest.TestLoader().loadTestsFromTestCase(test_case_class))
    runner = unittest.TextTestRunner(resultclass=PdbTestResult, verbosity=2)
    if not pdb_flag:
        runner = unittest.TextTestRunner(verbosity=2)
        runner.run(suite)
    else:
        runner.run(suite)

# %% ../nbs/00_core.ipynb 4
from abc import ABC, abstractmethod
from typing import Any

class AbstractQueue(ABC):
    @abstractmethod
    def enqueue(self, item: Any) -> None:
        """Add an item to the queue."""
        raise NotImplementedError

    @abstractmethod
    def dequeue(self) -> Any:
        """Remove and return an item from the queue."""
        raise NotImplementedError


    @abstractmethod
    def is_empty(self) -> bool:
        """Check if the queue is empty."""
        raise NotImplementedError
    
    @abstractmethod
    def start_workers(self, num_workers: int) -> None:
        """Start worker threads that process jobs from the queue."""
        raise NotImplementedError

    @abstractmethod
    def stop_workers(self) -> None:
        """Stop all worker threads."""
        raise NotImplementedError


# %% ../nbs/00_core.ipynb 7
def foo():
    pass
