# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['run_test_case_with_pdb', 'foo']

# %% ../nbs/00_core.ipynb 3
import unittest
import pdb


def run_test_case_with_pdb(
    test_case_class: type[unittest.TestCase], pdb_flag: bool = True
):
    """Run a unittest test case with pdb enabled"""

    class PdbTestResult(unittest.TestResult):
        def addError(self, test: unittest.TestCase, err):
            super().addError(test, err)
            _, _, tb = err
            pdb.post_mortem(tb)

        def addFailure(self, test: unittest.TestCase, err):
            super().addFailure(test, err)
            _, _, tb = err
            pdb.post_mortem(tb)

    suite = unittest.TestSuite()
    suite.addTest(unittest.TestLoader().loadTestsFromTestCase(test_case_class))
    runner = unittest.TextTestRunner(resultclass=PdbTestResult, verbosity=2)
    if not pdb_flag:
        runner = unittest.TextTestRunner(verbosity=2)
        runner.run(suite)
    else:
        runner.run(suite)

# %% ../nbs/00_core.ipynb 4
def foo():
    pass
