"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_db.ipynb.

# %% auto 0
__all__ = ['STRINGS_TO_SANITIZE', 'ValidString', 'ValidPath', 'T', 'P', 'DBType', 'TModelOut', 'validate_file_path',
           'sanitize_strings', 'VideoVisibility', 'PermissionLevel', 'UnvalidatedCompany', 'Company',
           'UnvalidatedEmployee', 'CreateEmployee', 'Employee', 'OrgBoundModel', 'UnvalidatedUser', 'User', 'FileType',
           'FileStatus', 'UnvalidatedFileMetadata', 'FileMetadata', 'UnvalidatedWord', 'WordClipLink', 'Word',
           'UtteranceBase', 'UtteranceSegment', 'UnvalidatedUtterance', 'Utterance', 'UnvalidatedTranscription',
           'CreateTranscription', 'Transcription', 'UnvalidatedSchema', 'Schema', 'UnvalidatedVideo', 'RenderStatus',
           'Video', 'VideoType', 'UnvalidatedClip', 'CreateClip', 'Clip', 'VideoMetrics', 'PermissionDecorator',
           'DatabaseProtocol', 'get_current_level', 'set_timezone', 'permission_required', 'read', 'write', 'admin',
           'public', 'AbstractDatabase', 'SqlModelDatabase']

# %% ../nbs/07_db.ipynb 4
from typing import (
    Any,
    List,
    Sequence,
    Optional,
    cast,
    Type,
    TypeVar,
    Union,
    Literal,
    Tuple,
    Callable,
    Protocol,
    ParamSpec,
    Concatenate,
    Generic,
)
from dataclasses import dataclass
from functools import wraps
from enum import Enum, IntEnum
from typing_extensions import Annotated
from abc import ABC, abstractmethod
from sqlalchemy import BigInteger, text, LargeBinary
from sqlalchemy.exc import PendingRollbackError
from sqlalchemy.orm import selectinload, joinedload
from psycopg2.errors import InsufficientPrivilege
from pydantic import field_validator
from pydantic.functional_validators import BeforeValidator
from sqlmodel import (
    Field,
    Session,
    SQLModel,
    create_engine,
    select,
    col,
    Relationship,
)
from datetime import datetime, timezone
from uuid import uuid4, UUID
from collections import OrderedDict
from sqlalchemy import Column, JSON, case
from passlib.hash import pbkdf2_sha256
import warnings
import re
from rich.console import Console
import os
from dotenv import load_dotenv

if not os.getenv("DATABASE_URL"):
    load_dotenv(dotenv_path="../.env.local")

# %% ../nbs/07_db.ipynb 5
def validate_file_path(v: str) -> str:
    """Check that the path is valid according to regex"""
    if not re.match(r"^(\/[a-zA-Z0-9_-]+)+\/[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+$", v):
        raise ValueError(f"Path {v} is not valid")
    return v

# %% ../nbs/07_db.ipynb 7
STRINGS_TO_SANITIZE = ["\x00"]


def sanitize_strings(v: str) -> str:
    if v is None or v == "":
        return v
    for string in STRINGS_TO_SANITIZE:
        v = v.replace(string, "")
    return v


# https://docs.pydantic.dev/latest/concepts/validators/#annotated-validators
ValidString = Annotated[str, BeforeValidator(sanitize_strings)]
ValidPath = Annotated[ValidString, BeforeValidator(validate_file_path)]

# %% ../nbs/07_db.ipynb 8
### AUTH MODELS ###


class VideoVisibility(str, Enum):
    PRIVATE = "PRIVATE"
    INTERNAL = "INTERNAL"
    PUBLIC = "PUBLIC"


class PermissionLevel(IntEnum):
    PUBLIC = 0
    READ = 1
    WRITE = 2
    ADMIN = 3


class UnvalidatedCompany(SQLModel):
    name: ValidString = Field(default=None)


class Company(UnvalidatedCompany, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    created_at: datetime = Field(default=datetime.now(timezone.utc), nullable=False)
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), nullable=False)
    employees: list["Employee"] = Relationship(back_populates="company")


class UnvalidatedEmployee(SQLModel):
    email: ValidString = Field(default=None)
    name: ValidString = Field(default=None)
    permission_level: PermissionLevel = Field(default=PermissionLevel.READ)


class CreateEmployee(UnvalidatedEmployee):
    password: str


class Employee(UnvalidatedEmployee, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    created_at: datetime = Field(default=datetime.now(timezone.utc), nullable=False)
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), nullable=False)
    company: Company = Relationship(back_populates="employees")
    company_id: UUID = Field(foreign_key="company.id")
    hashed_password: bytes = Field(sa_column=Column(LargeBinary), default=None)


class OrgBoundModel(SQLModel):
    company_id: UUID = Field(foreign_key="company.id")
    created_by_id: UUID = Field(foreign_key="employee.id")

# %% ../nbs/07_db.ipynb 10
class UnvalidatedUser(OrgBoundModel):
    name: ValidString = Field(default=None)
    external_id: ValidString = Field(default=None)


class User(UnvalidatedUser, table=True):
    """This represents the COMPANY's users, not the users of producthorse"""

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    created_at: datetime = Field(default=datetime.now(timezone.utc), nullable=False)
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), nullable=False)
    file_metadata: List["FileMetadata"] = Relationship(
        back_populates="user", sa_relationship_kwargs={"cascade": "all, delete-orphan"}
    )


class FileType(str, Enum):
    video = "video"
    audio = "audio"
    other = "other"

class FileStatus(str, Enum):
    upload_started = "upload_started"
    upload_finished = "upload_finished"
    upload_failed = "upload_failed"
    transcribe_started = "transcribe_started"
    transcribe_finished = "transcribe_finished"
    transcribe_failed = "transcribe_failed"
    active = "active"
    deleted = "deleted"
    archived = "archived"


class UnvalidatedFileMetadata(OrgBoundModel):
    user_id: UUID = Field(default=None, foreign_key="user.id")
    file_name: ValidString = Field(default=None)
    file_path: ValidString = Field(default=None)
    frame_rate: Optional[int] = Field(default=None)
    resolution_x: Optional[int] = Field(default=None)
    resolution_y: Optional[int] = Field(default=None)
    duration: Optional[float] = Field(default=None)
    file_type: FileType = Field(default=None)
    file_status: FileStatus = Field(default=FileStatus.upload_started)


class FileMetadata(UnvalidatedFileMetadata, table=True):
    __tablename__ = "file_metadata"  # type: ignore
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    created_at: datetime = Field(default=datetime.now(timezone.utc), nullable=False)
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), nullable=False)
    transcription: "Transcription" = Relationship(
        back_populates="file_metadata",
        sa_relationship_kwargs={"cascade": "all, delete-orphan"},
    )
    user: "User" = Relationship(back_populates="file_metadata")


class UnvalidatedWord(OrgBoundModel):
    confidence: float
    end: int = Field(sa_column=Column(BigInteger))
    speaker: ValidString = Field(default=None)
    start: int = Field(sa_column=Column(BigInteger))
    text: ValidString = Field(default=None)


class WordClipLink(SQLModel, table=True):
    word_id: UUID = Field(default=None, foreign_key="word.id", primary_key=True)
    clip_id: UUID = Field(default=None, foreign_key="clip.id", primary_key=True)


class Word(UnvalidatedWord, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    utterance_id: UUID = Field(default=None, foreign_key="utterance.id")
    utterance: "Utterance" = Relationship(back_populates="words")
    clips: List["Clip"] = Relationship(back_populates="words", link_model=WordClipLink)


# Base class -- do not use directly
class UtteranceBase(OrgBoundModel):
    confidence: float
    end: int = Field(sa_column=Column(BigInteger))
    speaker: ValidString = Field(default=None)
    start: int = Field(sa_column=Column(BigInteger))
    text: ValidString = Field(default=None)


class UtteranceSegment(
    UtteranceBase
):  # mocking the Utterance without actually needing db connects
    """
    This is a mock class for creating utterance segments from a transcription.
    It is not a database model and does not have a corresponding table.
    The ID represents the start and end words of the original utterance.
    """

    id: UUID | None = Field(default=None)
    transcription_id: UUID = Field(default=None)
    transcription: "Transcription"
    words: list["Word"]
    segment_start_word: "Word"
    segment_end_word: "Word"


class UnvalidatedUtterance(UtteranceBase):
    words: list["Word"] | list["UnvalidatedWord"]


class Utterance(UtteranceBase, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    transcription: "Transcription" = Relationship(back_populates="utterances")
    transcription_id: UUID = Field(default=None, foreign_key="transcription.id")
    words: list["Word"] = Relationship(
        back_populates="utterance",
        sa_relationship_kwargs={"cascade": "all, delete-orphan"},
    )
    # relationship field lengths aren't validatable in sqlmodel :-/
    # PydanticUserError: Decorators defined with incorrect fields: __main__.Utterance:4797847184.check_words_length (use check_fields=False if you're inheriting from the model and intended this)
    # @field_validator('words')
    # def check_words_length(cls, values: list["Word"]) -> list["Word"]:
    #     if not values:
    #         raise ValueError("Utterance must have at least one word.")
    #     return values


class UnvalidatedTranscription(OrgBoundModel):
    file_id: UUID = Field(default=None, foreign_key="file_metadata.id")
    text: ValidString = Field(default=None)


class CreateTranscription(UnvalidatedTranscription):
    utterances: list[UnvalidatedUtterance]


class Transcription(UnvalidatedTranscription, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    created_at: datetime = Field(default=datetime.now(timezone.utc), nullable=False)
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), nullable=False)
    embedded: Optional[bool] = Field(default=False)
    utterances: list["Utterance"] = Relationship(
        back_populates="transcription",
        sa_relationship_kwargs={"cascade": "all, delete-orphan"},
    )
    file_metadata: "FileMetadata" = Relationship(back_populates="transcription")

    def __hash__(self):
        return hash(self.id)


class UnvalidatedSchema(OrgBoundModel):
    input_text: ValidString = Field(default=None)
    json_schema: dict[str, Any] = Field(default={}, sa_column=Column(JSON))


class Schema(UnvalidatedSchema, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    created_at: datetime = Field(default=datetime.now(timezone.utc), nullable=False)
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), nullable=False)


class UnvalidatedVideo(OrgBoundModel):
    title: ValidString = Field(default=None)
    file_path: str | None = Field(
        default=None
    )  # would like to use better validation here, but there seems to be a bug in sqlmodel https://github.com/tiangolo/sqlmodel/issues/67
    resolution_x: int | None = Field(default=None)
    resolution_y: int | None = Field(default=None)
    fps: int | None = Field(default=None)


class RenderStatus(str, Enum):
    pending = "pending"
    processing = "processing"
    complete = "complete"
    failed = "failed"


class Video(UnvalidatedVideo, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    created_at: datetime = Field(default=datetime.now(timezone.utc), nullable=False)
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), nullable=False)
    clips: List["Clip"] = Relationship(
        back_populates="video", sa_relationship_kwargs={"cascade": "all, delete-orphan"}
    )
    render_status: RenderStatus = Field(default=RenderStatus.pending)
    visibility: VideoVisibility = Field(default=VideoVisibility.PRIVATE)

    @property
    def duration_ms(self) -> float:
        return self.clips[-1].end_ms - self.clips[0].start_ms

    @property
    def duration(self) -> float:
        """
        Duration of the video in milliseconds. Wrapper for duration_ms
        """
        return self.duration_ms


class VideoType(str, Enum):
    video = "video"
    audio = "audio"
    other = "other"


class UnvalidatedClip(OrgBoundModel):
    """
    Clip of a video or audio file.
    Only add the relevant words you want to include.
    """

    fps: int
    resolution_x: int
    resolution_y: int
    speaker_role: Optional[str] = None
    metadata_to_render: Optional[str] = None
    video_type: VideoType
    file_path: str | None = Field(default=None)
    hide_metadata: bool = Field(default=False)
    render_status: RenderStatus = Field(default=RenderStatus.pending)

    @property
    def resolution(self) -> Tuple[int, int]:
        return (self.resolution_x, self.resolution_y)


class CreateClip(UnvalidatedClip):
    words: Sequence[Word]

    @property
    def start_ms(self) -> float:
        value = self.words[0].start
        if value < 100:
            warnings.warn("start_ms is very small. Ensure it's in milliseconds.")
        return value

    @property
    def end_ms(self) -> float:
        value = self.words[-1].end
        if value < 100:
            warnings.warn("end_ms is very small. Ensure it's in milliseconds.")
        return value

    @property
    def duration_ms(self) -> float:
        return self.end_ms - self.start_ms

    @field_validator("words")
    def check_words_length(cls, values: list["Word"]) -> list["Word"]:
        if not values:
            raise ValueError("Clip must have at least one word.")
        return values


class Clip(UnvalidatedClip, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    words: List[Word] = Relationship(back_populates="clips", link_model=WordClipLink)
    video_id: UUID = Field(default=None, foreign_key="video.id")
    video: Video = Relationship(back_populates="clips")
    created_at: datetime = Field(default=datetime.now(timezone.utc), nullable=False)
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), nullable=False)

    @property
    def start_ms(self) -> float:
        value = self.words[0].start
        if value < 100:
            warnings.warn("start_ms is very small. Ensure it's in milliseconds.")
        return value

    @property
    def end_ms(self) -> float:
        value = self.words[-1].end
        if value < 100:
            warnings.warn("end_ms is very small. Ensure it's in milliseconds.")
        return value

    @property
    def duration_ms(self) -> float:
        return self.end_ms - self.start_ms

    @property
    def duration(self) -> float:
        """
        Duration of the video in milliseconds. Wrapper for duration_ms
        """
        return self.duration_ms


@dataclass
class VideoMetrics:
    max_fps: int
    total_duration: float
    max_resolution_x: int
    max_resolution_y: int
    clips: List[CreateClip]

# %% ../nbs/07_db.ipynb 11
T = TypeVar("T")
P = ParamSpec("P")


class PermissionDecorator(Protocol):
    def __call__(
        self, func: Callable[Concatenate[Any, P], T]
    ) -> Callable[Concatenate[Any, P], T]: ...


class DatabaseProtocol(Protocol):
    employee: Optional[Employee]

    def get_session_for_employee(self, public: bool = False) -> Session: ...
    def permissions_set_session_variables(
        self, session: Session, employee: Employee
    ) -> None: ...
    def permissions_clear_session_variables(self, session: Session) -> None: ...


DBType = TypeVar("DBType", bound=DatabaseProtocol)


def get_current_level(session: Session) -> PermissionLevel | None:
    current_level = session.execute(
        text("SELECT current_setting('app.current_permission_level')::permissionlevel")
    ).scalar()
    return PermissionLevel[current_level] if current_level else None

def set_timezone(session: Session):
    session.execute(text("SET TIME ZONE 'UTC'"))


def permission_required(level: PermissionLevel):
    def decorator(
        func: Callable[Concatenate[DBType, Session, P], T],
    ) -> Callable[Concatenate[DBType, P], T]:
        """Decorator to require a certain permission level for a function. Unsets employee at the end of the function."""

        @wraps(func)
        def wrapper(self: DBType, *args: P.args, **kwargs: P.kwargs) -> T:
            def clear_all_vars(self: DBType):
                new_session = self.get_session_for_employee(public=True)
                self.permissions_clear_session_variables(new_session)
                new_session.close()

            if level == PermissionLevel.PUBLIC:
                with self.get_session_for_employee(public=True) as session:
                    set_timezone(session)
                    return func(self, session, *args, **kwargs)
            with self.get_session_for_employee() as session:
                if not self.employee:
                    raise ValueError("Employee not provided")
                try:
                    # sets and then checks database permission levels at both an app-level and RLS level
                    set_timezone(session)
                    self.permissions_set_session_variables(session, self.employee)
                    current_employee_permissions_level = get_current_level(session)
                    if current_employee_permissions_level is None:
                        raise PermissionError("Permissions not set for this session.")
                    if not current_employee_permissions_level:
                        raise PermissionError(
                            "No permissions set on app.current_permission_level"
                        )
                    if current_employee_permissions_level < level:
                        raise PermissionError(
                            "Employee does not have sufficient permissions"
                        )
                    return func(self, session, *args, **kwargs)
                except InsufficientPrivilege:
                    session.rollback()
                    clear_all_vars(self)
                    raise PermissionError(
                        "Employee does not have sufficient permissions"
                    )
                except Exception as error:
                    print(error)
                    raise error
                finally:
                    try:
                        self.permissions_clear_session_variables(session)
                    except PendingRollbackError:
                        # Create a new session if there's a pending rollback
                        clear_all_vars(self)
                    except InsufficientPrivilege:
                        clear_all_vars(self)
                    self.employee = None

        wrapper._permission_level = level  # type: ignore - dynamic assignment that I'm not worrying about.
        return wrapper

    return decorator


def read(
    func: Callable[Concatenate[DBType, Session, P], T],
) -> Callable[Concatenate[DBType, P], T]:
    return permission_required(PermissionLevel.READ)(func)


def write(
    func: Callable[Concatenate[DBType, Session, P], T],
) -> Callable[Concatenate[DBType, P], T]:
    return permission_required(PermissionLevel.WRITE)(func)


def admin(
    func: Callable[Concatenate[DBType, Session, P], T],
) -> Callable[Concatenate[DBType, P], T]:
    return permission_required(PermissionLevel.ADMIN)(func)


def public(
    func: Callable[Concatenate[DBType, Session, P], T],
) -> Callable[Concatenate[DBType, P], T]:
    return permission_required(PermissionLevel.PUBLIC)(func)

# %% ../nbs/07_db.ipynb 12
class AbstractDatabase(ABC, DatabaseProtocol, Generic[DBType]):
    """Abstract base class for database operations related to users, files, transcriptions, and schemas.
    Use Unvalidated Models to save raw user input, validation occurs on the model save
    """

    def __init__(self):
        self.employee = None

    # OPERATIONS

    class Operations(ABC):
        @abstractmethod
        def create_all_tables(self) -> None:
            """Initializes the database."""
            raise NotImplementedError

        @abstractmethod
        def run_migrations(self) -> None:
            """Runs database migrations."""
            raise NotImplementedError

        @abstractmethod
        def close(self) -> None:
            """Closes the database connection."""
            raise NotImplementedError

    @public
    @abstractmethod
    def get_employee(
        self, session: Session, employee_id: Union[str, UUID]
    ) -> Optional[Employee]:
        """Retrieves an employee from the database."""
        raise NotImplementedError

    @public
    @abstractmethod
    def set_session_variables(self, session: Session, employee: Employee) -> None:
        """Sets the current employee for the session."""
        raise NotImplementedError

    @abstractmethod
    def permissions_set_session_variables(
        self, session: Session, employee: Employee
    ) -> None:
        """Sets the current employee for the session. Requires a session to be passed in"""
        raise NotImplementedError

    @public
    @abstractmethod
    def clear_session_variables(self, session: Session) -> None:
        """Clears the session variables."""
        raise NotImplementedError

    @abstractmethod
    def permissions_clear_session_variables(self, session: Session) -> None:
        """Clears the session variables. Requires a session to be passed in"""
        raise NotImplementedError

    @abstractmethod
    def get_session_for_employee(self, public: bool = False) -> Session:
        """Returns a session for the database. Fails if an Auth'd User is not available unless public=True"""
        raise NotImplementedError

    # AUTH and PERMISSIONS

    def as_employee(self, employee: Employee) -> "AbstractDatabase[DBType]":
        """Returns an authenticated database authorized to act as the provided employee."""
        raise NotImplementedError

    @write
    @abstractmethod
    def update_employee(
        self,
        session: Session,
        employee_id: Union[str, UUID],
        values_to_update: dict[str, Any],
    ) -> Employee:
        """Updates an employee in the database."""
        raise NotImplementedError

    @write
    @abstractmethod
    def save_employee(
        self,
        session: Session,
        unvalidated_employee: CreateEmployee,
        company_id: UUID,
    ) -> Employee:
        """Creates an employee in the database."""
        raise NotImplementedError

    @public
    @abstractmethod
    def save_company_and_employee(
        self,
        session: Session,
        unvalidated_company: UnvalidatedCompany,
        unvalidated_employee: CreateEmployee,
    ) -> Tuple[Company, Employee]:
        """Creates a company and employee in the database. Intended for use with first-time signups"""
        raise NotImplementedError

    @public
    @abstractmethod
    def authenticate_employee(
        self, session: Session, email: str, password: str
    ) -> Optional[Employee]:
        """Authenticates an employee."""
        raise NotImplementedError

    @property
    @abstractmethod
    def operations(self) -> "Operations":
        """Property that should return an instance of Operations."""
        raise NotImplementedError

    # USERS

    @write
    @abstractmethod
    def save_user(self, session: Session, user: UnvalidatedUser) -> User:
        """Saves user information to the database."""
        raise NotImplementedError

    @write
    @abstractmethod
    def update_user(
        self, session: Session, user_id: UUID, values_to_update: dict[str, Any]
    ) -> User:
        """Updates user information in the database."""
        raise NotImplementedError

    @write
    def delete_user(self, session: Session, user_id: UUID) -> None:
        """Deletes a user from the database. Cascades to all transcriptions and file metadata"""
        raise NotImplementedError

    # FILES

    @write
    @abstractmethod
    def save_file_metadata(
        self, session: Session, metadata: UnvalidatedFileMetadata
    ) -> FileMetadata:
        """Saves metadata about a file uploaded by users."""
        raise NotImplementedError

    @read
    @abstractmethod
    def get_file_metadata(
        self, session: Session, file_id: Union[str, UUID]
    ) -> Optional[FileMetadata]:
        """Retrieves metadata about a file from the database."""
        raise NotImplementedError

    @write
    @abstractmethod
    def update_file_metadata(
        self, session: Session, file_id: UUID, values_to_update: dict[str, Any]
    ) -> FileMetadata:
        """Updates metadata about a file."""
        raise NotImplementedError

    @read
    @abstractmethod
    def get_file_metadata_from_list_of_transcript_ids(
        self, session: Session, transcript_ids: List[str]
    ) -> Sequence[FileMetadata]:
        """Retrieves metadata about a file from the database. Returns results in the order of the input list"""
        raise NotImplementedError

    # TRANSCRIPTIONS

    @write
    @abstractmethod
    def save_transcription(
        self,
        session: Session,
        transcription: UnvalidatedTranscription,
        utterances: List[UnvalidatedUtterance],
    ) -> Transcription:
        """Saves transcription data for a given file."""
        raise NotImplementedError

    @read
    @abstractmethod
    def get_transcription(
        self, session: Session, transcription_id: Union[str, UUID]
    ) -> Optional[Transcription]:
        """Retrieves a transcription from the database."""
        raise NotImplementedError

    @write
    @abstractmethod
    def update_transcription(
        self, session: Session, transcription_id: UUID, values_to_update: dict[str, Any]
    ) -> Transcription:
        """Updates a transcription in the database."""
        raise NotImplementedError

    @read
    @abstractmethod
    def get_transcriptions(
        self,
        session: Session,
        user_id: Union[str, UUID],
        transcription_ids: Optional[List[UUID]] = None,
    ) -> Sequence[Transcription]:
        """Retrieves all transcriptions and associated user information from the database."""
        raise NotImplementedError

    @read
    @abstractmethod
    def get_all_unique_transcriptions(
        self, session: Session, mode: Literal["file_name", "user_id"]
    ) -> Sequence[Transcription]:
        """Retrieves all unique transcriptions from the database."""
        raise NotImplementedError

    @read
    @abstractmethod
    def get_user(self, session: Session, user_id: Union[str, UUID]) -> Optional[User]:
        """Retrieves a user from the database."""
        raise NotImplementedError

    @read
    @abstractmethod
    def get_words_from_utterance_ids(
        self, session: Session, utterance_ids: List[UUID]
    ) -> Sequence[Word]:
        """Retrieves words from a list of utterance IDs."""
        raise NotImplementedError

    @read
    @abstractmethod
    def get_utterances(
        self,
        session: Session,
        utterance_ids: List[UUID],
        word_ids: Optional[List[UUID] | List[str]] = None,
    ) -> Sequence[Utterance]:
        """Retrieves utterances from a list of utterance IDs."""
        raise NotImplementedError

    @read
    @abstractmethod
    def get_transcriptions_by_user_ids(
        self, session: Session, user_ids: List[str]
    ) -> Sequence[Transcription]:
        """Retrieves transcriptions for multiple user IDs."""
        raise NotImplementedError

    @read
    @abstractmethod
    def get_latest_schema(self, session: Session) -> Optional[Schema]:
        """Retrieves the latest schema based on the created_at timestamp."""
        raise NotImplementedError

    # SCHEMAS

    @write
    @abstractmethod
    def save_schema(self, session: Session, schema: UnvalidatedSchema) -> Schema:
        """Saves a schema created from text to the database."""
        raise NotImplementedError

    @read
    @abstractmethod
    def get_schema(
        self, session: Session, schema_id: Union[str, UUID]
    ) -> Optional[Schema]:
        """Retrieves a schema from the database."""
        raise NotImplementedError

    @read
    @abstractmethod
    def get_all_users(self, session: Session) -> Sequence[User]:
        """Retrieves all users from the database."""
        raise NotImplementedError

    # CLIPS AND VIDEOS

    @write
    @abstractmethod
    def save_clip(
        self,
        session: Session,
        clip: CreateClip,
        video_id: UUID | str,
    ) -> Clip:
        """Saves a clip to the database."""
        raise NotImplementedError

    @write
    @abstractmethod
    def save_clips(
        self,
        session: Session,
        clips: Sequence[CreateClip],
        video_id: UUID | str,
    ) -> Sequence[Clip]:
        """Saves a list of clips to the database."""
        raise NotImplementedError

    @read
    @abstractmethod
    def get_clips_from_video_ids(
        self, session: Session, video_ids: List[UUID]
    ) -> Sequence[Clip]:
        """Retrieves clips from a list of video IDs."""
        raise NotImplementedError

    @write
    @abstractmethod
    def save_video(
        self, session: Session, video: Union[UnvalidatedVideo, Video]
    ) -> Video:
        """Saves a video to the database."""
        raise NotImplementedError

    @read
    @abstractmethod
    def get_video(
        self, session: Session, video_id: Union[str, UUID]
    ) -> Optional[Video]:
        """Retrieves a video from the database."""
        raise NotImplementedError
    
    @read
    @abstractmethod
    def get_all_videos(self, session: Session) -> Sequence[Video]:
        """Retrieves all videos from the database."""
        raise NotImplementedError

    @write
    @abstractmethod
    def prepare_clips_from_metadata(
        self,
        session: Session,
        file_metadatas: Sequence[FileMetadata],
        creator: Employee,
        hide_metadata: bool = False,
    ) -> VideoMetrics:
        """
        Prepares and saves clips from file metadata.

        Returns:
        VideoMetrics containing aggregate video information and saved clips.
        """
        raise NotImplementedError

# %% ../nbs/07_db.ipynb 15
TModelOut = TypeVar("TModelOut", bound=SQLModel)


class SqlModelDatabase(AbstractDatabase["SqlModelDatabase"]):
    def __init__(self, database_url: str):
        self.engine = create_engine(database_url, pool_pre_ping=True)
        self.employee = None

    class Operations(AbstractDatabase.Operations):
        def __init__(self, database: "SqlModelDatabase"):
            self.database = database
            
        def close(self) -> None:
            self.database.engine.dispose()

    def as_employee(self, employee: Employee):
        self.employee = employee
        return self

    @public
    def get_employee(
        self, session: Session, employee_id: Union[str, UUID]
    ) -> Optional[Employee]:
        return session.exec(select(Employee).where(Employee.id == employee_id)).first()

    def permissions_set_session_variables(self, session: Session, employee: Employee):
        """Same as set_session_variables, but without any kind of permissions. Use at your own risk."""
        session.execute(text(f"SET app.current_company_id = '{employee.company_id}'"))
        session.execute(
            text(
                f"SET app.current_permission_level = '{employee.permission_level.name}'"
            )
        )
        session.execute(text(f"SET app.current_employee_id = '{employee.id}'"))
        session.commit()

    @public
    def set_session_variables(self, session: Session, employee: Employee):
        session.execute(text(f"SET app.current_company_id = '{employee.company_id}'"))
        session.execute(
            text(f"SET app.current_permission_level = '{employee.permission_level}'")
        )
        session.commit()

    @public
    def clear_session_variables(self, session: Session):
        session.execute(text("RESET app.current_company_id"))
        session.execute(text("RESET app.current_permission_level"))
        session.execute(text("RESET app.current_employee_id"))
        session.commit()

    def permissions_clear_session_variables(self, session: Session):
        session.execute(text("RESET app.current_company_id"))
        session.execute(text("RESET app.current_permission_level"))
        session.execute(text("RESET app.current_employee_id"))
        session.commit()

    def get_session_for_employee(self, public: bool = False) -> Session:
        if public:
            return Session(self.engine, expire_on_commit=False)
        if self.employee is None:
            raise PermissionError("Employee not set for this session.")
        return Session(self.engine, expire_on_commit=False)

    @public
    def authenticate_employee(
        self, session: Session, email: str, password: str
    ) -> Optional[Employee]:
        employee = session.exec(select(Employee).where(Employee.email == email)).first()

        if employee:
            print(employee.hashed_password.decode("utf-8"))
            if pbkdf2_sha256.verify(password, employee.hashed_password.decode("utf-8")):
                print("Password verified successfully")
                return employee
            else:
                print("Password verification failed")
        else:
            print("No employee found with this email")

        return None

    @write
    def save_employee(
        self,
        session: Session,
        unvalidated_employee: CreateEmployee,
        company_id: UUID,
    ) -> Employee:
        hashed_password = pbkdf2_sha256.hash(unvalidated_employee.password).encode(
            "utf-8"
        )
        company = session.exec(select(Company).where(Company.id == company_id)).first()
        if company is None:
            raise ValueError(f"Company with id {company_id} not found")
        print(unvalidated_employee.model_dump())
        employee_to_validate = Employee(
            **unvalidated_employee.model_dump(),
            hashed_password=hashed_password,
            company_id=company_id,
        )
        print("employee_to_validate.company_id", employee_to_validate.company_id)
        employee = Employee.model_validate(employee_to_validate)
        company.employees.append(employee)
        session.commit()
        session.refresh(employee)
        return employee

    @write
    def update_employee(
        self,
        session: Session,
        employee_id: str | UUID,
        values_to_update: dict[str, Any],
    ) -> Employee:
        employee = session.exec(
            select(Employee).where(Employee.id == employee_id)
        ).first()
        if employee is None:
            raise ValueError(f"Employee with id {employee_id} not found")
        for key, value in values_to_update.items():
            setattr(employee, key, value)
        session.add(employee)
        session.commit()
        session.refresh(employee)
        return employee

    @public
    def save_company_and_employee(
        self,
        session: Session,
        unvalidated_company: UnvalidatedCompany,
        unvalidated_employee: CreateEmployee,
    ) -> Tuple[Company, Employee]:
        # check if employee exists
        existing_employee = session.exec(
            select(Employee).where(Employee.email == unvalidated_employee.email)
        ).first()
        if existing_employee:
            raise ValueError(
                f"Employee with email {unvalidated_employee.email} already exists"
            )
        company = Company.model_validate(unvalidated_company)
        session.add(company)
        session.commit()
        session.refresh(company)
        hashed_password = pbkdf2_sha256.hash(unvalidated_employee.password).encode(
            "utf-8"
        )
        employee_to_validate = Employee(
            **unvalidated_employee.model_dump(),
            hashed_password=hashed_password,
            company_id=company.id,
        )
        employee = Employee.model_validate(employee_to_validate)
        company.employees.append(employee)
        session.commit()
        session.refresh(employee)

        return company, employee

    def _save(
        self,
        session: Session,
        model: SQLModel,
        output_model: Type[TModelOut],
        joinedload_keys: List[Callable[[TModelOut], Any]] = [],
    ) -> TModelOut:
        valid_model = output_model.model_validate(model)
        session.add(valid_model)
        session.commit()
        if joinedload_keys:
            model_to_return = session.exec(
                select(output_model)
                .options(joinedload(*joinedload_keys))
                .where(output_model.id == valid_model.id)
            ).first()
        else:
            model_to_return = session.exec(
                select(output_model).where(output_model.id == valid_model.id)
            ).first()
        if model_to_return is None:
            raise ValueError(
                f"{output_model.__name__} with id {valid_model.id} not found"
            )
        return model_to_return

    @write
    def save_user(self, session: Session, user: UnvalidatedUser) -> User:
        return self._save(session, user, User)

    @write
    def delete_user(self, session: Session, user_id: UUID) -> None:
        user = session.exec(select(User).where(User.id == user_id)).first()
        if user is None:
            raise ValueError(f"User with id {user_id} not found")
        session.delete(user)
        session.commit()

    @write
    def update_user(
        self, session: Session, user_id: UUID, values_to_update: dict[str, Any]
    ) -> User:
        user = session.exec(select(User).where(User.id == user_id)).first()
        if user is None:
            raise ValueError(f"User with id {user_id} not found")
        for key, value in values_to_update.items():
            setattr(user, key, value)
        session.add(user)
        session.commit()
        session.refresh(user)
        return user

    @write
    def save_file_metadata(
        self, session: Session, metadata: UnvalidatedFileMetadata
    ) -> FileMetadata:
        return self._save(
            session,
            metadata,
            FileMetadata,
            joinedload_keys=[FileMetadata.transcription],
        )

    @read
    def get_file_metadata(
        self, session: Session, file_id: Union[str, UUID]
    ) -> Optional[FileMetadata]:
        return session.exec(
            select(FileMetadata).where(FileMetadata.id == file_id)
        ).first()

    @write
    def update_file_metadata(
        self, session: Session, file_id: UUID, values_to_update: dict[str, Any]
    ) -> FileMetadata:
        metadata = session.exec(
            select(FileMetadata).where(FileMetadata.id == file_id)
        ).first()
        if metadata is None:
            raise ValueError(f"FileMetadata with id {file_id} not found")
        for key, value in values_to_update.items():
            setattr(metadata, key, value)
        session.add(metadata)
        session.commit()
        session.refresh(metadata)
        return metadata

    @read
    def get_file_metadata_from_list_of_transcript_ids(
        self, session: Session, transcript_ids: List[str]
    ) -> Sequence[FileMetadata]:
        order_case = case(
            {
                transcript_id: index
                for index, transcript_id in enumerate(transcript_ids)
            },
            value=Transcription.id,
        )
        return session.exec(
            select(FileMetadata)
            .options(
                joinedload(FileMetadata.transcription), joinedload(FileMetadata.user)
            )  # type: ignore - selectinload type is weird
            .join(Transcription)
            .where(col(Transcription.id).in_(transcript_ids))
            .order_by(order_case)
        ).all()

    @write
    def save_transcription(
        self,
        session: Session,
        transcription: UnvalidatedTranscription,
        utterances: List[UnvalidatedUtterance],
    ) -> Transcription:
        if len(utterances) == 0:
            raise ValueError("At least one utterance must be provided")
        valid_transcription = Transcription.model_validate(transcription)
        session.add(valid_transcription)
        for utterance in utterances:
            words = [Word.model_validate(word) for word in utterance.words]
            utterance_to_save = Utterance.model_validate(
                utterance.model_copy(update={"words": words})
            )
            valid_transcription.utterances.append(utterance_to_save)
        session.commit()
        session.refresh(valid_transcription)
        # Eagerly load the associated utterances and words
        transcript_with_utterances_words = session.exec(
            select(Transcription)
            .options(joinedload(Transcription.utterances).joinedload(Utterance.words))  # type: ignore - selectinload type is weird
            .where(Transcription.id == valid_transcription.id)
        ).first()
        if transcript_with_utterances_words is None:
            raise ValueError(
                f"Transcription with id {valid_transcription.id} not found"
            )
        return transcript_with_utterances_words

    @read
    def get_transcription(
        self, session: Session, transcription_id: Union[str, UUID]
    ) -> Optional[Transcription]:
        return session.exec(
            select(Transcription).where(Transcription.id == transcription_id)
        ).first()

    @read
    def get_transcriptions(
        self,
        session: Session,
        user_id: Optional[Union[str, UUID]] = None,
        transcription_ids: Optional[List[UUID]] = None,
    ) -> Sequence[Transcription]:
        if transcription_ids:
            transcript_with_file_meta = (
                select(Transcription)
                .join(FileMetadata)
                .options(joinedload(Transcription.file_metadata))  # type: ignore - selectinload type is weird
                .options(joinedload(Transcription.utterances))  # type: ignore - selectinload type is weird
                .where(col(Transcription.id).in_(transcription_ids))
            )
        else:
            transcript_with_file_meta = (
                select(Transcription)
                .join(FileMetadata)
                .options(joinedload(Transcription.file_metadata))  # type: ignore - selectinload type is weird
                .where(FileMetadata.user_id == user_id)
            )
        return session.exec(transcript_with_file_meta).unique().all()

    @write
    def update_transcription(
        self, session: Session, transcription_id: UUID, values_to_update: dict[str, Any]
    ) -> Transcription:
        transcription = session.exec(
            select(Transcription).where(Transcription.id == transcription_id)
        ).first()
        if transcription is None:
            raise ValueError(f"Transcription with id {transcription_id} not found")
        for key, value in values_to_update.items():
            setattr(transcription, key, value)
        session.add(transcription)
        session.commit()
        session.refresh(transcription)
        return transcription

    @read
    def get_words_from_utterance_ids(
        self, session: Session, utterance_ids: List[UUID]
    ) -> Sequence[Word]:
        return session.exec(
            select(Word).where(col(Word.utterance_id).in_(utterance_ids))
        ).all()

    @read
    def get_utterances(
        self,
        session: Session,
        utterance_ids: List[UUID] | List[str],
        word_ids: Optional[List[UUID] | List[str]] = None,
    ) -> Sequence[Utterance]:
        if len(utterance_ids) == 0:
            raise ValueError("utterance_ids must be provided")
        utterance_ids_str = ", ".join(f"'{str(id)}'" for id in utterance_ids)
        if word_ids:
            word_ids_str = ", ".join(f"'{str(id)}'" for id in word_ids)
            query = f"""
            SELECT utterance.*,
                word.id as word_id,
                word.confidence as word_confidence,
                word.end as word_end,
                word.speaker as word_speaker,
                word.start as word_start,
                word.text as word_text,
                word.company_id as word_company_id,
                word.created_by_id as word_created_by_id,
                transcription.id as transcription_id,
                transcription.file_id as transcription_file_id,
                transcription.created_at as transcription_created_at,
                transcription.updated_at as transcription_updated_at,
                transcription.embedded as transcription_embedded,
                transcription.text as transcription_text,
                transcription.company_id as transcription_company_id,
                transcription.created_by_id as transcription_created_by_id
            FROM utterance
            LEFT JOIN word ON utterance.id = word.utterance_id
            LEFT JOIN transcription ON utterance.transcription_id = transcription.id
            WHERE utterance.id IN ({utterance_ids_str})
            AND (word.id IN ({word_ids_str}))
            ORDER BY utterance.start, word.start
            """
        else:
            query = f"""
            SELECT utterance.*,
                word.id as word_id,
                word.confidence as word_confidence,
                word.end as word_end,
                word.speaker as word_speaker,
                word.start as word_start,
                word.text as word_text,
                word.company_id as word_company_id,
                word.created_by_id as word_created_by_id,
                transcription.id as transcription_id,
                transcription.file_id as transcription_file_id,
                transcription.created_at as transcription_created_at,
                transcription.updated_at as transcription_updated_at,
                transcription.embedded as transcription_embedded,
                transcription.text as transcription_text,
                transcription.company_id as transcription_company_id,
                transcription.created_by_id as transcription_created_by_id
            FROM utterance
            LEFT JOIN word ON utterance.id = word.utterance_id
            LEFT JOIN transcription ON utterance.transcription_id = transcription.id
            WHERE utterance.id IN ({utterance_ids_str})
            ORDER BY utterance.start, word.start
            """

        result = session.execute(text(query)).fetchall()

        utterances_dict: OrderedDict[UUID, Utterance] = OrderedDict()
        for row in result:
            utterance_id = row.id
            if utterance_id not in utterances_dict:
                utterances_dict[utterance_id] = Utterance(
                    id=utterance_id,
                    confidence=row.confidence,
                    end=row.end,
                    speaker=row.speaker,
                    start=row.start,
                    text=row.text,
                    company_id=row.company_id,
                    created_by_id=row.created_by_id,
                    transcription_id=row.transcription_id,
                    words=[],
                )
            
            if row.word_id:  # Check if word exists (not NULL)
                word = Word(
                    id=row.word_id,
                    confidence=row.word_confidence,
                    end=row.word_end,
                    speaker=row.word_speaker,
                    start=row.word_start,
                    text=row.word_text,
                    company_id=row.word_company_id,
                    created_by_id=row.word_created_by_id,
                    utterance_id=utterance_id,
                )
                utterances_dict[utterance_id].words.append(word)
            if row.transcription_id:
                transcription = Transcription(
                    id=row.transcription_id,
                    file_id=row.transcription_file_id,
                    created_at=row.transcription_created_at,
                    updated_at=row.transcription_updated_at,
                    embedded=row.transcription_embedded,
                    text=row.transcription_text,
                    company_id=row.transcription_company_id,
                    created_by_id=row.transcription_created_by_id,
                )
                utterances_dict[utterance_id].transcription = transcription

        de_duped_utterances = list(utterances_dict.values())

        return de_duped_utterances

    @read
    def get_user(self, session: Session, user_id: str | UUID) -> Optional[User]:
        return session.exec(select(User).where(User.id == user_id)).first()

    @write
    def save_schema(self, session: Session, schema: UnvalidatedSchema) -> Schema:
        return self._save(session, schema, Schema)

    @read
    def get_schema(
        self, session: Session, schema_id: Union[str, UUID]
    ) -> Optional[Schema]:
        return session.exec(select(Schema).where(Schema.id == schema_id)).first()

    @read
    def get_transcriptions_by_user_ids(
        self, session: Session, user_ids: List[str]
    ) -> Sequence[Transcription]:
        transcript_with_file_meta = (
            select(Transcription)
            .options(selectinload(Transcription.utterances))  # type: ignore - selectinload type is weird
            .join(FileMetadata)
            .where(col(FileMetadata.user_id).in_(user_ids))
        )
        return session.exec(transcript_with_file_meta).all()

    @read
    def get_all_unique_transcriptions(
        self, session: Session, mode: Literal["file_name", "user_id"]
    ) -> Sequence[Transcription]:
        """
        Returns all unique transcriptions and utterances based on the mode specified.
        If mode is "file_name", returns all unique transcriptions based on the file name.
        If mode is "user_id", returns all unique transcriptions based on the user ID.
        """
        if mode == "file_name":
            unique_metadata_query = session.exec(
                select(FileMetadata).distinct(col(FileMetadata.file_name))
            )
            unique_metadata_ids = [result.id for result in unique_metadata_query]
            transcripts = session.exec(
                select(Transcription)
                .options(selectinload(Transcription.utterances))  # type: ignore - selectinload type is weird
                .options(
                    selectinload(Transcription.utterances).joinedload(Utterance.words)  # type: ignore - selectinload type is weird
                )
                .options(selectinload(Transcription.file_metadata)) # type: ignore - selectinload type is weird
                .where(col(Transcription.file_id).in_(unique_metadata_ids))
            ).all()
            return transcripts
        elif mode == "user_id":
            raise NotImplementedError
        else:
            raise ValueError(f"Invalid mode: {mode}")

    @read
    def get_latest_schema(self, session: Session) -> Optional[Schema]:
        return session.exec(
            select(Schema).order_by(col(Schema.created_at).desc()).limit(1)
        ).first()

    @read
    def get_all_users(self, session: Session) -> Sequence[User]:
        return session.exec(select(User)).all()

    @write
    def save_clip(
        self,
        session: Session,
        clip: CreateClip,
        video_id: UUID | str,
    ) -> Clip:
        """Saves a clip to the database."""
        valid_clip = Clip.model_validate(clip)
        video = session.exec(select(Video).where(Video.id == video_id)).first()
        if video is None:
            raise ValueError(f"Video with id {video_id} not found")
        video.clips.append(valid_clip)
        session.add(video)
        session.commit()
        session.refresh(video)
        session.refresh(valid_clip)
        clip_query = (
            select(Clip)
            .where(Clip.id == valid_clip.id)
            .options(selectinload(Clip.words))  # type: ignore - selectinload type is weird
        )
        # need to do this extra query to load the words eagerly
        final_clip = session.exec(clip_query).first()
        if final_clip is None:
            raise ValueError(f"Clip with id {valid_clip.id} not found")
        return final_clip

    @write
    def save_clips(
        self,
        session: Session,
        clips: Sequence[CreateClip],
        video_id: UUID | str,
    ) -> Sequence[Clip]:
        video = session.exec(select(Video).where(Video.id == video_id)).first()
        clips_valid = []
        if video is None:
            raise ValueError(f"Video with id {video_id} not found")
        for clip in clips:
            clips_valid.append(Clip.model_validate(clip))
        video.clips.extend(clips_valid)
        session.add(video)
        session.commit()
        session.refresh(video)
        clips_query = (
            select(Clip)
            .where(Clip.video_id == video.id)
            .options(selectinload(Clip.words))  # type: ignore - selectinload type is weird
        )
        return session.exec(clips_query).all()

    @read
    def get_clips_from_video_ids(
        self, session: Session, video_ids: List[UUID]
    ) -> Sequence[Clip]:
        """Retrieves clips from a list of video IDs."""
        return session.exec(select(Clip).where(col(Clip.video_id).in_(video_ids))).all()

    @write
    def save_video(
        self, session: Session, video: Union[UnvalidatedVideo, Video]
    ) -> Video:
        """Saves a video to the database."""
        if isinstance(video, Video):
            # If it's an existing Video instance, merge it into the session
            valid_video = session.merge(video)
            session.commit()
        else:
            # If it's a new UnvalidatedVideo, validate and save it
            valid_video = Video.model_validate(video)
            session.add(valid_video)
            session.commit()
        video_to_return = session.exec(
            select(Video)
            .options(selectinload(Video.clips).joinedload(Clip.words))  # type: ignore - selectinload type is weird
            .where(Video.id == valid_video.id)
        ).first()
        if video_to_return is None:
            raise ValueError(f"Video with id {valid_video.id} not found")
        return video_to_return

    @read
    def get_video(
        self, session: Session, video_id: Union[str, UUID]
    ) -> Optional[Video]:
        """Retrieves a video from the database."""
        return session.exec(
            select(Video).options(selectinload(Video.clips)).where(Video.id == video_id)  # type: ignore - selectinload type is weird
        ).first()
    
    @read
    def get_all_videos(self, session: Session) -> Sequence[Video]:
        """Retrieves all videos from the database."""
        return session.exec(select(Video)).all()

    @read
    def prepare_clips_from_metadata(
        self,
        session: Session,
        file_metadatas: Sequence[FileMetadata],
        creator: Employee,
        hide_metadata: bool = False,
    ) -> VideoMetrics:
        """
        Prepares clips and video metrics from file metadata.
        Returns one clip per file metadata
        """
        file_ids = [file_metadata.id for file_metadata in file_metadatas]

        # Query 1: Get aggregated data using raw SQL
        aggregate_query = text("""
            SELECT 
                SUM(duration) as total_duration,
                MAX(frame_rate) as max_frame_rate,
                MAX(resolution_x) as max_resolution_x,
                MAX(resolution_y) as max_resolution_y
            FROM 
                file_metadata
            WHERE 
                id = ANY(:file_ids)
        """)
        aggregate_result = session.execute(
            aggregate_query, {"file_ids": file_ids}
        ).fetchone()

        file_metadata_query = select(FileMetadata).where(
            col(FileMetadata.id).in_(file_ids)
        )
        file_metadata_results = session.exec(file_metadata_query).all()

        clips: list[CreateClip] = []
        if aggregate_result is None:
            raise ValueError("Aggregate result is None")
        for file_metadata in file_metadata_results:
            # Fetch words for each file_metadata
            utterances = session.exec(
                select(Utterance).where(
                    Utterance.transcription_id == file_metadata.transcription.id
                )
            ).all()
            words = [word for utterance in utterances for word in utterance.words]

            video_type = (
                VideoType(file_metadata.file_type)
                if file_metadata.file_type
                else VideoType.video
            )

            unvalidated_clip = CreateClip(
                fps=file_metadata.frame_rate or 30,
                resolution_x=file_metadata.resolution_x
                or aggregate_result.max_resolution_x,
                resolution_y=file_metadata.resolution_y
                or aggregate_result.max_resolution_y,
                metadata_to_render=file_metadata.user.name
                if file_metadata.user
                else None,
                video_type=video_type,
                file_path=file_metadata.file_path,
                words=words,
                hide_metadata=hide_metadata,
                company_id=creator.company_id,
                created_by_id=creator.id,
            )
            clips.append(unvalidated_clip)

        return VideoMetrics(
            total_duration=aggregate_result.total_duration,
            max_fps=aggregate_result.max_frame_rate,
            max_resolution_x=aggregate_result.max_resolution_x,
            max_resolution_y=aggregate_result.max_resolution_y,
            clips=clips,
        )

    @property
    def operations(self) -> "Operations":
        return self.Operations(self)
