# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_db.ipynb.

# %% auto 0
__all__ = ['User', 'FileMetadata', 'Transcription', 'Schema', 'AbstractDatabase']

# %% ../nbs/07_db.ipynb 3
from dataclasses import dataclass
from typing import Any, List, Optional
from abc import ABC, abstractmethod
from pydantic import BaseModel

# %% ../nbs/07_db.ipynb 4
class User(BaseModel):
    id: int
    name: str
    email: str

class FileMetadata(BaseModel):
    id: int
    user_id: int
    file_name: str
    file_path: str

class Transcription(BaseModel):
    id: int
    file_id: int
    text: str

class Schema(BaseModel):
    id: int
    schema_text: str

class AbstractDatabase(ABC):
    """Abstract base class for database operations related to users, files, transcriptions, and schemas."""
    
    @abstractmethod
    def save_user(self, user: User) -> None:
        """Saves user information to the database."""
        raise NotImplementedError
    
    @abstractmethod
    def save_file_metadata(self, metadata: FileMetadata) -> None:
        """Saves metadata about files uploaded by users."""
        raise NotImplementedError
    
    @abstractmethod
    def save_transcription(self, transcription: Transcription) -> None:
        """Saves transcription data for a given file."""
        raise NotImplementedError
    
    @abstractmethod
    def get_transcriptions(self) -> List[Transcription]:
        """Retrieves all transcriptions and associated user information from the database."""
        raise NotImplementedError
    
    @abstractmethod
    def save_schema(self, schema: Schema) -> None:
        """Saves a schema created from text to the database."""
        raise NotImplementedError
