# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_db.ipynb.

# %% auto 0
__all__ = ['STRINGS_TO_SANITIZE', 'ValidString', 'TModelOut', 'sanitize_strings', 'UnvalidatedUser', 'User',
           'UnvalidatedFileMetadata', 'FileMetadata', 'UnvalidatedWord', 'Word', 'UnvalidatedUtterance', 'Utterance',
           'UnvalidatedTranscription', 'Transcription', 'UnvalidatedSchema', 'Schema', 'AbstractDatabase',
           'SqlModelDatabase']

# %% ../nbs/07_db.ipynb 3
from typing import Any, List, Sequence, Optional, cast, Type, TypeVar, Union, ForwardRef, Literal
from typing_extensions import Annotated
from abc import ABC, abstractmethod
from sqlalchemy import BigInteger
from sqlalchemy.orm import selectinload, joinedload
from pydantic import BaseModel
from pydantic.functional_validators import BeforeValidator
from sqlmodel import Field, Session, SQLModel, create_engine, select, col, Relationship
from datetime import datetime
from uuid import uuid4, UUID
from sqlalchemy import Column, JSON

# %% ../nbs/07_db.ipynb 5
STRINGS_TO_SANITIZE = ["\x00"]


def sanitize_strings(v: str) -> str:
    for string in STRINGS_TO_SANITIZE:
        v = v.replace(string, "")
    return v


# https://docs.pydantic.dev/latest/concepts/validators/#annotated-validators
ValidString = Annotated[str, BeforeValidator(sanitize_strings)]


class UnvalidatedUser(SQLModel):
    name: ValidString = Field(default=None)
    external_id: ValidString = Field(default=None)


class User(UnvalidatedUser, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    created_at: datetime = Field(default=datetime.utcnow(), nullable=False)
    updated_at: datetime = Field(default_factory=datetime.utcnow, nullable=False)
    pass


class UnvalidatedFileMetadata(SQLModel):
    user_id: UUID = Field(default=None, foreign_key="user.id")
    file_name: ValidString = Field(default=None)
    file_path: ValidString = Field(default=None)


class FileMetadata(UnvalidatedFileMetadata, table=True):
    __tablename__ = "file_metadata"
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    created_at: datetime = Field(default=datetime.utcnow(), nullable=False)
    updated_at: datetime = Field(default_factory=datetime.utcnow, nullable=False)
    transcription: "Transcription" = Relationship(back_populates="file_metadata")

class UnvalidatedWord(SQLModel):
    confidence: float
    end: int = Field(sa_column=Column(BigInteger))
    speaker: ValidString = Field(default=None)
    start: int = Field(sa_column=Column(BigInteger))
    text: ValidString = Field(default=None)


class Word(UnvalidatedWord, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    utterance_id: UUID = Field(default=None, foreign_key="utterance.id")
    utterance: "Utterance" = Relationship(back_populates="words")


class UnvalidatedUtterance(SQLModel):
    confidence: float
    end: int = Field(sa_column=Column(BigInteger))
    speaker: ValidString = Field(default=None)
    start: int = Field(sa_column=Column(BigInteger))
    text: ValidString = Field(default=None)


class Utterance(UnvalidatedUtterance, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    words: list["Word"] = Relationship(back_populates="utterance")
    transcription: "Transcription" = Relationship(back_populates="utterances")
    transcription_id: UUID = Field(default=None, foreign_key="transcription.id")


class UnvalidatedTranscription(SQLModel):
    file_id: UUID = Field(default=None, foreign_key="file_metadata.id")
    text: ValidString = Field(default=None)


class Transcription(UnvalidatedTranscription, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    created_at: datetime = Field(default=datetime.utcnow(), nullable=False)
    updated_at: datetime = Field(default_factory=datetime.utcnow, nullable=False)
    utterances: list["Utterance"] = Relationship(back_populates="transcription")
    file_metadata: "FileMetadata" = Relationship(back_populates="transcription")

    def __hash__(self):
        return hash(self.id)


class UnvalidatedSchema(SQLModel):
    input_text: ValidString = Field(default=None)
    json_schema: dict[str, Any] = Field(default={}, sa_column=Column(JSON))


class Schema(UnvalidatedSchema, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    created_at: datetime = Field(default=datetime.utcnow(), nullable=False)
    updated_at: datetime = Field(default_factory=datetime.utcnow, nullable=False)

# %% ../nbs/07_db.ipynb 6
class AbstractDatabase(ABC):
    """Abstract base class for database operations related to users, files, transcriptions, and schemas.
    Use Unvalidated Models to save raw user input, validation occurs on the model save
    """

    # OPERATIONS

    class Operations(ABC):
        @abstractmethod
        def create_all_tables(self) -> None:
            """Initializes the database."""
            raise NotImplementedError

        @abstractmethod
        def run_migrations(self) -> None:
            """Runs database migrations."""
            raise NotImplementedError

        @abstractmethod
        def close(self) -> None:
            """Closes the database connection."""
            raise NotImplementedError

    @property
    @abstractmethod
    def operations(self) -> "Operations":
        """Property that should return an instance of Operations."""
        raise NotImplementedError

    # USERS

    @abstractmethod
    def save_user(self, user: UnvalidatedUser) -> User:
        """Saves user information to the database."""
        raise NotImplementedError

    # FILES

    @abstractmethod
    def save_file_metadata(self, metadata: UnvalidatedFileMetadata) -> FileMetadata:
        """Saves metadata about a file uploaded by users."""
        raise NotImplementedError

    @abstractmethod
    def get_file_metadata(self, file_id: Union[str, UUID]) -> Optional[FileMetadata]:
        """Retrieves metadata about a file from the database."""
        raise NotImplementedError
    
    @abstractmethod
    def get_file_metadata_from_list_of_transcript_ids(self, transcript_ids: List[str]) -> Sequence[FileMetadata]:
        """Retrieves metadata about a file from the database."""
        raise NotImplementedError

    # TRANSCRIPTIONS

    @abstractmethod
    def save_transcription(
        self,
        transcription: UnvalidatedTranscription,
        utterances: List[UnvalidatedUtterance],
    ) -> Transcription:
        """Saves transcription data for a given file."""
        raise NotImplementedError

    @abstractmethod
    def get_transcriptions(self, user_id: Union[str, UUID]) -> Sequence[Transcription]:
        """Retrieves all transcriptions and associated user information from the database."""
        raise NotImplementedError
    
    @abstractmethod
    def get_all_unique_transcriptions(self, mode: Literal["file_name", "user_id"]) -> Sequence[Transcription]:
        """Retrieves all unique transcriptions from the database."""
        raise NotImplementedError

    @abstractmethod
    def get_user(self, user_id: Union[str, UUID]) -> Optional[User]:
        """Retrieves a user from the database."""
        raise NotImplementedError

    @abstractmethod
    def get_transcriptions_by_user_ids(
        self, user_ids: List[str]
    ) -> List[Transcription]:
        """Retrieves transcriptions for multiple user IDs."""
        raise NotImplementedError

    @abstractmethod
    def get_latest_schema(self) -> Optional[Schema]:
        """Retrieves the latest schema based on the created_at timestamp."""
        raise NotImplementedError

    # SCHEMAS

    @abstractmethod
    def save_schema(self, schema: UnvalidatedSchema) -> Schema:
        """Saves a schema created from text to the database."""
        raise NotImplementedError

    @abstractmethod
    def get_schema(self, schema_id: Union[str, UUID]) -> Optional[Schema]:
        """Retrieves a schema from the database."""
        raise NotImplementedError
    
    @abstractmethod
    def get_all_users(self) -> Sequence[User]:
        """Retrieves all users from the database."""
        raise NotImplementedError


# %% ../nbs/07_db.ipynb 9
TModelOut = TypeVar("TModelOut", bound=SQLModel)


class SqlModelDatabase(AbstractDatabase):
    def __init__(self, database_url: str):
        self.engine = create_engine(database_url)
        SQLModel.metadata.create_all(self.engine)

    class Operations(AbstractDatabase.Operations):
        def __init__(self, database: "SqlModelDatabase"):
            self.database = database

        def create_all_tables(self) -> None:
            SQLModel.metadata.create_all(self.database.engine)

        def run_migrations(self) -> None:
            # Implement migration logic here
            pass

        def close(self) -> None:
            self.database.engine.dispose()

    def _save(self, model: SQLModel, output_model: Type[TModelOut]) -> TModelOut:
        with Session(self.engine) as session:
            valid_model = output_model.model_validate(model)
            session.add(valid_model)
            session.commit()
            session.refresh(valid_model)
            return valid_model

    def save_user(self, user: UnvalidatedUser) -> User:
        return self._save(user, User)


    def save_file_metadata(self, metadata: UnvalidatedFileMetadata) -> FileMetadata:
        return self._save(metadata, FileMetadata)

    def get_file_metadata(self, file_id: Union[str, UUID]) -> Optional[FileMetadata]:
        with Session(self.engine) as session:
            return session.exec(
                select(FileMetadata).where(FileMetadata.id == file_id)
            ).first()
        
    def get_file_metadata_from_list_of_transcript_ids(self, transcript_ids: List[str]) -> Sequence[FileMetadata]:
        with Session(self.engine) as session:
            return session.exec(
                select(FileMetadata)
                .options(joinedload(FileMetadata.transcription))
                .join(Transcription)
                .where(col(Transcription.id).in_(transcript_ids))
            ).all()

    def save_transcription(
        self,
        transcription: UnvalidatedTranscription,
        utterances: List[UnvalidatedUtterance],
    ) -> Transcription:
        with Session(self.engine) as session:
            valid_transcription = Transcription.model_validate(transcription)
            session.add(valid_transcription)
            session.commit()
            session.refresh(valid_transcription)

            valid_utterances = [
                Utterance.model_validate(
                    utterance.model_dump(),
                    update={"transcription_id": valid_transcription.id},
                )
                for utterance in utterances
            ]
            session.add_all(valid_utterances)
            session.commit()

            for utterance, valid_utterance in zip(utterances, valid_utterances):
                for word in utterance.words:  # type: ignore
                    word = cast(UnvalidatedWord, word)
                    valid_word = Word.model_validate(
                        word.model_dump(),
                        update={"utterance_id": valid_utterance.id},
                    )
                    session.add(valid_word)
                    session.commit()
            session.commit()
            # Eagerly load the associated utterances and words
            session.refresh(valid_transcription)
            for utterance in valid_transcription.utterances:
                session.refresh(utterance)
                for word in utterance.words:
                    session.refresh(word)
            return valid_transcription

    def get_transcriptions(self, user_id: Union[str, UUID]) -> Sequence[Transcription]:
        with Session(self.engine) as session:
            transcript_with_file_meta = (
                select(Transcription)
                .join(FileMetadata)
                .where(FileMetadata.user_id == user_id)
            )
            return session.exec(transcript_with_file_meta).all()
        
    def get_user(self, user_id: str | UUID) -> Optional[User]:
        with Session(self.engine) as session:
            return session.exec(select(User).where(User.id == user_id)).first()

    def save_schema(self, schema: UnvalidatedSchema) -> Schema:
        return self._save(schema, Schema)

    def get_schema(self, schema_id: Union[str, UUID]) -> Optional[Schema]:
        with Session(self.engine) as session:
            return session.exec(select(Schema).where(Schema.id == schema_id)).first()

    def get_transcriptions_by_user_ids(
        self, user_ids: List[str]
    ) -> List[Transcription]:
        with Session(self.engine) as session:
            transcript_with_file_meta = (
                select(Transcription)
                .options(selectinload(Transcription.utterances))
                .join(FileMetadata)
                .where(col(FileMetadata.user_id).in_(user_ids))
            )
        return session.exec(transcript_with_file_meta).all()

    def get_all_unique_transcriptions(self, mode: Literal["file_name", "user_id"]) -> Sequence[Transcription]:
        """
        Returns all unique transcriptions and utterances based on the mode specified.
        If mode is "file_name", returns all unique transcriptions based on the file name.
        If mode is "user_id", returns all unique transcriptions based on the user ID.
        """
        with Session(self.engine) as session:
            if mode == "file_name":
                unique_metadata_query = session.exec(
                    select(FileMetadata)
                    .distinct(col(FileMetadata.file_name))
                )
                unique_metadata_ids = [result.id for result in unique_metadata_query]
                transcripts = session.exec(
                    select(Transcription)
                    .options(selectinload(Transcription.utterances))
                    .where(col(Transcription.file_id).in_(unique_metadata_ids))
                ).all()
                return transcripts
            elif mode == "user_id":
                raise NotImplementedError

    def get_latest_schema(self) -> Optional[Schema]:
        with Session(self.engine) as session:
            return session.exec(
                select(Schema).order_by(col(Schema.created_at).desc()).limit(1)
            ).first()
        
    def get_all_users(self) -> Sequence[User]:
        with Session(self.engine) as session:
            return session.exec(select(User)).all()

    @property
    def operations(self) -> "Operations":
        return self.Operations(self)
