# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_extraction.ipynb.

# %% auto 0
__all__ = ['ALiteLLM', 'ModelType', 'QuestionSchema', 'Questions', 'AnswerSchema', 'AnswerCategorySchema', 'Answers',
           'AIModelClient', 'QADataManager']

# %% ../nbs/04_extraction.ipynb 3
from enum import Enum
from typing import List, Union, Optional, Annotated
from pydantic import BaseModel, Field
from instructor import patch, Mode
from litellm import LiteLLM, acompletion
import litellm
from dotenv import load_dotenv

litellm.drop_params = True

load_dotenv()

# %% ../nbs/04_extraction.ipynb 4
# custom ALiteLLM class to patch acompletion support, which isn't available in vanilla litellm-instructor integration. https://github.com/jxnl/instructor/blob/b06eb4faa32e7b5e0f3628a611490efd042868fa/docs/blog/posts/learn-async.md#L4
class ALiteLLM(LiteLLM):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.chat.completions.create = self._patched_acompletion

    async def _patched_acompletion(self, *args, **kwargs):
        return await acompletion(
            *args,
            **kwargs
        )

# %% ../nbs/04_extraction.ipynb 7
class ModelType(Enum):
    CLAUDE_3_HAIKU = "claude-3-haiku-20240307"
    CLAUDE_3_SONNET = "claude-3-sonnet-20240229"
    GPT_4_0125_PREVIEW = "gpt-4-0125-preview"
    GPT_3_5_TURBO = "gpt-3.5-turbo"
    GPT_4_TURBO = "gpt-4-turbo-2024-04-09"
    CLAUDE_3_OPUS = "claude-3-opus-20240229"
    GPT_4o = "gpt-4o"


class QuestionSchema(BaseModel):
    id: str
    text: str
    output_type: str
    categories: Optional[List[str]] = None


class Questions(BaseModel):
    questions: List[QuestionSchema]


class AnswerSchema(BaseModel):
    question_id: str
    text: str = Field(..., title="The answer to the question")

    def __hash__(self):
        return hash(self.question_id)


class AnswerCategorySchema(BaseModel):
    question_id: str
    categories: Union[str, List[str]] = Field(
        ...,
        title="The answer to the question. Must be a valid category or list of category from the originally provided text.",
    )


class Answers(BaseModel):
    answers: List[Union[AnswerSchema, AnswerCategorySchema]]

    def __hash__(self):
        return hash(self.answers[0].question_id)


class AIModelClient:
    """
    A client for interacting with various language models to create schemas and extract information.

    Args:
        model_type (ModelType): The type of language model to use.
    """

    def __init__(
        self,
        model_type: ModelType = ModelType.GPT_4o,
        max_retries: int = 10,
        max_tokens: int = 4096,
    ):
        self.client = patch(ALiteLLM(), mode=Mode.JSON)  # type: ignore
        self.model_type = model_type
        self.max_tokens = max_tokens
        self.max_retries = max_retries
        self.start_with = "{"

    async def create_schema(
        self, questions: str, model_type_override: Optional[ModelType] = None
    ) -> Questions:
        """
        Create a schema from the given questions.

        Args:
            questions (str): The questions to be structured.

        Returns:
            Questions: The structured questions.
        """
        EXTRACTION_PROMPT_B = f"Extract a set of structured questions from the user-provided unstructured text using ONLY JSON with NO preamble so it can be validated immediately, with no spacing or newlines, following the following JSON schema format: {Questions.model_json_schema()}. i.e., start your response with {self.start_with}. If the information requested in the question is absent, leave the answer completely blank or write 'N/a'. You should respond in a message, not a tool or function call, if that's an option for you. Output type can be 'string', or 'category'. If output type is 'category', then the categories key should be a list of relevant categories provided by the user."

        response: Questions = await self.client.chat.completions.create(  # type: ignore
            model=model_type_override.value
            if model_type_override
            else self.model_type.value,
            response_model=Questions,
            max_retries=self.max_retries,
            max_tokens=self.max_tokens,
            messages=[
                {"role": "system", "content": EXTRACTION_PROMPT_B},
                {
                    "role": "user",
                    "content": questions,
                },
            ],
        )
        if isinstance(response, Questions):
            return response
        else:
            raise ValueError("Response is not of type Questions")

    async def extract_information(
        self,
        text: str,
        questions: Questions,
        model_type_override: Optional[ModelType] = ModelType.GPT_4o,
    ) -> Answers:
        """
        Extract information from the given text using the provided schema.

        Args:
            text (str): The text to extract information from.
            schema (Questions): The schema to use for extraction.

        Returns:
            Answers: The extracted information.
        """
        EXTRACTION_PROMPT_C = f"Answer the following questions based on the user-provided text using ONLY JSON with NO preamble so it can be validated immediately, with no spacing or newlines, following the following JSON schema format: {Answers.model_json_schema()}, i.e., start your response with {self.start_with}. You should respond in a message, not a tool or function call, if that's an option for you. Be concise, and answer only the question or questions provided: {questions.model_dump_json()}. Answer these questions in the most intelligent way possible, as this is high-stakes for the user to get it right. Provide direct supporting quotes where possible."
        EXTRACTION_PROMPT_A = f"You are a product analyst assistant. Please look at the transcripts provided and give careful responses for each field, explaining the answer and your rationale to the question in detail while also providing 1-3 direct quotes from the transcript when relevant, and edited lightly if needed for brevity and clarity.\n\nBe as comprehensive as possible, providing all relevant information.\n\nHere's the scheme you must respond in, it will be validated with pydantic and so you MUST respond only with the JSON.\n\nUse Null if the answer is not present in the transcript, not every question is asked each time.\n\nUse context clues to understand who the researcher is in the conversation and which speaker is being interviewed.{questions.model_dump_json()} Finally, If the answer is not provided in the transcript provided, say 'N/a', unless the question says that it's required by the user — in that case, provide your best analysis based on the provided info."

        response: Answers = await self.client.chat.completions.create(  # type: ignore
            model=model_type_override.value
            if model_type_override
            else self.model_type.value,
            response_model=Answers,
            max_retries=self.max_retries,
            max_tokens=self.max_tokens,
            messages=[
                {"role": "system", "content": EXTRACTION_PROMPT_A},
                {"role": "user", "content": text},
            ],
            response_format={"type": "json_object"},
        )
        if isinstance(response, Answers):
            return response
        else:
            raise ValueError("Response is not of type Answers")

# %% ../nbs/04_extraction.ipynb 8
import pandas as pd
from io import BytesIO


class QADataManager:
    def __init__(self):
        self.df = pd.DataFrame()

    def add_answers(
        self, questions: Questions, answers: Answers, document_name: str, user_id: str
    ):
        data = {"document_name": document_name, "user_id": user_id}
        for question in questions.questions:
            answer = next(
                (a for a in answers.answers if a.question_id == question.id), None
            )
            if answer:
                if isinstance(answer, AnswerSchema):
                    data[question.text] = answer.text
                else:
                    # Ensure categories is a list before joining
                    categories = (
                        answer.categories
                        if isinstance(answer.categories, list)
                        else [answer.categories]
                    )
                    data[question.text] = ", ".join(categories)

        new_df = pd.DataFrame([data])
        self.df = pd.concat([self.df, new_df], ignore_index=True)

    def to_csv(self, file_path: str):
        self.df.to_csv(file_path, index=False)

    def to_csv_bytes(self) -> bytes:
        csv_buffer = BytesIO()
        self.df.to_csv(csv_buffer, index=False)
        csv_bytes = csv_buffer.getvalue()
        return csv_bytes
    
    def merge_rows_by_user(self):
        """Merge rows by user_id, concatenating the data for each user. Document row is also concatenated."""
        if 'user_id' not in self.df.columns:
            raise ValueError("DataFrame does not contain a 'user_id' column.")
        def concat_documents(docs: "pd.Series[str]"):
            # Filter out 'N/a', 'na', 'nan', 'null', and actual NaN values based on lowered case without altering original case
            filtered_docs = docs[docs.str.lower().str.strip().replace(['n/a', 'na', 'nan', 'null', ''], pd.NA).notna()]
            if len(filtered_docs) == 1:
                return filtered_docs.iloc[0]
            return ',\n'.join(f"{i+1}. {doc}" for i, doc in enumerate(filtered_docs))

        aggregation_functions = {col: concat_documents for col in self.df.columns if col != 'user_id'}
        self.df = self.df.groupby('user_id').agg(aggregation_functions).reset_index()

