# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_extraction.ipynb.

# %% auto 0
__all__ = ['ModelType', 'QuestionSchema', 'Questions', 'AnswerSchema', 'AnswerCategorySchema', 'Answers', 'AIModelClient',
           'QADataManager']

# %% ../nbs/04_extraction.ipynb 3
from enum import Enum
from typing import List, Union, Optional
from pydantic import BaseModel, Field
from instructor import patch, Mode
from litellm import LiteLLM
import litellm
from dotenv import load_dotenv

litellm.drop_params = True

load_dotenv()

# %% ../nbs/04_extraction.ipynb 4
class ModelType(Enum):
    CLAUDE_3_HAIKU = "claude-3-haiku-20240307"
    CLAUDE_3_SONNET = "claude-3-sonnet-20240229"
    GPT_4_0125_PREVIEW = "gpt-4-0125-preview"
    GPT_3_5_TURBO = "gpt-3.5-turbo"
    CLAUDE_3_OPUS = "claude-3-opus-20240229"


class QuestionSchema(BaseModel):
    id: str
    text: str
    output_type: str
    categories: Optional[List[str]] = None


class Questions(BaseModel):
    questions: List[QuestionSchema]


class AnswerSchema(BaseModel):
    question_id: str
    text: str = Field(..., title="The answer to the question")


class AnswerCategorySchema(BaseModel):
    question_id: str
    categories: Union[str, List[str]] = Field(
        ...,
        title="The answer to the question. Must be a valid category or list of category from the originally provided text.",
    )


class Answers(BaseModel):
    answers: List[Union[AnswerSchema, AnswerCategorySchema]]


class AIModelClient:
    """
    A client for interacting with various language models to create schemas and extract information.

    Args:
        model_type (ModelType): The type of language model to use.
    """

    def __init__(
        self,
        model_type: ModelType = ModelType.CLAUDE_3_HAIKU,
        max_retries: int = 10,
        max_tokens: int = 4096,
    ):
        self.client = patch(LiteLLM(), mode=Mode.JSON)  # type: ignore
        self.model_type = model_type
        self.max_tokens = max_tokens
        self.max_retries = max_retries
        self.start_with = "{"

    def create_schema(
        self, questions: str, model_type_override: Optional[ModelType] = None
    ) -> Questions:
        """
        Create a schema from the given questions.

        Args:
            questions (str): The questions to be structured.

        Returns:
            Questions: The structured questions.
        """
        response: Questions = self.client.chat.completions.create(  # type: ignore
            model=model_type_override.value
            if model_type_override
            else self.model_type.value,
            response_model=Questions,
            max_retries=self.max_retries,
            max_tokens=self.max_tokens,
            messages=[
                {
                    "role": "system",
                    "content": f"Extract a set of structured questions from the user-provided unstructured text using ONLY JSON with NO preamble so it can be validated immediately, with no spacing or newlines, following the following JSON schema format: {Questions.model_json_schema()}. i.e., start your response with {self.start_with}. You should respond in a message, not a tool or function call, if that's an option for you. Output type can be 'string', or 'category'. If output type is 'category', then the categories key should be a list of relevant categories provided by the user.",
                },
                {
                    "role": "user",
                    "content": questions,
                },
            ],
        )
        if isinstance(response, Questions):
            return response
        else:
            raise ValueError("Response is not of type Questions")

    def extract_information(
        self,
        text: str,
        schema: Questions,
        model_type_override: Optional[ModelType] = ModelType.CLAUDE_3_OPUS,
    ) -> Answers:
        """
        Extract information from the given text using the provided schema.

        Args:
            text (str): The text to extract information from.
            schema (Questions): The schema to use for extraction.

        Returns:
            Answers: The extracted information.
        """
        response: Answers = self.client.chat.completions.create(  # type: ignore
            model=model_type_override.value
            if model_type_override
            else self.model_type.value,
            response_model=Answers,
            max_retries=self.max_retries,
            max_tokens=self.max_tokens,
            messages=[
                {
                    "role": "system",
                    "content": f"Answer the following questions based on the user-provided text using ONLY JSON with NO preamble so it can be validated immediately, with no spacing or newlines, following the following JSON schema format: {Answers.model_json_schema()}, i.e., start your response with {self.start_with}. You should respond in a message, not a tool or function call, if that's an option for you. Be concise, and answer only the question or questions provided: {schema.model_dump_json()}. Answer these questions in the most intelligent way possible, as this is high-stakes for the user to get it right.",
                },
                {"role": "user", "content": text},
            ],
        )
        if isinstance(response, Answers):
            return response
        else:
            raise ValueError("Response is not of type Answers")

# %% ../nbs/04_extraction.ipynb 5
import pandas as pd
from io import BytesIO


class QADataManager:
    def __init__(self):
        self.df = pd.DataFrame()

    def add_answers(
        self, questions: Questions, answers: Answers, document_name: str, user_id: str
    ):
        data = {"document_name": document_name, "user_id": user_id}
        for question in questions.questions:
            answer = next(
                (a for a in answers.answers if a.question_id == question.id), None
            )
            if answer:
                data[question.text] = (
                    answer.text
                    if isinstance(answer, AnswerSchema)
                    else ", ".join(answer.categories)
                )

        new_df = pd.DataFrame([data])
        self.df = pd.concat([self.df, new_df], ignore_index=True)  # type: ignore

    def to_csv(self, file_path: str):
        self.df.to_csv(file_path, index=False)

    def to_csv_bytes(self) -> bytes:
        csv_buffer = BytesIO()
        self.df.to_csv(csv_buffer, index=False)
        csv_bytes = csv_buffer.getvalue()
        return csv_bytes

    return csv_bytes


