"""For filesystems that store video, text, and more"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_filesystems.ipynb.

# %% auto 0
__all__ = ['File', 'AudioFile', 'VideoFile', 'TextFile', 'FileSystemType', 'FilePathType', 'AbstractFileSystem',
           'LocalFileSystem']

# %% ../nbs/01_filesystems.ipynb 4
from typing import Generator, Optional, BinaryIO, IO, Any, cast
from pydantic import BaseModel
from .db import User
from dataclasses import dataclass, field
from enum import Enum
from urllib.parse import quote
from abc import ABC, abstractmethod
import shutil
from datetime import datetime
from contextlib import contextmanager
from pathlib import Path


import io

from uuid import uuid4

# %% ../nbs/01_filesystems.ipynb 5
class File(BaseModel):
    uri: str
    content: Optional[bytes | io.BytesIO] = None

    class Config:
        arbitrary_types_allowed = True


class AudioFile(File):
    start: int
    end: int
    file: str


class VideoFile(File):
    start: int
    end: int
    file: str


class TextFile(File):
    pass

# %% ../nbs/01_filesystems.ipynb 6
class FileSystemType(Enum):
    LOCAL = "local"
    R2 = "r2"


class FilePathType(Enum):
    """Files can come in as Audio, Video, Text, or PDF.
    The original file should be saved in user_id/originals.
    Transformed files should be saved in user_id/audio, user_id/video, user_id/text, user_id/pdf
    Relationships back to original file should be saved in the db, but that's not handled by filesystem APIs"""

    USER_ID_BASE = "user_id"
    USER_ID_BASE_AUDIO = "user_id_audio"
    USER_ID_BASE_VIDEO = "user_id_video"
    USER_ID_BASE_CLIPS = "user_id_clips"
    USER_ID_BASE_TEXT = "user_id_text"
    USER_ID_BASE_PDF = "user_id_pdf"


@dataclass
class AbstractFileSystem(ABC):
    base_path: str = field(default="")

    @property
    @abstractmethod
    def tenant_video_path(self) -> str:
        """The path for tenant-scoped videos"""
        raise NotImplementedError("This method should be implemented by subclasses")

    @abstractmethod
    def build_user_path(self, user: User, file_path_type: FilePathType) -> str:
        """Build the file path according to the inputted objects and rules.
        Does not create resources, just a string formatter"""
        raise NotImplementedError("This method should be implemented by subclasses")

    @abstractmethod
    def create_folder(self, path: str) -> str:
        """Creates folders at the specified location. Doesn't raise errors if locaqtion exists"""
        raise NotImplementedError("This method should be implemented by subclasses")

    def sanitize_characters(self, text: str) -> str:
        """Replace non-ASCII characters with their Unicode codepoint representations."""
        return (
            text.encode("unicode_escape")
            .decode()
            .replace("\\u", "u")
            .replace("\\", "_")
            .replace("\\U", "U")
        )

    def sanitize_filename(self, filename: str) -> str:
        """Use as an add-on to sanitize characters. Replace non-ASCII characters with their Unicode codepoint representations."""
        return filename.replace("/", "_").replace("\\", "_").replace(" ", "_")

    @abstractmethod
    def validate_access(self, user: User, path: str) -> bool:
        """Check if the user has access to the specified location"""
        raise NotImplementedError("This method should be implemented by subclasses")

    @abstractmethod
    def check_exists(self, path: str) -> bool:
        """Check if the file exists at the specified path."""
        raise NotImplementedError("This method should be implemented by subclasses")

    @abstractmethod
    async def create_file(
        self,
        path: str,
        content: bytes | io.BytesIO,
        name: str,
        authorized: bool = False,
    ) -> File:
        """Creates files at specified path. Throws an error if the location doesn't exist.
        Does NOT check permissions — pass in authorized to allow access"""
        raise NotImplementedError("This method should be implemented by subclasses")

    @abstractmethod
    def read_file(self, path: str, load_content: bool = False) -> File:
        """Reads the file at the specified path.
        If load_content is True, the content of the file is loaded into memory.
        Otherwise, the content is set to None."""
        raise NotImplementedError("This method should be implemented by subclasses")

    @abstractmethod
    async def update_file(self, path: str, content: bytes) -> File:
        raise NotImplementedError("This method should be implemented by subclasses")

    @abstractmethod
    def delete_file(self, path: str) -> File:
        raise NotImplementedError("This method should be implemented by subclasses")
    
    @abstractmethod
    def file_stream(self, path: str, mode: str = "rb") -> BinaryIO | IO[Any]:
        raise NotImplementedError("This method should be implemented by subclasses")

    @abstractmethod
    @contextmanager
    def temporary_user_directory(self, user: User) -> Generator[str, None, None]:
        """Expose a temporary directory for the user to store files in.
        This directory should be deleted after the user has finished with it.
        should be used as `with storage.temporary_user_directory(user) as tmp_dir:`"""
        raise NotImplementedError("This method should be implemented by subclasses")

# %% ../nbs/01_filesystems.ipynb 7
import os
import tempfile


@dataclass
class LocalFileSystem(AbstractFileSystem):
    base_path: str = field(
        default="",
        metadata={
            "help": "The base path for the local file system. Set to tenant_id for tenant-scoped storage"
        },
    )

    @property
    def tenant_video_path(self) -> str:
        return f"{self.base_path}/videos"

    def build_user_path(
        self: AbstractFileSystem, user: User, file_path_type: FilePathType
    ) -> str:
        if file_path_type == FilePathType.USER_ID_BASE:
            return f"{self.base_path}/{user.id}/originals"
        elif file_path_type == FilePathType.USER_ID_BASE_AUDIO:
            return f"{self.base_path}/{user.id}/audio"
        elif file_path_type == FilePathType.USER_ID_BASE_VIDEO:
            return f"{self.base_path}/{user.id}/video"
        elif file_path_type == FilePathType.USER_ID_BASE_TEXT:
            return f"{self.base_path}/{user.id}/text"
        elif file_path_type == FilePathType.USER_ID_BASE_PDF:
            return f"{self.base_path}/{user.id}/pdf"
        elif file_path_type == FilePathType.USER_ID_BASE_CLIPS:
            return f"{self.base_path}/{user.id}/clips"
        else:
            raise ValueError(f"Invalid file path type: {file_path_type}")

    def create_folder(self: AbstractFileSystem, path: str) -> str:
        path = self.sanitize_characters(path)
        os.makedirs(path, exist_ok=True)
        return path

    def validate_access(self: AbstractFileSystem, user: User, path: str) -> bool:
        # Simplified access validation: checks if path starts with user's directory
        return str(user.id) in path

    def check_exists(self: AbstractFileSystem, path: str) -> bool:
        return os.path.exists(path)

    async def create_file(
        self: AbstractFileSystem,
        path: str,
        content: bytes | io.BytesIO | IO[Any],
        name: str,
        authorized: bool = False, # remove eventually
    ) -> File:
        """if the path does exist, it will create it."""
        path_obj = Path(path)
        if not path_obj.parent.exists():
            path_obj.parent.mkdir(parents=True, exist_ok=True)
        sanitized_name = Path(self.sanitize_characters(self.sanitize_filename(name)))
        full_path = path_obj
        if name not in str(full_path):
            full_path = full_path / sanitized_name
        if full_path.exists():
            raise FileExistsError("File already exists — use update_file instead")
        if len(str(sanitized_name)) == 0:
            raise ValueError("File name cannot be empty")
        with full_path.open('wb') as f:
            if isinstance(content, bytes):
                f.write(content)
            else:
                shutil.copyfileobj(content, f)
        return File(uri=str(full_path))

    def read_file(
        self: AbstractFileSystem, path: str, load_content: bool = False
    ) -> File:
        if not os.path.isfile(path):
            raise FileNotFoundError("File does not exist")
        if load_content:
            with open(path, "rb") as f:
                content = f.read()
        else:
            content = None
        return File(uri=path, content=content)
    
    def file_stream(self, path: str, mode: str = "rb") -> BinaryIO | IO[Any]:
        full_path = os.path.join(self.base_path, path)
        if mode == 'rb':
            if not os.path.isfile(full_path):
                raise FileNotFoundError(f"File does not exist: {full_path}")
            return open(full_path, mode)
        elif mode == 'wb':
            # Ensure the directory exists
            os.makedirs(os.path.dirname(full_path), exist_ok=True)
            return open(full_path, mode)
        else:
            raise NotImplementedError("LocalFileSystem only supports read mode ('rb') and write mode ('wb')")
    
    async def update_file(self: AbstractFileSystem, path: str, content: bytes) -> File:
        if not os.path.isfile(path):
            raise FileNotFoundError("File does not exist")
        return File(uri=path)

    def delete_file(self: AbstractFileSystem, path: str) -> File:
        if not os.path.isfile(path):
            raise FileNotFoundError("File does not exist")
        os.remove(path)
        return File(uri=path)
    
    async def file_exists(self, path: str) -> bool:
        return os.path.exists(path)
    
    def generate_unique_file_name(self, original_name: str, user_id: str) -> str:
        base_name, extension = os.path.splitext(original_name)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        unique_name =quote(f"{timestamp}__{base_name}{extension}")
        return unique_name
    
    def generate_file_key(self, file_name: str, user_id: str, include_base_path: bool = True) -> str:
        # Implement file key generation logic
        if include_base_path:
            return quote(f"{self.base_path}/{user_id}/{file_name}")
        else:
            return quote(f"{user_id}/{file_name}")

    async def get_unique_file_key(self, original_name: str, user_id: str, include_base_path: bool = True) -> str:
        unique_name = self.generate_unique_file_name(original_name, user_id)
        file_key = self.generate_file_key(unique_name, user_id, include_base_path)
        
        while await self.file_exists(file_key):
            unique_name = self.generate_unique_file_name(original_name, user_id)
            file_key = self.generate_file_key(unique_name, user_id)
        
        return file_key

    @contextmanager
    def temporary_user_directory(self, user: User) -> Generator[str, None, None]:
        temp_dir = tempfile.mkdtemp()
        user_temp_dir = os.path.join(temp_dir, str(user.id))
        os.makedirs(user_temp_dir, exist_ok=True)
        try:
            yield user_temp_dir
        finally:
            shutil.rmtree(temp_dir)
