# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_filesystems.ipynb.

# %% auto 0
__all__ = ['foo', 'File', 'User', 'FileSystemType', 'FilePathType', 'AbstractFileSystem', 'LocalFileSystem']

# %% ../nbs/01_filesystems.ipynb 2
from typing import Any
from pydantic import BaseModel
from dataclasses import dataclass, field
from enum import Enum

# %% ../nbs/01_filesystems.ipynb 4
def foo():
    pass

# %% ../nbs/01_filesystems.ipynb 5
class File(BaseModel):
    uri: str


class User(BaseModel):
    id: str


class FileSystemType(Enum):
    LOCAL = "local"
    R2 = "r2"


class FilePathType(Enum):
    USER_ID = "user_id"


@dataclass
class AbstractFileSystem:
    base_path: str = field(default="")

    def build_file_path(self, user: User, file_path_type: FilePathType) -> str:
        """Build the file path according to the inputted objects and rules.
        Does not create resources, just a string formatter"""
        raise NotImplementedError("This method should be implemented by subclasses")

    def create_folder(self, path: str) -> str:
        """Creates folders at the specified location."""
        raise NotImplementedError("This method should be implemented by subclasses")

    def validate_access(self, user: User, path: str) -> bool:
        """Check if the user has access to the file at the specified path."""
        raise NotImplementedError("This method should be implemented by subclasses")

    def check_exists(self, path: str) -> bool:
        """Check if the file exists at the specified path."""
        raise NotImplementedError("This method should be implemented by subclasses")

    def create_file(self, path: str, content: bytes) -> File:
        """Creates files at specified location.
        Throws and error if the location doesn't exist, or the user doesn't have access."""
        raise NotImplementedError("This method should be implemented by subclasses")

    def read_file(self, path: str) -> File:
        raise NotImplementedError("This method should be implemented by subclasses")

    def update_file(self, path: str, content: bytes) -> File:
        raise NotImplementedError("This method should be implemented by subclasses")

    def delete_file(self, path: str) -> File:
        raise NotImplementedError("This method should be implemented by subclasses")

# %% ../nbs/01_filesystems.ipynb 6
import os
import tempfile


@dataclass
class LocalFileSystem(AbstractFileSystem):
    base_path: str = field(
        default=tempfile.mkdtemp(),
        metadata={"help": "The base path for the local file system."},
    )

    def build_file_path(
        self: AbstractFileSystem, user: User, file_path_type: FilePathType
    ) -> str:
        if file_path_type == FilePathType.USER_ID:
            return f"/Users/max/Documents/product_horse/temp/{user.id}"

    def create_folder(self: AbstractFileSystem, path: str) -> str:
        os.makedirs(path, exist_ok=True)
        return path

    def validate_access(self: AbstractFileSystem, user: User, path: str) -> bool:
        # Simplified access validation: checks if path starts with user's directory
        return path.startswith(f"/home/{user.id}")

    def check_exists(self: AbstractFileSystem, path: str) -> bool:
        return os.path.exists(path)

    def create_file(self: AbstractFileSystem, path: str, content: bytes) -> File:
        if not self.check_exists(os.path.dirname(path)) or not self.validate_access(
            User(id="default"), path
        ):
            raise FileNotFoundError("Location doesn't exist or access denied")
        with open(path, "wb") as f:
            f.write(content)
        return File(uri=path)

    def read_file(self: AbstractFileSystem, path: str) -> File:
        if not os.path.isfile(path):
            raise FileNotFoundError("File does not exist")
        return File(uri=path)

    def update_file(self: AbstractFileSystem, path: str, content: bytes) -> File:
        if not os.path.isfile(path):
            raise FileNotFoundError("File does not exist")
        return File(uri=path)

    def delete_file(self: AbstractFileSystem, path: str) -> File:
        if not os.path.isfile(path):
            raise FileNotFoundError("File does not exist")
        os.remove(path)
        return File(uri=path)
