# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_graphql.ipynb.

# %% auto 0
__all__ = ['API_URL', 'database_url', 'database_superuser_url', 'secret', 'database', 'database_superuser', 'T', 'api_key',
           'audio_editor', 'PermissionsLevel', 'RegisterResponse', 'LoginResponse', 'schema', 'graphql_app', 'app',
           'origins', 'JwtPayload', 'create_jwt', 'decode_jwt', 'Context', 'IsAuthenticated', 'FormError', 'FormErrors',
           'handle_form_validation_errors', 'retry_on_operational_error', 'transcribe_and_save_file',
           'run_remote_transcribe_and_save_file', 'Employee', 'User', 'Word', 'UtteranceSegmentInput', 'Utterance',
           'Clip', 'Video', 'Company', 'FileMetadata', 'Transcription', 'RegisterCompanySuccess', 'FileType',
           'FileMetadataInput', 'LoginSuccess', 'Query', 'Mutation', 'get_context']

# %% ../nbs/09_graphql.ipynb 4
from typing import (
    Annotated,
    Any,
    Union,
    cast,
    Sequence,
    Callable,
    TypeVar,
    TypedDict,
    List,
    Optional,
)
from functools import wraps
from enum import Enum
from uuid import UUID
import strawberry
import jwt
import modal
from jwt.exceptions import InvalidTokenError
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from strawberry.extensions import AddValidationRules
from graphql.validation import NoSchemaIntrospectionCustomRule
from .filesystems import R2StorageClient
from urllib.parse import quote
from product_horse.db import (
    SqlModelDatabase,
    Employee,
    PermissionLevel as DbPermissionLevel,
    Company,
    UnvalidatedCompany,
    CreateEmployee,
    User as DbUser,
    Utterance,
    UnvalidatedUser,
    Word,
    Video,
    Clip,
    FileMetadata,
    UnvalidatedFileMetadata,
    Transcription,
    FileStatus,
    UnvalidatedTranscription,
    UnvalidatedUtterance,
    FileType as DbFileType,
)
from datetime import datetime, timedelta

from psycopg2 import OperationalError

from pydantic import ValidationError
from product_horse.audio_video import (
    AudioEditor,
    create_video_from_utterances as create_video,
)
from .api import get_relevant_utterances_from_query

from strawberry.permission import BasePermission
from strawberry.file_uploads import Upload
from strawberry.fastapi import BaseContext, GraphQLRouter
from starlette.datastructures import UploadFile
from tenacity import retry, stop_after_attempt, wait_exponential

from dotenv import load_dotenv
import os

if not os.getenv("DATABASE_URL"):
    load_dotenv()

# %% ../nbs/09_graphql.ipynb 6
API_URL = "https://storage.producthorse.workers.dev/"  # or localhost:8787 - but won't work with transcription
# API_URL = "http://localhost:8787"

# %% ../nbs/09_graphql.ipynb 7
database_url = os.getenv("DATABASE_URL")
database_superuser_url = os.getenv("DATABASE_SUPERUSER_URL")
if database_url is None or database_superuser_url is None:
    raise ValueError("DATABASE_URL or DATABASE_SUPERUSER_URL is not set")
secret = os.getenv("SECRET")
if secret is None:
    raise ValueError("SECRET is not set")
database = SqlModelDatabase(database_url=database_url)
database_superuser = SqlModelDatabase(database_url=database_superuser_url)


class JwtPayload(TypedDict):
    id: UUID
    company_id: UUID
    exp: float
    permission_level: DbPermissionLevel


def create_jwt(
    employee_id: UUID, company_id: UUID, permission_level: DbPermissionLevel
) -> str:
    expiration = datetime.utcnow() + timedelta(weeks=2)
    payload = {
        "id": str(employee_id),
        "company_id": str(company_id),
        "exp": expiration,
        "permission_level": permission_level.value,
    }
    return jwt.encode(payload, secret, algorithm="HS256")  # type: ignore


def decode_jwt(token: str) -> JwtPayload:
    payload = cast(JwtPayload, jwt.decode(token, secret, algorithms=["HS256"]))  # type: ignore
    if "id" not in payload:
        raise InvalidTokenError
    if "company_id" not in payload:
        raise InvalidTokenError
    if datetime.fromtimestamp(payload["exp"]) < datetime.utcnow():
        raise InvalidTokenError
    return payload


class Context(BaseContext):
    @property
    def employee(self) -> Optional[Employee]:
        request = self.request
        if request is None:
            print("Request is None")
            return None
        authorization = request.headers.get("Authorization")
        if authorization is None:
            return None
        if not authorization.startswith("Bearer "):
            return None
        token = authorization.split()[1]
        payload = decode_jwt(token)
        employee_id = payload["id"]
        # run on superuser connection, since it's behind jwt auth
        employee = database_superuser.get_employee(employee_id=employee_id)
        return employee

    @property
    def jwt(self) -> Optional[str]:
        request = self.request
        if request is None:
            return None
        authorization = request.headers.get("Authorization")
        if authorization is None:
            return None
        if not authorization.startswith("Bearer "):
            return None
        token = authorization.split()[1]
        return token


class IsAuthenticated(BasePermission):
    message = "Employee is not authenticated"
    error_extensions = {"code": "UNAUTHORIZED"}

    def has_permission(self, source: Any, info: strawberry.Info, **kwargs: Any) -> bool:
        employee = info.context.employee
        return employee is not None


T = TypeVar("T")


@strawberry.type
class FormError:
    field: str
    message: str


@strawberry.type
class FormErrors:
    errors: list[FormError]


def handle_form_validation_errors(
    func: Callable[..., T],
) -> Callable[..., Union[T, FormErrors]]:
    @wraps(func)
    def wrapper(*args: Any, **kwargs: Any) -> Union[T, FormErrors]:
        try:
            return func(*args, **kwargs)
        except ValidationError as e:
            errors = [
                FormError(field=cast(str, error["loc"][-1]), message=error["msg"])
                for error in e.errors()
            ]
            return FormErrors(errors=errors)

    return wrapper

# %% ../nbs/09_graphql.ipynb 9
# Something is wrong with this retry -- doesn't help, just adds latency


def retry_on_operational_error(func: Callable[..., T]) -> Callable[..., T]:
    @wraps(func)
    @retry(
        stop=stop_after_attempt(2), wait=wait_exponential(multiplier=1, min=4, max=15)
    )
    def wrapper(*args: Any, **kwargs: Any) -> T:
        try:
            return func(*args, **kwargs)
        except OperationalError:
            raise Exception("Database access error, try again in a minute")

    return wrapper


api_key = os.getenv("ASSEMBLYAI_API_KEY")
if not api_key:
    raise ValueError("ASSEMBLYAI_API_KEY environment variable not found")
audio_editor = AudioEditor(api_key=api_key)

@retry(stop=stop_after_attempt(2), wait=wait_exponential(multiplier=1, min=4, max=15))
async def transcribe_and_save_file(
    file_metadata: FileMetadata,
    signed_url: str,
    employee: Employee,
    db: SqlModelDatabase,
) -> Transcription:
    transcription_result = await audio_editor.transcribe(signed_url, employee)
    utterances: List[UnvalidatedUtterance] = transcription_result.utterances

    unvalidated_transcription = UnvalidatedTranscription(
        file_id=file_metadata.id,
        text=transcription_result.text,
        company_id=employee.company_id,
        created_by_id=employee.id,
    )
    transcription: Transcription = db.as_employee(employee).save_transcription(
        unvalidated_transcription, utterances
    )
    return transcription

async def run_remote_transcribe_and_save_file(
    file_metadata_to_save: FileMetadata,
    employee: Employee,
    jwt: str,
):
    API_URL = os.getenv("API_URL")
    if API_URL is None:
        raise Exception("API_URL is not set")
    r2 = R2StorageClient(
        api_url=API_URL,
        base_path=str(employee.company_id),
        jwt=jwt,
    )
    db_url = os.getenv("DATABASE_URL")
    if db_url is None:
        raise Exception("DATABASE_URL is not set")
    database = SqlModelDatabase(database_url=db_url)
    signed_url = r2.get_signed_url(file_metadata_to_save.file_path)
    return await transcribe_and_save_file(
        db=database,
        file_metadata=file_metadata_to_save,
        signed_url=signed_url,
        employee=employee,
    )

# %% ../nbs/09_graphql.ipynb 11
PermissionsLevel = strawberry.enum(DbPermissionLevel)


@strawberry.experimental.pydantic.type(Employee)
class Employee:
    id: UUID
    email: str
    name: str
    permission_level: PermissionsLevel


@strawberry.experimental.pydantic.type(DbUser)
class User:
    id: UUID
    name: str


@strawberry.experimental.pydantic.type(Word)
class Word:
    id: UUID
    text: str
    start: float
    end: float


@strawberry.input
class UtteranceSegmentInput:
    utterance_id: str
    word_ids: list[str]


@strawberry.experimental.pydantic.type(Utterance)
class Utterance:
    id: UUID
    confidence: float
    start_time: float
    end_time: float
    speaker: str
    text: str
    words: list[Word]


@strawberry.experimental.pydantic.type(Clip)
class Clip:
    id: UUID
    name: str
    words: list[Word]


@strawberry.experimental.pydantic.type(Video)
class Video:
    id: UUID
    title: str
    clips: list[Clip]
    title: str
    file_path: str
    resolution_x: int
    resolution_y: int
    render_status: str
    fps: int
    signed_url: Optional[str] = None
    visibility: str


@strawberry.experimental.pydantic.type(Company)
class Company:
    id: UUID
    name: str
    employees: list[Employee]


@strawberry.experimental.pydantic.type(FileMetadata)
class FileMetadata:
    id: UUID
    file_name: str
    file_path: str


@strawberry.experimental.pydantic.type(Transcription)
class Transcription:
    id: UUID
    text: str
    created_at: datetime
    updated_at: datetime
    embedded: Optional[bool]
    utterances: list[Utterance]
    file_metadata: FileMetadata


@strawberry.type
class RegisterCompanySuccess:
    company: Company
    token: str


@strawberry.enum
class FileType(Enum):
    VIDEO = "video"
    AUDIO = "audio"
    TEXT = "text"


@strawberry.input
class FileMetadataInput:
    id: Optional[str] = None
    file_name: str
    file_type: FileType
    resolution_x: int
    resolution_y: int
    frame_rate: int
    duration: float


# Create a Union type to represent the 2 results from the mutation
RegisterResponse = Annotated[
    Union[RegisterCompanySuccess, FormErrors],
    strawberry.union("RegisterCompanyResponse"),
]


@strawberry.type
class LoginSuccess:
    employee: Employee
    token: str


LoginResponse = Annotated[
    Union[LoginSuccess, FormErrors],
    strawberry.union("LoginResponse"),
]

# %% ../nbs/09_graphql.ipynb 13
@strawberry.type
class Query:
    employee: Employee

    @strawberry.field(permission_classes=[IsAuthenticated])
    def get_users(self, info: strawberry.Info) -> Sequence[User]:
        return database.as_employee(info.context.employee).get_all_users()  # type: ignore

    @strawberry.field(permission_classes=[IsAuthenticated])
    @retry_on_operational_error
    def get_transcripts(self, info: strawberry.Info) -> Sequence[Transcription]:
        transcripts = database.as_employee(
            info.context.employee
        ).get_all_unique_transcriptions(mode="file_name")
        return transcripts  # type: ignore

    @strawberry.field(permission_classes=[IsAuthenticated])
    @retry_on_operational_error
    async def get_relevant_utterances(
        self, info: strawberry.Info, query: str, transcript_ids: Sequence[str]
    ) -> Sequence[Utterance]:
        transcript_uuids = [UUID(transcript_id) for transcript_id in transcript_ids]
        transcripts = database.as_employee(info.context.employee).get_transcriptions(
            transcription_ids=transcript_uuids
        )
        # TODO: this won't work if there are too few utterances to query. Add a check.
        # TODO: check the seconds buffer and N to return in the search_engine. Might be worth exposing those,
        # and I am not sure what seconds buffer is anyway.
        utterances = await get_relevant_utterances_from_query(
            db=database,
            employee=info.context.employee,
            query=query,
            transcripts=transcripts,
        )
        return utterances  # type: ignore

    @strawberry.field(permission_classes=[IsAuthenticated])
    @retry_on_operational_error
    def get_video(self, info: strawberry.Info, video_id: str) -> Video:
        video = database.as_employee(info.context.employee).get_video(video_id)
        if video is None:
            raise Exception("Video not found")

        r2 = R2StorageClient(
            api_url=API_URL,
            base_path=info.context.employee.company_id,
            jwt=info.context.jwt,
        )
        if video.file_path is None:
            raise Exception("Video file path is None")
        signed_url = r2.get_signed_url(video.file_path)
        video_dict = video.model_dump()
        # Remove unwanted keys from the dictionary
        keys_to_remove = ["created_by_id", "company_id", "updated_at", "created_at"]
        for key in keys_to_remove:
            video_dict.pop(key, None)
        video_dict["signed_url"] = signed_url
        try:
            if video_dict["clips"] is None:
                video_dict["clips"] = video.clips or []
        except KeyError as e:
            print(e)
            video_dict["clips"] = []
        return Video(**video_dict)

    @strawberry.field(permission_classes=[IsAuthenticated])
    @retry_on_operational_error
    def get_all_videos(self, info: strawberry.Info) -> Sequence[Video]:
        return database.as_employee(info.context.employee).get_all_videos()  # type: ignore

# %% ../nbs/09_graphql.ipynb 15
@strawberry.type
class Mutation:
    """
    Mutations are the functions that change the state of the database.
    """

    @strawberry.mutation
    def login(self, email: str, password: str) -> LoginResponse:
        employee = database_superuser.authenticate_employee(email, password)
        if employee is None:
            raise Exception("Invalid email or password")
        return LoginSuccess(
            employee=employee,  # type: ignore
            token=create_jwt(
                employee.id, employee.company_id, employee.permission_level
            ),
        )

    @strawberry.mutation
    @retry_on_operational_error
    @handle_form_validation_errors
    def register_company_and_employee(
        self, name: str, email: str, password: str, company_name: str
    ) -> RegisterResponse:
        company_to_save = UnvalidatedCompany(name=company_name)
        employee_to_save = CreateEmployee(
            name=name,
            email=email,
            password=password,
            permission_level=DbPermissionLevel.ADMIN,
        )
        company, employee = database_superuser.save_company_and_employee(
            company_to_save, employee_to_save
        )
        return RegisterCompanySuccess(
            company=company,  # type: ignore
            token=create_jwt(employee.id, company.id, employee.permission_level),
        )

    @strawberry.mutation(permission_classes=[IsAuthenticated])
    @retry_on_operational_error
    def save_user(
        self,
        info: strawberry.Info[Context, Any],
        name: str,
        external_id: Optional[str] = None,
    ) -> User:
        external_id = external_id if external_id is not None else ""
        if info.context.employee is None:
            raise Exception("Employee is None")
        user = UnvalidatedUser(
            name=name,
            external_id=external_id,
            company_id=info.context.employee.company_id,
            created_by_id=info.context.employee.id,
        )
        return database.as_employee(info.context.employee).save_user(user)  # type: ignore
    
    @strawberry.mutation(permission_classes=[IsAuthenticated])
    async def transcribe_file(
        self,
        info: strawberry.Info,
        file_id: str,
    ) -> bool:
        file_metadata = database.as_employee(info.context.employee).get_file_metadata(file_id)
        if file_metadata is None:
            raise Exception("File metadata is None")
        transcribe_and_save_file = modal.Function.lookup("process-video", "run_remote_transcribe_and_save_file")  # type: ignore
        result = transcribe_and_save_file.remote(  # type: ignore    
            file_metadata_to_save=file_metadata,
            employee=info.context.employee,
            jwt=info.context.jwt,
        )
        assert result is not None
        return True

    @strawberry.mutation(permission_classes=[IsAuthenticated])
    async def save_files(
        self,
        info: strawberry.Info,
        user_id: UUID,
        file_metadata: List[FileMetadataInput],
    ) -> List[FileMetadata]:
        r2 = R2StorageClient(
            api_url=API_URL,
            base_path=info.context.employee.company_id,
            jwt=info.context.jwt,
        )
        user = database.as_employee(info.context.employee).get_user(user_id)
        if user is None:
            raise Exception("User not found")
        metadata: List[FileMetadata] = []
        for file in file_metadata:
            try:
                if file.file_name is None:
                    raise Exception("File name is None")
                # Generate a unique file key
                unique_file_key = await r2.get_unique_file_key(
                    file.file_name, str(user.id)
                )
                unvalidated_metadata = UnvalidatedFileMetadata(
                    user_id=user.id,
                    file_name=file.file_name,
                    file_path=unique_file_key,
                    file_type=DbFileType[file.file_type.value],
                    created_by_id=info.context.employee.id,
                    company_id=info.context.employee.company_id,
                    resolution_x=file.resolution_x,
                    resolution_y=file.resolution_y,
                    frame_rate=file.frame_rate,
                )
                file_metadata_to_save = database.as_employee(
                    info.context.employee
                ).save_file_metadata(unvalidated_metadata)
                metadata.append(file_metadata_to_save)  # type: ignore
            except Exception as e:
                print(e)
                raise Exception(f"Failed to upload file {file}")
        return metadata

    @strawberry.mutation(permission_classes=[IsAuthenticated])
    async def create_video_from_utterances(
        self,
        info: strawberry.Info,
        utterance_segments: Sequence[UtteranceSegmentInput],
        title: str,
    ) -> Video:
        """TODO
        Refactor to be an initializer and then you query a different endpoint to get the video.
        Use render status appropriately.
        Mirror the v2 file upload design for this endpoint.
        1. [DONE] create_video_from_utterances is an initializer, send id and respond with a video created
        - in background, kick off serverless video creation on modal.com. Use python storage_client to get the files there, not here.
        - modal will talk directly to the database and update the video with the status as it goes.
        2. get_video, responds with video and status, along with a signed url to download the video if it's ready.
        - signed url is for the r2 api, not the graphql server, so the client can download the video directly.
        3. Add more granularity to the video and file status - upload created, upload completed, transcription in progress, etc.
        """
        vite_api_url = os.environ.get("VITE_API_URL")
        if vite_api_url:
            remote_url = "process-video-dev" if vite_api_url.startswith("http://127.0.0.1") else "process-video"
        else:
            remote_url = "process-video"
        make_video = modal.Function.lookup(remote_url, "run_remote_create_video")  # type: ignore
        size = (1920/4, 1080/4)
        make_video_status = make_video.spawn(  # type: ignore
            utterance_segments_inputs=utterance_segments,
            employee_id=info.context.employee.id,
            jwt=info.context.jwt,
            title=title,
            size=size,
            force_size=True,
        )
        if make_video_status is None:
            raise Exception("Make video status is None")
        return Video(
            id=str(make_video_status),
            title=title,
            render_status="pending",
            clips=[],
            file_path="",
        )  # type: ignore

# %% ../nbs/09_graphql.ipynb 16
async def get_context() -> Context:
    return Context()


schema = strawberry.Schema(
    Query,
    Mutation,
    scalar_overrides={UploadFile: Upload},
    extensions=[
        AddValidationRules([NoSchemaIntrospectionCustomRule]),
    ],
)

graphql_app = GraphQLRouter(
    schema,
    context_getter=get_context,
    graphql_ide=None,
)

app = FastAPI()
origins = ["*"]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(graphql_app, prefix="/graphql")
