# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_graphql.ipynb.

# %% auto 0
__all__ = ['secret', 'database_url', 'database', 'database_superuser', 'T', 'PermissionsLevel', 'RegisterResponse',
           'LoginResponse', 'schema', 'graphql_app', 'app', 'JwtPayload', 'create_jwt', 'decode_jwt', 'Context',
           'IsAuthenticated', 'FormError', 'FormErrors', 'handle_form_validation_errors', 'Employee', 'User', 'Word',
           'UtteranceSegment', 'Utterance', 'Clip', 'Video', 'Company', 'FileMetadata', 'RegisterCompanySuccess',
           'LoginSuccess', 'Query', 'Mutation', 'get_context']

# %% ../nbs/09_graphql.ipynb 3
from typing import (
    Annotated,
    Any,
    Union,
    cast,
    Sequence,
    Callable,
    TypeVar,
    TypedDict,
    List,
    Optional,
)
from functools import wraps

from uuid import UUID
import strawberry
import jwt
from jwt.exceptions import InvalidTokenError
from fastapi import FastAPI
from .filesystems import R2StorageClient, FilePathType
from product_horse.db import (
    SqlModelDatabase,
    Employee,
    PermissionLevel as DbPermissionLevel,
    Company,
    UnvalidatedCompany,
    CreateEmployee,
    User as DbUser,
    Video,
    Utterance,
    UtteranceSegment,
    UnvalidatedUser,
    Word,
    Clip,
    FileMetadata,
    UnvalidatedFileMetadata,
)
from datetime import datetime, timedelta

from pydantic import ValidationError


from strawberry.permission import BasePermission
from strawberry.file_uploads import Upload
from strawberry.fastapi import BaseContext, GraphQLRouter
from starlette.datastructures import UploadFile

from dotenv import load_dotenv
import os

load_dotenv()

# %% ../nbs/09_graphql.ipynb 4
secret = os.getenv("SECRET")

# %% ../nbs/09_graphql.ipynb 5
database_url = os.getenv("DATABASE_URL")
if database_url is None:
    raise ValueError("DATABASE_URL is not set")
if secret is None:
    raise ValueError("SECRET is not set")
database = SqlModelDatabase(
    database_url="postgresql://rls_user:secure_password@localhost:5432/product_horse"
)
database_superuser = SqlModelDatabase(
    database_url="postgresql://localhost:5432/product_horse"
)


class JwtPayload(TypedDict):
    id: UUID
    company_id: UUID
    exp: float
    permission_level: DbPermissionLevel


def create_jwt(
    employee_id: UUID, company_id: UUID, permission_level: DbPermissionLevel
) -> str:
    expiration = datetime.utcnow() + timedelta(weeks=2)
    payload = {
        "id": str(employee_id),
        "company_id": str(company_id),
        "exp": expiration,
        "permission_level": permission_level.value,
    }
    return jwt.encode(payload, secret, algorithm="HS256")  # type: ignore


def decode_jwt(token: str) -> JwtPayload:
    payload = cast(JwtPayload, jwt.decode(token, secret, algorithms=["HS256"]))  # type: ignore
    if "id" not in payload:
        raise InvalidTokenError
    if "company_id" not in payload:
        raise InvalidTokenError
    if datetime.fromtimestamp(payload["exp"]) < datetime.utcnow():
        raise InvalidTokenError
    return payload


class Context(BaseContext):
    @property
    def employee(self):
        request = self.request
        if request is None:
            print("Request is None")
            return None
        authorization = request.headers.get("Authorization")
        if authorization is None:
            return None
        if not authorization.startswith("Bearer "):
            return None
        token = authorization.split()[1]
        payload = decode_jwt(token)
        employee_id = payload["id"]
        # run on superuser connection, since it's behind jwt auth
        employee = database_superuser.get_employee(employee_id=employee_id)
        return employee

    @property
    def jwt(self):
        request = self.request
        if request is None:
            return None
        authorization = request.headers.get("Authorization")
        if authorization is None:
            return None
        if not authorization.startswith("Bearer "):
            return None
        token = authorization.split()[1]
        return token


class IsAuthenticated(BasePermission):
    message = "Employee is not authenticated"
    error_extensions = {"code": "UNAUTHORIZED"}

    def has_permission(self, source: Any, info: strawberry.Info, **kwargs: Any) -> bool:
        employee = info.context.employee
        return employee is not None


T = TypeVar("T")


@strawberry.type
class FormError:
    field: str
    message: str


@strawberry.type
class FormErrors:
    errors: list[FormError]


def handle_form_validation_errors(
    func: Callable[..., T],
) -> Callable[..., Union[T, FormErrors]]:
    @wraps(func)
    def wrapper(*args: Any, **kwargs: Any) -> Union[T, FormErrors]:
        try:
            return func(*args, **kwargs)
        except ValidationError as e:
            errors = [
                FormError(field=cast(str, error["loc"][-1]), message=error["msg"])
                for error in e.errors()
            ]
            return FormErrors(errors=errors)

    return wrapper

# %% ../nbs/09_graphql.ipynb 7
PermissionsLevel = strawberry.enum(DbPermissionLevel)


@strawberry.experimental.pydantic.type(Employee)
class Employee:
    id: UUID
    email: str
    name: str
    permission_level: PermissionsLevel


@strawberry.experimental.pydantic.type(DbUser)
class User:
    id: UUID
    name: str


@strawberry.experimental.pydantic.type(Word)
class Word:
    id: UUID
    text: str
    start_time: float
    end_time: float


@strawberry.experimental.pydantic.type(UtteranceSegment)
class UtteranceSegment:
    id: UUID
    start_word: Word
    end_word: Word
    text: str
    words: list[Word]


@strawberry.experimental.pydantic.type(Utterance)
class Utterance:
    id: UUID
    confidence: float
    start_time: float
    end_time: float
    speaker: str
    text: str
    words: list[Word]


@strawberry.experimental.pydantic.type(Clip)
class Clip:
    id: UUID
    name: str
    words: list[Word]


@strawberry.experimental.pydantic.type(Video)
class Video:
    id: UUID
    name: str
    clips: list[Clip]


@strawberry.experimental.pydantic.type(Company)
class Company:
    id: UUID
    name: str
    employees: list[Employee]


@strawberry.experimental.pydantic.type(FileMetadata)
class FileMetadata:
    id: UUID
    name: str
    file_path: str

@strawberry.type
class RegisterCompanySuccess:
    company: Company
    token: str


# Create a Union type to represent the 2 results from the mutation
RegisterResponse = Annotated[
    Union[RegisterCompanySuccess, FormErrors],
    strawberry.union("RegisterCompanyResponse"),
]


@strawberry.type
class LoginSuccess:
    employee: Employee
    token: str


LoginResponse = Annotated[
    Union[LoginSuccess, FormErrors],
    strawberry.union("LoginResponse"),
]


@strawberry.type
class Query:
    employee: Employee

    @strawberry.field(permission_classes=[IsAuthenticated])
    def get_users(self, info: strawberry.Info) -> Sequence[User]:
        return database.as_employee(info.context.employee).get_all_users()  # type: ignore

    # @strawberry.field(permission_classes=[IsAuthenticated])
    # async def get_relevant_utterances(
    #     self, info: strawberry.Info, query: str, transcript_ids: Sequence[str]
    # ) -> Sequence[Utterance]:
    #     transcript_uuids = [UUID(transcript_id) for transcript_id in transcript_ids]
    #     transcripts = database.as_employee(info.context.employee).get_transcriptions(transcription_ids=transcript_uuids)
    #     utterances = await get_relevant_utterances_from_query(
    #         db=database,
    #         employee=info.context.employee,
    #         query=query,
    #         transcripts=transcripts,
    #     )
    #     return utterances # type: ignore

    # @strawberry.field(permission_classes=[IsAuthenticated])
    # def get_video(self, info: strawberry.Info, video_id: str) -> Video:
    #     raise NotImplementedError

    # @strawberry.field(permission_classes=[IsAuthenticated])
    # def get_videos(self, info: strawberry.Info) -> Sequence[Video]:
    #     raise NotImplementedError


@strawberry.type
class Mutation:
    @strawberry.mutation
    def login(self, email: str, password: str) -> LoginResponse:
        employee = database_superuser.authenticate_employee(email, password)
        if employee is None:
            raise Exception("Invalid email or password")
        return LoginSuccess(
            employee=employee,  # type: ignore
            token=create_jwt(
                employee.id, employee.company_id, employee.permission_level
            ),
        )

    @strawberry.mutation
    @handle_form_validation_errors
    def register_company_and_employee(
        self, name: str, email: str, password: str, company_name: str
    ) -> RegisterResponse:
        company_to_save = UnvalidatedCompany(name=company_name)
        employee_to_save = CreateEmployee(
            name=name,
            email=email,
            password=password,
            permission_level=DbPermissionLevel.ADMIN,
        )
        company, employee = database_superuser.save_company_and_employee(
            company_to_save, employee_to_save
        )
        return RegisterCompanySuccess(
            company=company,  # type: ignore
            token=create_jwt(employee.id, company.id, employee.permission_level),
        )

    @strawberry.mutation(permission_classes=[IsAuthenticated])
    def save_user(self, info: strawberry.Info, name: str, external_id: Optional[str] = None) -> User:
        external_id = external_id if external_id is not None else ""
        user = UnvalidatedUser(
            name=name,
            external_id=external_id,
            company_id=info.context.employee.company_id,
            created_by_id=info.context.employee.id,
        )
        return database.as_employee(info.context.employee).save_user(user)  # type: ignore

    @strawberry.mutation
    async def save_files_and_transcriptions(
        self,
        info: strawberry.Info,
        user_id: UUID,
        files: Sequence[Upload],
    ) -> List[FileMetadata]:
        r2 = R2StorageClient(
            # api_url="http://localhost:8787",
            api_url="https://storage.producthorse.workers.dev/",
            base_path=info.context.employee.company_id,
            jwt=info.context.jwt,
        )
        user = database.as_employee(info.context.employee).get_user(user_id)
        if user is None:
            raise Exception("User not found")
        path = r2.build_user_path(user, FilePathType.USER_ID_BASE_TEXT)
        metadata: List[FileMetadata] = []
        for file in files:
            try:
                file = cast(UploadFile, file)
                name = file.filename
                content_type = (
                    file.content_type if file.content_type is not None else "text/plain"
                )
                if name is None:
                    raise Exception("File name is None")
                contents = await file.read()
                file = await r2.create_file(
                    path, contents, name, authorized=True, mime_type=content_type
                )
                unvalidated_metadata = UnvalidatedFileMetadata(
                    user_id=user.id,
                    file_name=name,
                    file_path=file.uri,
                    created_by_id=info.context.employee.id,
                    company_id=info.context.employee.company_id,
                )
                metadata.append(
                    database.as_employee(info.context.employee).save_file_metadata(
                        unvalidated_metadata
                    )
                )
            except Exception as e:
                print(e)
                raise Exception(f"Failed to upload file {file}")
        return metadata

    # @strawberry.mutation
    # def create_video_from_utterances(
    #     self, utterance_segments: Sequence[UtteranceSegment], user_id: UUID
    # ) -> str:
    #     raise NotImplementedError

# %% ../nbs/09_graphql.ipynb 8
async def get_context() -> Context:
    return Context()


schema = strawberry.Schema(Query, Mutation, scalar_overrides={UploadFile: Upload})

graphql_app = GraphQLRouter(
    schema,
    context_getter=get_context,
)

app = FastAPI()
app.include_router(graphql_app, prefix="/graphql")
