# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_load.ipynb.

# %% auto 0
__all__ = ['AbstractDataLoader']

# %% ../nbs/06_load.ipynb 3
from dataclasses import dataclass
from typing import Any, List

# %% ../nbs/06_load.ipynb 4
@dataclass
class AbstractDataLoader:
    """Abstract class for data loaders that bring data into the user's search index.
    Data will be loaded into a unified schema that can be used to search for clips and sources"""
    schema: Any

    def load(self, uri: str) -> Any:
        raise NotImplementedError

