# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_run_modal.ipynb.

# %% auto 0
__all__ = ['app', 'image', 'run_remote_create_video']

# %% ../nbs/06_run_modal.ipynb 4
import modal
from .audio_video import create_video_from_utterances
from .db import SqlModelDatabase, UtteranceSegment
from .filesystems import LocalFileSystem, R2StorageClient
from .graphql import UtteranceSegmentInput
from uuid import UUID
from random import randint
import uuid
import os
from typing import Tuple


# %% ../nbs/06_run_modal.ipynb 5
app = modal.App("process-video")

image = (
    modal.Image.debian_slim()
    .apt_install(["ffmpeg", "pkg-config", "libcairo2-dev", "imagemagick", "ghostscript", "fonts-freefont-otf"])
    .pip_install_from_requirements("requirements.lock")
    .run_commands(
        """sed -i 's/rights="none" pattern="@\\*"/rights="read|write" pattern="@*"/' /etc/ImageMagick-6/policy.xml"""
    )
)

@app.function(timeout=1200, secrets=[modal.Secret.from_name("video_secrets")], image=image)
async def run_remote_create_video(
    utterance_segments_inputs: list[UtteranceSegmentInput],
    employee_id: UUID,
    jwt: str,
    title: str,
    size: Tuple[int, int] = (1920, 1080),
    force_size: bool = True,
):
    """
    TO-DOs:
    - recover if file fails to download
    - update video status more immediately and frequently
    - set video failed status if that happens
    """
    db_url = os.getenv("DATABASE_URL")
    db_superuser_url = os.getenv("DATABASE_SUPERUSER_URL")
    if db_superuser_url is None:
        raise Exception("DATABASE_SUPERUSER_URL is not set")
    API_URL = os.getenv("API_URL")
    if db_url is None or API_URL is None:
        raise Exception(
            f"Not Set: {'DATABASE_URL' if db_url is None else ''} {'API_URL' if API_URL is None else ''}"
        )
    database_superuser = SqlModelDatabase(database_url=db_superuser_url)
    database = SqlModelDatabase(database_url=db_url)
    # run on superuser connection, since it's behind jwt auth
    employee = database_superuser.get_employee(employee_id=employee_id)
    if employee is None:
        raise Exception("Employee not found")
    # DEFINE FILE SYSTEMS
    r2 = R2StorageClient(
        api_url=API_URL,
        base_path=str(employee.company_id),
        jwt=jwt,
    )
    server_file_system = LocalFileSystem()
    # rest of program
    utterance_ids = [
        UUID(segment.utterance_id) for segment in utterance_segments_inputs
    ]
    word_ids = [
        word_id
        for segment in utterance_segments_inputs
        for word_id in segment.word_ids
    ]
    utterances = database.as_employee(employee).get_utterances(
        utterance_ids, word_ids=word_ids
    )
    video_exists = database.as_employee(employee).get_all_videos()
    for video in video_exists:
        if video.title == title:  # type: ignore
            title = f"{title}-{randint(1, 200)}"
    utterance_segments_for_video: list[UtteranceSegment] = []
    for utterance in utterances:
        utterance_segments_for_video.append(
            UtteranceSegment(
                id=utterance.id,
                transcription_id=utterance.transcription_id,
                transcription=utterance.transcription,
                words=utterance.words,
                segment_start_word=utterance.words[0],  # type: ignore
                segment_end_word=utterance.words[-1],  # type: ignore
                confidence=utterance.confidence,
                company_id=utterance.company_id,
                created_by_id=utterance.created_by_id,
                start=utterance.start,
                end=utterance.end,
            )
        )
    user = database.as_employee(employee).get_all_users()[0]
    if user is None:
        raise Exception("User not found")
    final_destination = await r2.get_unique_file_key(f"{title}.mp4", str(user.id))
    video = await create_video_from_utterances(
        database,
        remote_file_system=r2,
        local_file_system=server_file_system,
        employee=employee,
        user=user,
        utterance_segments=utterance_segments_for_video,
        final_destination=final_destination,
        title=title,
        size=size,
        force_size=force_size,
    )
    return video

