# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_run_modal.ipynb.

# %% auto 0
__all__ = ['app', 'list_files']

# %% ../nbs/06_run_modal.ipynb 4
import modal
import subprocess
from .audio_video import create_video_from_utterances

# %% ../nbs/06_run_modal.ipynb 5
app = modal.App('process-video')


@app.function( # type: ignore
    volumes={
        "/ph-storage": modal.CloudBucketMount(
            bucket_name="ph-storage",
            bucket_endpoint_url="https://db59eb944db359472048f5e9a5dbc7d7.r2.cloudflarestorage.com",
            secret=modal.Secret.from_name("R2_KEY"),
            read_only=True
        )
    }
)
def list_files():
    print("Listing files in /ph-storage")
    result = subprocess.run(["ls", "-la", "/ph-storage"], capture_output=True, text=True)
    return result.stdout

