# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_search.ipynb.

# %% auto 0
__all__ = ['get_nodes_from_transcripts', 'embed_and_augment_nodes', 'TranscriptRetriever', 'TranscriptIndex', 'create_client',
           'get_utterances_from_query']

# %% ../nbs/05_search.ipynb 3
from typing import Any, List, Sequence, Set, Optional, Dict, Coroutine
from .db import SqlModelDatabase, Utterance
from pprint import pprint
import uuid
from llama_index.embeddings.openai import OpenAIEmbedding
import chromadb
from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.core.schema import (
    TextNode,
    NodeRelationship,
    RelatedNodeInfo,
    BaseNode,
)
from .db import Transcription
from .extraction import AIModelClient, Questions, ModelType
from llama_index.core.vector_stores.types import VectorStoreQueryResult
import numpy as np
from llama_index.core.ingestion import IngestionPipeline
from llama_index.core.indices.base import BaseIndex
from llama_index.core.data_structs import IndexDict
from llama_index.core.schema import QueryBundle, NodeWithScore
from llama_index.core.storage.docstore.types import RefDocInfo
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.vector_stores.types import (
    VectorStore,
    VectorStoreQuery,
    MetadataFilter,
    MetadataFilters,
)
from llama_index.core.storage.storage_context import StorageContext

# %% ../nbs/05_search.ipynb 9
async def get_nodes_from_transcripts(transcripts: Sequence[Transcription]) -> List[TextNode]:
    """Get nodes from transcripts.
    Each node represents a single utterance in the transcript.
    Uses AI to detect the speaker role.
    The node's metadata contains the speaker, start_seconds, end_seconds, and confidence."""
    parent_nodes: List[TextNode] = []
    child_nodes: List[TextNode] = []
    # embed_model = OpenAIEmbedding()
    ai_client = AIModelClient(model_type=ModelType.GPT_3_5_TURBO)
    role_extract_schema = Questions(questions=[
            {
                "categories": ["A", "B"],
                "id": "1",
                "output_type": "category",
                "text": "Identify which of the speakers is the researcher in this transcript, returning whichever speaker they are in a two-person conversation — A or B.",
            }
        ]
    )
    for transcript in transcripts:
        # parent_node = TextNode(
        #     id_=str(transcript.id),
        #     text=transcript.text,
        #     # embedding=embed_model.get_query_embedding(transcript.text),
        # )
        # parent_nodes.append(parent_node)
        # nodes_for_parent: List[TextNode] = []
        next_node_id = None
        next_transcript_id = None
        interviewer_answers = await ai_client.extract_information(transcript.text, role_extract_schema)
        interviewer = interviewer_answers.answers[0].categories[0]

        for utterance in reversed(transcript.utterances):
            role = 'interviewee' if interviewer != utterance.speaker else 'interviewer'
            child_node = TextNode(
                text=utterance.text,
                id_=str(utterance.id),
                # embedding=embed_model.get_query_embedding(utterance.text),
                # ref_doc_id=str(transcript.id),
                metadata={
                    "transcript_id": str(transcript.id),
                    "speaker": role,
                    "start_seconds": utterance.start,
                    "end_seconds": utterance.end,
                    "confidence": utterance.confidence,
                },
            )

            if next_node_id is not None and next_transcript_id == transcript.id:
                child_node.relationships[NodeRelationship.NEXT] = RelatedNodeInfo(
                    node_id=next_node_id
                )
            else:
                if next_node_id is not None:
                    child_node.relationships[NodeRelationship.NEXT] = RelatedNodeInfo(
                        node_id=next_node_id
                    )
            next_node_id = child_node.id_
            next_transcript_id = transcript.id
            child_nodes.append(child_node)

        # After processing all utterances, attach the nodes to the main transcript node
        # parent_node.relationships = {
        #     NodeRelationship.PARENT: [
        #         RelatedNodeInfo(node_id=node.id_, metadata=node.metadata)
        #         for node in nodes_for_parent
        #     ]}
    reversed_child_nodes = list(reversed(child_nodes))
    for i, node in enumerate(reversed_child_nodes):
        if i > 0:
            if NodeRelationship.NEXT in reversed_child_nodes[i - 1].relationships:
                node.relationships[NodeRelationship.PREVIOUS] = RelatedNodeInfo(
                    node_id=reversed_child_nodes[i - 1].id_
                )
    all_nodes = [*reversed_child_nodes]
    return all_nodes

# %% ../nbs/05_search.ipynb 13
def embed_and_augment_nodes(
    nodes: List[TextNode],
) -> Coroutine[Any, Any, Sequence[BaseNode]]:
    """Augments and embeds nodes. Returns a couroutine for async work in the main thread."""
    transformations = [
        # TitleExtractor(nodes=5, llm=llm),
        # QuestionsAnsweredExtractor(questions=3, llm=llm),
        OpenAIEmbedding()
    ]

    pipeline = IngestionPipeline(
        transformations=transformations,
    )
    return pipeline.arun(nodes=nodes, in_place=False)

# %% ../nbs/05_search.ipynb 26
class TranscriptRetriever(BaseRetriever):
    """Returned by TranscriptIndex.as_retriever(), and pass into RetrieverQueryEngine.
    Then use RetrieverQueryEngine.retrieve
    Retrieval logic:
    1. Find the most relevant utterance in the transcript
    2. Expand to the adjacent utterances to get nodes that contain the most relevant information until they stop being similar to the original.
    3. Merge any overlapping nodes
    5. Rerank then return to user"""

    def __init__(self, vector_store: VectorStore, **kwargs: Any):
        self.vector_store = vector_store
        super().__init__(**kwargs)

    def _check_query_result(
        self,
        result: VectorStoreQueryResult,
        node_to_check_against: Optional[NodeWithScore] = None,
    ) -> List[NodeWithScore]:
        if result.nodes is None or result.similarities is None:
            return []

        # Sort nodes by 'start_seconds' metadata
        sorted_nodes_with_scores: List[NodeWithScore] = sorted(
            [
                NodeWithScore(node=node, score=similarity)
                for node, similarity in zip(result.nodes, result.similarities)
            ],
            key=lambda node: node.node.metadata["start_seconds"],
        )

        if node_to_check_against:
            # Find the index of the node to check against
            try:
                start_index = next(
                    i
                    for i, node_with_score in enumerate(sorted_nodes_with_scores)
                    if node_with_score.node.id_ == node_to_check_against.node.id_
                )
            except StopIteration:
                return []

            # Apply exponential to similarities to expand the range
            similarities = np.exp(
                np.array(
                    [
                        node_with_score.score
                        for node_with_score in sorted_nodes_with_scores
                    ]
                )
            )

            # Smooth the similarities using a simple moving average
            window_size = 3
            smoothed_similarities = np.convolve(
                similarities, np.ones(window_size) / window_size, mode="same"
            )

            # Compute differences and find inflection points
            differences = np.diff(smoothed_similarities)
            second_differences = np.diff(differences)
            inflection_points = np.where(
                np.abs(second_differences) > np.std(second_differences)
            )[0]  # Using standard deviation as a threshold

            # Determine bounds for inclusion based on inflection points
            lower_bound = max(
                0,
                inflection_points[inflection_points < start_index].max() + 1
                if any(inflection_points < start_index)
                else 0,
            )
            upper_bound = min(
                len(sorted_nodes_with_scores) - 1,
                inflection_points[inflection_points > start_index].min() + 1
                if any(inflection_points > start_index)
                else len(sorted_nodes_with_scores) - 1,
            )

            # Include nodes from lower to upper bound
            nodes_list = sorted_nodes_with_scores[lower_bound : upper_bound + 1]
        else:
            # If no specific node to check against, include all nodes
            nodes_list = sorted_nodes_with_scores
        return nodes_list

    def _get_all_transcript_nodes(
        self, node_with_score: NodeWithScore
    ) -> List[NodeWithScore]:
        """Retrieve all nodes in a transcript if they have the same transcript_id and the node has a relationship"""
        adjacent_nodes: List[NodeWithScore] = []
        current_node = node_with_score.node
        if len(current_node.relationships) > 0:
            query_str = current_node.get_content()
            query_embedding = self.embed_model.get_query_embedding(query_str)
            query_bundle = VectorStoreQuery(
                query_str=query_str,
                query_embedding=query_embedding,
                filters=MetadataFilters(
                    filters=[
                        MetadataFilter(
                            key="transcript_id",
                            value=current_node.metadata["transcript_id"],
                        )
                    ]
                ),
                similarity_top_k=50,
            )
            result = self.vector_store.query(query_bundle)
            adjacent_node_list = self._check_query_result(
                result, node_to_check_against=node_with_score
            )
            if not adjacent_node_list:
                return adjacent_nodes  # []
            adjacent_nodes.extend(adjacent_node_list)
            return adjacent_nodes  # happy path
        else:
            return adjacent_nodes  # []

    def _retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        """Retrieve nodes given query."""
        self.embed_model = OpenAIEmbedding()
        query_embedding = self.embed_model.get_query_embedding(query_bundle.query_str)
        query_bundle.embedding = query_embedding
        vector_store_query = VectorStoreQuery(
            query_str=query_bundle.query_str,
            query_embedding=query_bundle.embedding,
            similarity_top_k=20,
        )
        result = self.vector_store.query(vector_store_query)
        nodes_list = self._check_query_result(result)

        all_relevant_nodes: List[NodeWithScore] = []
        seen_node_ids: Set[str] = set()
        for node_with_score in nodes_list:
            all_nodes_in_transcript = self._get_all_transcript_nodes(node_with_score)
            for node in all_nodes_in_transcript:
                if node.node.id_ not in seen_node_ids:
                    seen_node_ids.add(node.node.id_)
                    all_relevant_nodes.append(node)

        all_relevant_nodes.sort(
            key=lambda x: (
                x.node.metadata["transcript_id"],
                x.node.metadata["start_seconds"],
            )
        )
        return all_relevant_nodes

    async def _aretrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        """Asynchronously retrieve nodes given query.

        Implemented by the user.

        """
        return self._retrieve(query_bundle)

    ####################################
    ### Image Retrieval: Not implementing
    ####################################

    async def _aimage_to_image_retrieve(
        self,
        query_bundle: QueryBundle,
    ) -> List[NodeWithScore]:
        """Async retrieve image nodes or documents given image.

        Implemented by the user.

        """
        raise NotImplementedError("Images type not supported in transcripts")

    async def _atext_to_image_retrieve(
        self,
        query_bundle: QueryBundle,
    ) -> List[NodeWithScore]:
        """Async retrieve image nodes or documents given query text.

        Implemented by the user.

        """
        raise NotImplementedError("Images type not supported in transcripts")

    def _image_to_image_retrieve(
        self,
        query_bundle: QueryBundle,
    ) -> List[NodeWithScore]:
        """Retrieve image nodes or documents given image.

        Implemented by the user.

        """
        raise NotImplementedError("Images type not supported in transcripts")

    def _text_to_image_retrieve(
        self,
        query_bundle: QueryBundle,
    ) -> List[NodeWithScore]:
        """Retrieve image nodes or documents given query text.

        Implemented by the user.

        """
        raise NotImplementedError("Images type not supported in transcripts")


class TranscriptIndex(BaseIndex[IndexDict]):
    """For now this class is mainly going to be used as a pass-through.
    The indexing is done in a helper function and passed into a vector store first.
    API should look like:
    index = TranscriptIndex.from_vector_store(vector_store)
    query_engine = index.as_query_engine()
    Which returns RetrieverQueryEngine
    """

    def __init__(self, nodes: Sequence[BaseNode], **kwargs: Any):
        super().__init__(nodes, **kwargs)
        self._callback_manager = CallbackManager()

    @classmethod
    def from_vector_store(
        cls,
        vector_store: VectorStore,
        **kwargs: Any,
    ) -> "TranscriptIndex":
        """
        Initialize a TranscriptIndex object from a VectorStore.

        Args:
            vector_store (VectorStore): A VectorStore object.
            **kwargs: Additional keyword arguments.

        Returns:
            TranscriptIndex: A TranscriptIndex object.
        """
        if not vector_store.stores_text:
            raise ValueError(
                "Cannot initialize from a vector store that does not store text."
            )

        kwargs.pop("storage_context", None)
        storage_context = StorageContext.from_defaults(vector_store=vector_store)

        return cls(
            nodes=[],
            storage_context=storage_context,
            **kwargs,
        )

    def _build_index_from_nodes(self, nodes: Sequence[BaseNode]) -> IndexDict:
        """Build the index from nodes."""
        index_dict = IndexDict()
        for node in nodes:
            index_dict.add_node(node)
        return index_dict

    def _insert(self, nodes: Sequence[BaseNode], **insert_kwargs: Any) -> None:
        """Index-specific logic for inserting nodes to the index struct."""
        raise NotImplementedError("Not implemented")

    def _delete_node(self, node_id: str, **delete_kwargs: Any) -> None:
        """Delete a node."""
        raise NotImplementedError("Not implemented")

    @property
    def ref_doc_info(self) -> Dict[str, RefDocInfo]:
        """Retrieve a dict mapping of ingested documents and their nodes+metadata.
        Original implementation borrowed from VectorStoreIndex"""
        if not self._vector_store.stores_text:
            node_doc_ids = list(self.index_struct.nodes_dict.values())
            nodes = self.docstore.get_nodes(node_doc_ids)

            all_ref_doc_info = {}
            for node in nodes:
                ref_node = node.source_node
                if not ref_node:
                    continue

                ref_doc_info = self.docstore.get_ref_doc_info(ref_node.node_id)
                if not ref_doc_info:
                    continue

                all_ref_doc_info: Dict[str, RefDocInfo] = {}
                all_ref_doc_info[ref_node.node_id] = ref_doc_info
            return all_ref_doc_info
        else:
            raise NotImplementedError(
                "Vector store integrations that store text in the vector store are "
                "not supported by ref_doc_info yet."
            )

    def as_retriever(self, **kwargs: Any) -> BaseRetriever:
        return TranscriptRetriever(
            callback_manager=self._callback_manager,
            # node_ids=self.index_struct.nodes_dict.keys(),
            vector_store=self.storage_context.vector_store,
            object_map=self._object_map,
            **kwargs,
        )

# %% ../nbs/05_search.ipynb 28
def create_client() -> ChromaVectorStore:
    chroma_client = chromadb.EphemeralClient()
    random_string = str(uuid.uuid4())
    chroma_collection = chroma_client.create_collection(random_string)
    vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
    return vector_store


def get_utterances_from_query(query: str, nodes: Sequence[BaseNode]) -> List[Utterance]:
    "Returns time-sorted utterances from a query"
    vector_store = create_client()
    vector_store.add(nodes)
    index = TranscriptIndex.from_vector_store(vector_store)
    query_engine = index.as_retriever()
    query_str = "What do painters think of the AI designer?"
    result = query_engine.retrieve(query_str)
    utterances: List[Utterance] = []
    for node_with_score in result:
        node = node_with_score.node
        utterances.append(
            Utterance(
                id=node.id_,
                text=node.text,
                confidence=node.metadata["confidence"],
                start=int(node.metadata["start_seconds"]),
                end=int(node.metadata["end_seconds"]),
                speaker=node.metadata["speaker"],
                transcription_id=node.metadata["transcript_id"],
            )
        )
    return utterances
