# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_search.ipynb.

# %% auto 0
__all__ = ['get_nodes_from_transcripts', 'embed_and_augment_nodes', 'get_node', 'ExtendedQueryBundle', 'TranscriptRetriever',
           'TranscriptIndex', 'setup_vector_db', 'SearchEngine']

# %% ../nbs/05_search.ipynb 4
from typing import Any, List, Sequence, Set, Optional, Dict, Coroutine, Tuple
from product_horse.db import (
    SqlModelDatabase,
    Utterance,
    AbstractDatabase,
    DBType,
    Employee,
    create_default_company_and_employee
)
import os
import psycopg2
import subprocess
import tempfile
from pprint import pprint
from sqlalchemy import make_url
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.vector_stores.postgres import PGVectorStore
from llama_index.core.schema import (
    TextNode,
    NodeRelationship,
    RelatedNodeInfo,
    BaseNode,
)
from .db import Transcription
from .extraction import AIModelClient, Questions, ModelType
from llama_index.core.ingestion import IngestionPipeline
from llama_index.core.indices.base import BaseIndex
from llama_index.core.data_structs import IndexDict
from llama_index.core.schema import QueryBundle, NodeWithScore
from llama_index.core.storage.docstore.types import RefDocInfo
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.vector_stores.types import (
    VectorStoreQueryResult,
    VectorStore,
    VectorStoreQuery,
    MetadataFilter,
    MetadataFilters,
    FilterCondition,
)
from llama_index.core.storage.storage_context import StorageContext
from dotenv import load_dotenv

if not os.getenv("DATABASE_URL"):
    load_dotenv(dotenv_path="../.env.local")

# %% ../nbs/05_search.ipynb 6
async def get_nodes_from_transcripts(
    transcripts: Sequence[Transcription],
) -> List[TextNode]:
    import asyncio

    """Get nodes from transcripts.
    Each node represents a single utterance in the transcript.
    Uses AI to detect the speaker role.
    The node's metadata contains the speaker, start_seconds, end_seconds, and confidence."""
    child_nodes: List[TextNode] = []
    # embed_model = OpenAIEmbedding()
    ai_client = AIModelClient(model_type=ModelType.GPT_3_5_TURBO)
    role_extract_schema = Questions(
        questions=[
            {
                "categories": ["A", "B"],
                "id": "1",
                "output_type": "category",
                "text": "Identify which of the speakers is the researcher in this transcript, returning whichever speaker they are in a two-person conversation — A or B.",
            } # type: ignore
        ]
    )
    tasks = [
        ai_client.extract_information(transcript.text, role_extract_schema)
        for transcript in transcripts
    ]
    # Run all ai_client calls concurrently and wait for all to complete
    results = await asyncio.gather(*tasks)
    for transcript, result in zip(transcripts, results):
        next_transcript_id = None
        next_node_id = None
        interviewer = result.answers[0].categories[0]

        for utterance in reversed(transcript.utterances):
            role = "interviewee" if interviewer != utterance.speaker else "interviewer"
            child_node = TextNode(
                text=utterance.text,
                id_=str(utterance.id),
                # embedding=embed_model.get_query_embedding(utterance.text),
                # ref_doc_id=str(transcript.id),
                metadata={
                    "transcript_id": str(transcript.id),
                    "speaker": role,
                    "start_seconds": utterance.start,
                    "end_seconds": utterance.end,
                    "confidence": utterance.confidence,
                },
            )

            if next_node_id is not None and next_transcript_id == transcript.id:
                child_node.relationships[NodeRelationship.NEXT] = RelatedNodeInfo(
                    node_id=next_node_id
                )
            else:
                if next_node_id is not None:
                    child_node.relationships[NodeRelationship.NEXT] = RelatedNodeInfo(
                        node_id=next_node_id
                    )
            next_node_id = child_node.id_
            next_transcript_id = transcript.id
            child_nodes.append(child_node)

    reversed_child_nodes = list(reversed(child_nodes))
    for i, node in enumerate(reversed_child_nodes):
        if i > 0:
            if NodeRelationship.NEXT in reversed_child_nodes[i - 1].relationships:
                node.relationships[NodeRelationship.PREVIOUS] = RelatedNodeInfo(
                    node_id=reversed_child_nodes[i - 1].id_
                )
    all_nodes = [*reversed_child_nodes]
    return all_nodes

# %% ../nbs/05_search.ipynb 9
def embed_and_augment_nodes(
    nodes: List[TextNode],
) -> Coroutine[Any, Any, Sequence[BaseNode]]:
    """Augments and embeds nodes. Returns a couroutine for async work in the main thread."""
    transformations = [
        # TitleExtractor(nodes=5, llm=llm),
        # QuestionsAnsweredExtractor(questions=3, llm=llm),
        OpenAIEmbedding()
    ]

    pipeline = IngestionPipeline(
        transformations=transformations,
    )
    return pipeline.arun(nodes=nodes, in_place=False)

# %% ../nbs/05_search.ipynb 11
def get_node(vector_store: VectorStore, node_id: str):
    query = VectorStoreQuery(
        node_ids=[node_id]
    )
    result = vector_store.query(query)
    node = result.nodes[0] if result.nodes else None
    if not node:
        raise ValueError(f"Node {node_id} not found")
    return node

# %% ../nbs/05_search.ipynb 14
class ExtendedQueryBundle(QueryBundle):
    query_str: str
    transcription_ids: List[str]
    seconds_buffer: int
    similarity_top_k: int

    def __init__(
        self,
        query_str: str,
        transcription_ids: List[str],
        seconds_buffer: int = 10,
        similarity_top_k: int = 25,
    ):
        self.query_str = query_str
        self.transcription_ids = transcription_ids
        self.seconds_buffer = seconds_buffer
        self.similarity_top_k = similarity_top_k


class TranscriptRetriever(BaseRetriever):
    """Returned by TranscriptIndex.as_retriever(), and pass into RetrieverQueryEngine.
    Then use RetrieverQueryEngine.retrieve
    Retrieval logic:
    1. Find the most relevant utterance in the transcript
    2. Expand to the adjacent utterances to get nodes that contain the most relevant information until they stop being similar to the original.
    3. Merge any overlapping nodes
    5. Rerank then return to user"""

    def __init__(self, vector_store: VectorStore, **kwargs: Any):
        self.vector_store = vector_store
        super().__init__(**kwargs)

    def _check_query_result(
        self,
        result: VectorStoreQueryResult,
        node_to_check_against: Optional[NodeWithScore] = None,
    ) -> List[NodeWithScore]:
        """really just sorts by seconds right now, doesn't actually check similarily as it originally did."""
        if result.nodes is None:
            return []
        if result.similarities is None:
            # populate with 0s
            result.similarities = [0 for _ in result.nodes]

        sorted_nodes_with_scores: List[NodeWithScore] = sorted(
            [
                NodeWithScore(node=node, score=similarity)
                for node, similarity in zip(result.nodes, result.similarities)
            ],
            key=lambda node: node.node.metadata["start_seconds"],
        )
        if node_to_check_against:
            raise NotImplementedError("Not implemented yet")
        else:
            nodes_list = sorted_nodes_with_scores
        return nodes_list

    def _get_nodes_based_on_relationship(
        self, node: BaseNode, relationship: NodeRelationship
    ) -> Optional[TextNode]:
        related_node = node.relationships.get(relationship)
        if related_node:
            related_node_refreshed = get_node(self.vector_store, related_node.node_id)
            return related_node_refreshed
        return None

    def _get_adjacent_nodes(
        self, node: BaseNode, seconds_buffer: int = 10, max_nodes: int = 5
    ) -> List[BaseNode]:
        """Get adjacent nodes in the transcript within a specified time window."""
        adjacent_nodes: List[BaseNode] = [node]

        # Get the start and end times of the original node
        original_start_ms = node.metadata["start_seconds"]
        original_end_ms = node.metadata["end_seconds"]

        # Calculate the time window boundaries
        start_window_ms = original_start_ms - seconds_buffer * 1000
        end_window_ms = original_end_ms + seconds_buffer * 1000

        # Retrieve previous nodes within the time window
        prev_node = node
        while len(adjacent_nodes) < max_nodes:
            prev_node_id = prev_node.relationships.get(NodeRelationship.PREVIOUS)
            if not prev_node_id:
                break
            prev_node = self._get_nodes_based_on_relationship(
                node=prev_node, relationship=NodeRelationship.PREVIOUS
            )
            if not prev_node:
                break
            if prev_node.metadata["end_seconds"] < start_window_ms:
                break
            adjacent_nodes.insert(0, prev_node)

        # Retrieve next nodes within the time window
        next_node = node
        while len(adjacent_nodes) < max_nodes:
            next_node_id = next_node.relationships.get(NodeRelationship.NEXT)
            if not next_node_id:
                break
            next_node = self._get_nodes_based_on_relationship(
                node=next_node, relationship=NodeRelationship.NEXT
            )
            if not next_node:
                break
            if next_node.metadata["start_seconds"] > end_window_ms:
                break
            adjacent_nodes.append(next_node)

        return adjacent_nodes[:max_nodes]  # Ensure we don't exceed max_node

    def _get_all_transcript_nodes(
            self, node_with_score: NodeWithScore, seconds_buffer: int = 3, max_nodes: int = 5
        ) -> List[NodeWithScore]:
        """Retrieve all nodes in a transcript if they have the same transcript_id and the node has a relationship, up to a certain # of seconds"""
        adjacent_nodes: List[NodeWithScore] = []
        current_node = node_with_score.node
        if len(current_node.relationships) > 0:
            adjacent_node_list = self._get_adjacent_nodes(
                current_node, seconds_buffer=seconds_buffer, max_nodes=max_nodes
            )
            adjacent_node_list = self._check_query_result(
                result=VectorStoreQueryResult(nodes=adjacent_node_list)
            )
            if not adjacent_node_list:
                return adjacent_nodes  # []
            adjacent_nodes.extend(adjacent_node_list[:max_nodes])  # Limit the number of nodes
            return adjacent_nodes  # happy path
        else:
            return adjacent_nodes  # []

    def _retrieve(self, query_bundle: ExtendedQueryBundle) -> List[NodeWithScore]:
        """Retrieve nodes given query."""
        self.embed_model = OpenAIEmbedding()
        print('model embedded')
        metadata_filters = MetadataFilters(
            condition=FilterCondition.OR,
            filters=[
                MetadataFilter(key="transcript_id", value=str(transcription_id))
                for transcription_id in query_bundle.transcription_ids
            ],
        )
        print('metadata_filters')
        query_embedding = self.embed_model.get_query_embedding(query_bundle.query_str)
        print('query_embedding')
        query_bundle.embedding = query_embedding
        vector_store_query = VectorStoreQuery(
            query_str=query_bundle.query_str,
            query_embedding=query_bundle.embedding,
            similarity_top_k=query_bundle.similarity_top_k,
            filters=metadata_filters,
        )
        print('vector_store_query')
        result = self.vector_store.query(vector_store_query)
        print('resulted')
        nodes_list = self._check_query_result(result)
        print('result checked')

        # all_relevant_nodes: List[NodeWithScore] = []
        # seen_node_ids: Set[str] = set()
        # max_nodes_per_transcript = 5  # You can adjust this value or make it a parameter

        # for node_with_score in nodes_list:
        #     print('node_with_score')
        #     all_nodes_in_transcript = self._get_all_transcript_nodes(
        #         node_with_score, 
        #         seconds_buffer=query_bundle.seconds_buffer,
        #         max_nodes=max_nodes_per_transcript
        #     )
        #     for node in all_nodes_in_transcript:
        #         if node.node.id_ not in seen_node_ids:
        #             seen_node_ids.add(node.node.id_)
        #             all_relevant_nodes.append(node)
        #             if len(all_relevant_nodes) >= query_bundle.similarity_top_k:
        #                 break
        #     if len(all_relevant_nodes) >= query_bundle.similarity_top_k:
        #         break
        # print('all_relevant_nodes, post-sort')
        return nodes_list

    async def _aretrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        """Asynchronously retrieve nodes given query.

        Implemented by the user.

        """
        return self._retrieve(query_bundle)

    ####################################
    ### Image Retrieval: Not implementing
    ####################################

    async def _aimage_to_image_retrieve(
        self,
        query_bundle: QueryBundle,
    ) -> List[NodeWithScore]:
        """Async retrieve image nodes or documents given image.

        Implemented by the user.

        """
        raise NotImplementedError("Images type not supported in transcripts")

    async def _atext_to_image_retrieve(
        self,
        query_bundle: QueryBundle,
    ) -> List[NodeWithScore]:
        """Async retrieve image nodes or documents given query text.

        Implemented by the user.

        """
        raise NotImplementedError("Images type not supported in transcripts")

    def _image_to_image_retrieve(
        self,
        query_bundle: QueryBundle,
    ) -> List[NodeWithScore]:
        """Retrieve image nodes or documents given image.

        Implemented by the user.

        """
        raise NotImplementedError("Images type not supported in transcripts")

    def _text_to_image_retrieve(
        self,
        query_bundle: QueryBundle,
    ) -> List[NodeWithScore]:
        """Retrieve image nodes or documents given query text.

        Implemented by the user.

        """
        raise NotImplementedError("Images type not supported in transcripts")


class TranscriptIndex(BaseIndex[IndexDict]):
    """For now this class is mainly going to be used as a pass-through.
    The indexing is done in a helper function and passed into a vector store first.
    API should look like:
    index = TranscriptIndex.from_vector_store(vector_store)
    query_engine = index.as_query_engine()
    Which returns RetrieverQueryEngine
    """

    def __init__(self, nodes: Sequence[BaseNode], **kwargs: Any):
        super().__init__(nodes, **kwargs)
        self._callback_manager = CallbackManager()

    @classmethod
    def from_vector_store(
        cls,
        vector_store: VectorStore,
        **kwargs: Any,
    ) -> "TranscriptIndex":
        """
        Initialize a TranscriptIndex object from a VectorStore.

        Args:
            vector_store (VectorStore): A VectorStore object.
            **kwargs: Additional keyword arguments.

        Returns:
            TranscriptIndex: A TranscriptIndex object.
        """
        if not vector_store.stores_text:
            raise ValueError(
                "Cannot initialize from a vector store that does not store text."
            )

        kwargs.pop("storage_context", None)
        storage_context = StorageContext.from_defaults(vector_store=vector_store)

        return cls(
            nodes=[],
            storage_context=storage_context,
            **kwargs,
        )

    def _build_index_from_nodes(self, nodes: Sequence[BaseNode]) -> IndexDict:
        """Build the index from nodes."""
        index_dict = IndexDict()
        for node in nodes:
            index_dict.add_node(node)
        return index_dict

    def _insert(self, nodes: Sequence[BaseNode], **insert_kwargs: Any) -> None:
        """Index-specific logic for inserting nodes to the index struct."""
        raise NotImplementedError("Not implemented")

    def _delete_node(self, node_id: str, **delete_kwargs: Any) -> None:
        """Delete a node."""
        raise NotImplementedError("Not implemented")

    @property
    def ref_doc_info(self) -> Dict[str, RefDocInfo]:
        """Retrieve a dict mapping of ingested documents and their nodes+metadata.
        Original implementation borrowed from VectorStoreIndex"""
        if not self._vector_store.stores_text:
            node_doc_ids = list(self.index_struct.nodes_dict.values())
            nodes = self.docstore.get_nodes(node_doc_ids)

            all_ref_doc_info = {}
            for node in nodes:
                ref_node = node.source_node
                if not ref_node:
                    continue

                ref_doc_info = self.docstore.get_ref_doc_info(ref_node.node_id)
                if not ref_doc_info:
                    continue

                all_ref_doc_info: Dict[str, RefDocInfo] = {}
                all_ref_doc_info[ref_node.node_id] = ref_doc_info
            return all_ref_doc_info
        else:
            raise NotImplementedError(
                "Vector store integrations that store text in the vector store are "
                "not supported by ref_doc_info yet."
            )

    def as_retriever(self, **kwargs: Any) -> BaseRetriever:
        return TranscriptRetriever(
            callback_manager=self._callback_manager,
            # node_ids=self.index_struct.nodes_dict.keys(),
            vector_store=self.storage_context.vector_store,
            object_map=self._object_map,
            **kwargs,
        )

# %% ../nbs/05_search.ipynb 15
def setup_vector_db(connection_string: str):
    # Get connection string from environment variable
    if not connection_string:
        raise ValueError("POSTGRES_URL environment variable is not set")

    # Create vector_db database
    db_name = "vector_db"
    conn = psycopg2.connect(connection_string)
    conn.autocommit = True
    with conn.cursor() as c:
        c.execute("SELECT 1 FROM pg_database WHERE datname = %s", (db_name,))
        if c.fetchone() is None:
            c.execute(f"CREATE DATABASE {db_name}")
    conn.close()

    # Update connection string to use the new database
    url = make_url(connection_string)
    vector_db_url = url.set(database=db_name)

    # Create vector store
    vector_store = PGVectorStore.from_params(
        database=db_name,
        host=url.host,
        password=url.password,
        port=str(url.port or 5432),
        user=url.username,
        table_name="transcripts",
        embed_dim=1536,  # openai embedding dimension
        hnsw_kwargs={
            "hnsw_m": 16,
            "hnsw_ef_construction": 64,
            "hnsw_ef_search": 40,
            "hnsw_dist_method": "vector_cosine_ops",
        },
    )

    print(f"Vector database '{db_name}' and table 'transcripts' created successfully.")
    print(f"New vector database URL: {vector_db_url}")
    return vector_db_url

# %% ../nbs/05_search.ipynb 17
class SearchEngine:
    """Search engine for transcripts.
    Usage:
    search_engine = SearchEngine()
    utterances = search_engine.get_utterances_from_query(query, transcripts)"""

    def __init__(
        self,
        db: AbstractDatabase[DBType],
        employee: Employee,
        db_url: Optional[str] = None,
        seconds_buffer: int = 10,
        similarity_top_k: int = 25,
        reembed_all: bool = False,
    ):
        if similarity_top_k < 10:
            raise ValueError("similarity_top_k must be at least 10 (if not more). Smaller values raise chance of no results.")
        self.db = db.as_employee(employee)
        self.client_id = "hardcoded-string-right-now"
        self.seconds_buffer = seconds_buffer
        self.similarity_top_k = similarity_top_k
        self.db_url = db_url
        self.vector_store: Optional[VectorStore] = self._create_client()
        self.employee = employee
        self.reembed_all = reembed_all
        
    async def _embed_and_augment_nodes(
        self, nodes: List[TextNode]
    ) -> Sequence[BaseNode]:
        "Embeds and augments nodes"
        return await embed_and_augment_nodes(nodes)

    def _create_client(self) -> PGVectorStore:
        """returns vector store. Creates vector store if they haven't been already."""
        connection_string = os.environ.get("VECTOR_PG_URL") if self.db_url is None else self.db_url
        if not connection_string:
            raise ValueError("DATABASE_URL is not set")
        db_name = "vector_db"
        conn = psycopg2.connect(connection_string)
        conn.autocommit = True
        with conn.cursor() as c:
            c.execute("SELECT 1 FROM pg_database WHERE datname = %s", (db_name,))
            if c.fetchone() is None:
                c.execute(f"CREATE DATABASE {db_name}")
        conn.close()
        url = make_url(connection_string)
        port = 5432
        if url.port is not None:
            port = url.port

        vector_store = PGVectorStore.from_params(
            database=db_name,
            host=url.host,
            password=url.password,
            port=str(port),
            user=url.username,
            table_name="transcripts",
            embed_dim=1536,  # openai embedding dimension
            hnsw_kwargs={
                "hnsw_m": 16,
                "hnsw_ef_construction": 64,
                "hnsw_ef_search": 40,
                "hnsw_dist_method": "vector_cosine_ops",
            },
        )
        return vector_store

    async def _check_and_add_nodes_from_transcriptions(
        self, transcripts: List[Transcription]
    ) -> Tuple[bool, str]:
        from uuid import UUID
        "Adds nodes to the vector store if they haven't been already. Returns a boolean and a string indicating the status of the operation."
        vector_store = self.vector_store
        if vector_store is None:
            raise ValueError("Vector store is None")
        transcripts_to_add: List[Transcription] = []
        nodes: List[TextNode] = []
        augmented_nodes: List[BaseNode] = []
        for transcript in transcripts:
            if transcript.embedded is False or self.reembed_all:
                transcripts_to_add.append(transcript)
        if len(transcripts_to_add) == 0:
            return True, "No nodes were added"  # early return if no need to add nodes
        nodes = await get_nodes_from_transcripts(transcripts_to_add)
        unique_transcript_ids: Set[str] = set()
        for node in nodes:
            unique_transcript_ids.add(node.metadata["transcript_id"])
        for transcript_id in unique_transcript_ids:
            if not self.db:
                raise ValueError("Database is None")
            self.db.as_employee(self.employee).update_transcription(UUID(transcript_id), {"embedded": True})
        augmented_nodes = await embed_and_augment_nodes(nodes)  # type: ignore
        vector_store = self._create_client()
        try:
            vector_store.add(augmented_nodes)
            return True, "all nodes added"
        except Exception as e:
            return False, str(e)

    def _make_query(
        self, query: str, transcriptions: List[Transcription]
    ) -> QueryBundle:
        "Makes a query bundle from a query and a list of transcripts"
        transcript_ids = [str(transcript.id) for transcript in transcriptions]
        return ExtendedQueryBundle(query_str=query, transcription_ids=transcript_ids)

    async def get_utterances_from_query(
        self,
        query: str,
        transcripts: Sequence[Transcription],
    ) -> Sequence[Utterance]:
        "Returns time-sorted utterances from a query"
        vector_store = self.vector_store
        if vector_store is None:
            raise ValueError("Vector store is None")
        try:
            status, message = await self._check_and_add_nodes_from_transcriptions(
                transcripts
            )
            if status is False:
                raise ValueError(message)
        except Exception as e:
            raise e
        index = TranscriptIndex.from_vector_store(vector_store)
        query_engine = index.as_retriever()
        query_bundle: ExtendedQueryBundle = self._make_query(query, transcripts)
        query_bundle.seconds_buffer = self.seconds_buffer
        query_bundle.similarity_top_k = self.similarity_top_k
        result = query_engine.retrieve(query_bundle)
        utterance_ids = [node.node.id_ for node in result]
        if len(utterance_ids) == 0:
            return []
        utterances = self.db.as_employee(self.employee).get_utterances(utterance_ids)
        return utterances
