# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_search.ipynb.

# %% auto 0
__all__ = ['get_nodes_from_transcripts', 'embed_and_augment_nodes', 'ExtendedQueryBundle', 'TranscriptRetriever',
           'TranscriptIndex', 'SearchEngine']

# %% ../nbs/05_search.ipynb 3
from typing import Any, List, Sequence, Set, Optional, Dict, Coroutine, Tuple
from .db import SqlModelDatabase, Utterance, AbstractDatabase
from pprint import pprint
import uuid
from llama_index.embeddings.openai import OpenAIEmbedding
import chromadb
from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.core.schema import (
    TextNode,
    NodeRelationship,
    RelatedNodeInfo,
    BaseNode,
)
from .db import Transcription
from .extraction import AIModelClient, Questions, ModelType
from llama_index.core.vector_stores.types import VectorStoreQueryResult
import numpy as np
from llama_index.core.ingestion import IngestionPipeline
from llama_index.core.indices.base import BaseIndex
from llama_index.core.data_structs import IndexDict
from llama_index.core.schema import QueryBundle, NodeWithScore
from llama_index.core.storage.docstore.types import RefDocInfo
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.vector_stores.types import (
    VectorStore,
    VectorStoreQuery,
    MetadataFilter,
    MetadataFilters,
    FilterOperator,
    FilterCondition
)
from llama_index.core.storage.storage_context import StorageContext

# %% ../nbs/05_search.ipynb 10
async def get_nodes_from_transcripts(
    transcripts: Sequence[Transcription],
) -> List[TextNode]:
    import asyncio

    """Get nodes from transcripts.
    Each node represents a single utterance in the transcript.
    Uses AI to detect the speaker role.
    The node's metadata contains the speaker, start_seconds, end_seconds, and confidence."""
    parent_nodes: List[TextNode] = []
    child_nodes: List[TextNode] = []
    # embed_model = OpenAIEmbedding()
    ai_client = AIModelClient(model_type=ModelType.GPT_3_5_TURBO)
    role_extract_schema = Questions(
        questions=[
            {
                "categories": ["A", "B"],
                "id": "1",
                "output_type": "category",
                "text": "Identify which of the speakers is the researcher in this transcript, returning whichever speaker they are in a two-person conversation — A or B.",
            }
        ]
    )
    tasks = [
        ai_client.extract_information(transcript.text, role_extract_schema)
        for transcript in transcripts
    ]
    # Run all ai_client calls concurrently and wait for all to complete
    results = await asyncio.gather(*tasks)
    for transcript, result in zip(transcripts, results):
        next_transcript_id = None
        next_node_id = None
        interviewer = result.answers[0].categories[0]

        for utterance in reversed(transcript.utterances):
            role = "interviewee" if interviewer != utterance.speaker else "interviewer"
            child_node = TextNode(
                text=utterance.text,
                id_=str(utterance.id),
                # embedding=embed_model.get_query_embedding(utterance.text),
                # ref_doc_id=str(transcript.id),
                metadata={
                    "transcript_id": str(transcript.id),
                    "speaker": role,
                    "start_seconds": utterance.start,
                    "end_seconds": utterance.end,
                    "confidence": utterance.confidence,
                },
            )

            if next_node_id is not None and next_transcript_id == transcript.id:
                child_node.relationships[NodeRelationship.NEXT] = RelatedNodeInfo(
                    node_id=next_node_id
                )
            else:
                if next_node_id is not None:
                    child_node.relationships[NodeRelationship.NEXT] = RelatedNodeInfo(
                        node_id=next_node_id
                    )
            next_node_id = child_node.id_
            next_transcript_id = transcript.id
            child_nodes.append(child_node)

    reversed_child_nodes = list(reversed(child_nodes))
    for i, node in enumerate(reversed_child_nodes):
        if i > 0:
            if NodeRelationship.NEXT in reversed_child_nodes[i - 1].relationships:
                node.relationships[NodeRelationship.PREVIOUS] = RelatedNodeInfo(
                    node_id=reversed_child_nodes[i - 1].id_
                )
    all_nodes = [*reversed_child_nodes]
    return all_nodes

# %% ../nbs/05_search.ipynb 13
def embed_and_augment_nodes(
    nodes: List[TextNode],
) -> Coroutine[Any, Any, Sequence[BaseNode]]:
    """Augments and embeds nodes. Returns a couroutine for async work in the main thread."""
    transformations = [
        # TitleExtractor(nodes=5, llm=llm),
        # QuestionsAnsweredExtractor(questions=3, llm=llm),
        OpenAIEmbedding()
    ]

    pipeline = IngestionPipeline(
        transformations=transformations,
    )
    return pipeline.arun(nodes=nodes, in_place=False)

# %% ../nbs/05_search.ipynb 20
class ExtendedQueryBundle(QueryBundle):
    query_str: str
    transcription_ids: List[str]
    seconds_buffer: int
    similarity_top_k: int

    def __init__(self, query_str: str, transcription_ids: List[str], seconds_buffer: int = 10, similarity_top_k: int = 25):
        self.query_str = query_str
        self.transcription_ids = transcription_ids
        self.seconds_buffer = seconds_buffer
        self.similarity_top_k = similarity_top_k

class TranscriptRetriever(BaseRetriever):
    """Returned by TranscriptIndex.as_retriever(), and pass into RetrieverQueryEngine.
    Then use RetrieverQueryEngine.retrieve
    Retrieval logic:
    1. Find the most relevant utterance in the transcript
    2. Expand to the adjacent utterances to get nodes that contain the most relevant information until they stop being similar to the original.
    3. Merge any overlapping nodes
    5. Rerank then return to user"""

    def __init__(self, vector_store: VectorStore, **kwargs: Any):
        self.vector_store = vector_store
        super().__init__(**kwargs)

    def _check_query_result(
        self,
        result: VectorStoreQueryResult,
        node_to_check_against: Optional[NodeWithScore] = None,
    ) -> List[NodeWithScore]:
        """really just sorts by seconds right now, doesn't actually check similarily as it originally did."""
        if result.nodes is None:
            return []
        if result.similarities is None:
            # populate with 0s
            result.similarities = [0 for _ in result.nodes]

        sorted_nodes_with_scores: List[NodeWithScore] = sorted(
            [
                NodeWithScore(node=node, score=similarity)
                for node, similarity in zip(result.nodes, result.similarities)
            ],
            key=lambda node: node.node.metadata["start_seconds"],
        )
        if node_to_check_against:
            raise NotImplementedError("Not implemented yet")
        else:
            nodes_list = sorted_nodes_with_scores
        return nodes_list
    
    def _get_nodes_based_on_relationship(self, node: BaseNode, relationship: NodeRelationship) -> Optional[TextNode]:
        related_node = node.relationships.get(relationship)
        if related_node:
            related_node_refreshed = self.vector_store.client.get(ids=[related_node.node_id])
            import json
            relationships_dict = json.loads(related_node_refreshed['metadatas'][0]['_node_content'])['relationships']
            new_node = TextNode(
                    text=related_node_refreshed['documents'][0],
                    id_=related_node_refreshed['ids'][0],
                    metadata={
                        "transcript_id": related_node_refreshed['metadatas'][0]["transcript_id"],
                        "speaker": related_node_refreshed['metadatas'][0]["speaker"],
                        "start_seconds": related_node_refreshed['metadatas'][0]["start_seconds"],
                        "end_seconds": related_node_refreshed['metadatas'][0]["end_seconds"],
                        "confidence": related_node_refreshed['metadatas'][0]["confidence"],
                    }
                )
            if '3' in relationships_dict:
                new_node.relationships[NodeRelationship.NEXT] = RelatedNodeInfo(
                    node_id=relationships_dict['3']['node_id']
                )
            if '2' in relationships_dict:
                new_node.relationships[NodeRelationship.PREVIOUS] = RelatedNodeInfo(
                    node_id=relationships_dict['2']['node_id']
                )
            return new_node

    
    def _get_adjacent_nodes(self, node: BaseNode, seconds_buffer: int = 10) -> List[BaseNode]:
        """Get adjacent nodes in the transcript within a specified time window."""
        adjacent_nodes: List[BaseNode] = [node]

        # Get the start and end times of the original node
        original_start_ms = node.metadata["start_seconds"]
        original_end_ms = node.metadata["end_seconds"]

        # Calculate the time window boundaries
        start_window_ms = original_start_ms - seconds_buffer * 1000
        end_window_ms = original_end_ms + seconds_buffer * 1000
        # Retrieve previous nodes within the time window
        prev_node_id = node.relationships.get(NodeRelationship.PREVIOUS)
        if prev_node_id:
            prev_node_with_metadata = self.vector_store.client.get(ids=[prev_node_id.node_id])
        while prev_node_id:
            prev_node = self._get_nodes_based_on_relationship(node=node, relationship=NodeRelationship.PREVIOUS)
            if prev_node:
                prev_node_metadata = prev_node.metadata
                if prev_node_metadata['end_seconds'] < start_window_ms:
                    break
                adjacent_nodes.insert(0, prev_node)
                prev_node_id = prev_node.relationships.get(NodeRelationship.PREVIOUS)
                node = prev_node
            else:
                break

        # Retrieve next nodes within the time window
        next_node_id = node.relationships.get(NodeRelationship.NEXT)
        while next_node_id:
            next_node = self._get_nodes_based_on_relationship(node=node, relationship=NodeRelationship.NEXT)
            if next_node:
                if next_node.metadata['start_seconds'] > end_window_ms:
                    break
                adjacent_nodes.append(next_node)
                next_node_id = next_node.relationships.get(NodeRelationship.NEXT)
                node = next_node
            else:
                break
        return adjacent_nodes

    def _get_all_transcript_nodes(
        self, node_with_score: NodeWithScore, seconds_buffer: int = 10
    ) -> List[NodeWithScore]:
        """Retrieve all nodes in a transcript if they have the same transcript_id and the node has a relationship, up to a certain # of seconds"""
        adjacent_nodes: List[NodeWithScore] = []
        current_node = node_with_score.node
        if len(current_node.relationships) > 0:
            adjacent_node_list = self._get_adjacent_nodes(current_node, seconds_buffer=seconds_buffer)
            adjacent_node_list = self._check_query_result(result=VectorStoreQueryResult(nodes=adjacent_node_list))
            if not adjacent_node_list:
                return adjacent_nodes  # []
            adjacent_nodes.extend(adjacent_node_list)
            return adjacent_nodes  # happy path
        else:
            return adjacent_nodes  # []

    def _retrieve(self, query_bundle: ExtendedQueryBundle) -> List[NodeWithScore]:
        """Retrieve nodes given query."""
        self.embed_model = OpenAIEmbedding()
        metadata_filters = MetadataFilters(
            condition=FilterCondition.OR,
            filters=[
                MetadataFilter(key="transcript_id", value=str(transcription_id))
                for transcription_id in query_bundle.transcription_ids
            ]
        )
        query_embedding = self.embed_model.get_query_embedding(query_bundle.query_str)
        query_bundle.embedding = query_embedding
        vector_store_query = VectorStoreQuery(
            query_str=query_bundle.query_str,
            query_embedding=query_bundle.embedding,
            similarity_top_k=query_bundle.similarity_top_k,
            filters=metadata_filters

        )
        result = self.vector_store.query(vector_store_query)
        nodes_list = self._check_query_result(result)

        all_relevant_nodes: List[NodeWithScore] = []
        seen_node_ids: Set[str] = set()
        for node_with_score in nodes_list:
            all_nodes_in_transcript = self._get_all_transcript_nodes(node_with_score, seconds_buffer=query_bundle.seconds_buffer)
            for node in all_nodes_in_transcript:
                if node.node.id_ not in seen_node_ids:
                    seen_node_ids.add(node.node.id_)
                    all_relevant_nodes.append(node)


        all_relevant_nodes.sort(
            key=lambda x: (
                x.node.metadata["transcript_id"],
                x.node.metadata["start_seconds"],
            )
        )
        return all_relevant_nodes

    async def _aretrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        """Asynchronously retrieve nodes given query.

        Implemented by the user.

        """
        return self._retrieve(query_bundle)

    ####################################
    ### Image Retrieval: Not implementing
    ####################################

    async def _aimage_to_image_retrieve(
        self,
        query_bundle: QueryBundle,
    ) -> List[NodeWithScore]:
        """Async retrieve image nodes or documents given image.

        Implemented by the user.

        """
        raise NotImplementedError("Images type not supported in transcripts")

    async def _atext_to_image_retrieve(
        self,
        query_bundle: QueryBundle,
    ) -> List[NodeWithScore]:
        """Async retrieve image nodes or documents given query text.

        Implemented by the user.

        """
        raise NotImplementedError("Images type not supported in transcripts")

    def _image_to_image_retrieve(
        self,
        query_bundle: QueryBundle,
    ) -> List[NodeWithScore]:
        """Retrieve image nodes or documents given image.

        Implemented by the user.

        """
        raise NotImplementedError("Images type not supported in transcripts")

    def _text_to_image_retrieve(
        self,
        query_bundle: QueryBundle,
    ) -> List[NodeWithScore]:
        """Retrieve image nodes or documents given query text.

        Implemented by the user.

        """
        raise NotImplementedError("Images type not supported in transcripts")


class TranscriptIndex(BaseIndex[IndexDict]):
    """For now this class is mainly going to be used as a pass-through.
    The indexing is done in a helper function and passed into a vector store first.
    API should look like:
    index = TranscriptIndex.from_vector_store(vector_store)
    query_engine = index.as_query_engine()
    Which returns RetrieverQueryEngine
    """

    def __init__(self, nodes: Sequence[BaseNode], **kwargs: Any):
        super().__init__(nodes, **kwargs)
        self._callback_manager = CallbackManager()

    @classmethod
    def from_vector_store(
        cls,
        vector_store: VectorStore,
        **kwargs: Any,
    ) -> "TranscriptIndex":
        """
        Initialize a TranscriptIndex object from a VectorStore.

        Args:
            vector_store (VectorStore): A VectorStore object.
            **kwargs: Additional keyword arguments.

        Returns:
            TranscriptIndex: A TranscriptIndex object.
        """
        if not vector_store.stores_text:
            raise ValueError(
                "Cannot initialize from a vector store that does not store text."
            )

        kwargs.pop("storage_context", None)
        storage_context = StorageContext.from_defaults(vector_store=vector_store)

        return cls(
            nodes=[],
            storage_context=storage_context,
            **kwargs,
        )

    def _build_index_from_nodes(self, nodes: Sequence[BaseNode]) -> IndexDict:
        """Build the index from nodes."""
        index_dict = IndexDict()
        for node in nodes:
            index_dict.add_node(node)
        return index_dict

    def _insert(self, nodes: Sequence[BaseNode], **insert_kwargs: Any) -> None:
        """Index-specific logic for inserting nodes to the index struct."""
        raise NotImplementedError("Not implemented")

    def _delete_node(self, node_id: str, **delete_kwargs: Any) -> None:
        """Delete a node."""
        raise NotImplementedError("Not implemented")

    @property
    def ref_doc_info(self) -> Dict[str, RefDocInfo]:
        """Retrieve a dict mapping of ingested documents and their nodes+metadata.
        Original implementation borrowed from VectorStoreIndex"""
        if not self._vector_store.stores_text:
            node_doc_ids = list(self.index_struct.nodes_dict.values())
            nodes = self.docstore.get_nodes(node_doc_ids)

            all_ref_doc_info = {}
            for node in nodes:
                ref_node = node.source_node
                if not ref_node:
                    continue

                ref_doc_info = self.docstore.get_ref_doc_info(ref_node.node_id)
                if not ref_doc_info:
                    continue

                all_ref_doc_info: Dict[str, RefDocInfo] = {}
                all_ref_doc_info[ref_node.node_id] = ref_doc_info
            return all_ref_doc_info
        else:
            raise NotImplementedError(
                "Vector store integrations that store text in the vector store are "
                "not supported by ref_doc_info yet."
            )

    def as_retriever(self, **kwargs: Any) -> BaseRetriever:
        return TranscriptRetriever(
            callback_manager=self._callback_manager,
            # node_ids=self.index_struct.nodes_dict.keys(),
            vector_store=self.storage_context.vector_store,
            object_map=self._object_map,
            **kwargs,
        )

# %% ../nbs/05_search.ipynb 21
class SearchEngine:
    """Search engine for transcripts.
    Usage:
    search_engine = SearchEngine()
    utterances = search_engine.get_utterances_from_query(query, transcripts)"""

    def __init__(
        self, db: Optional[SqlModelDatabase] = None, path: str = "../chroma_db", seconds_buffer: int = 10, similarity_top_k: int = 25
    ):
        self.db = db
        self.client_id = "hardcoded-string-right-now"
        self.seconds_buffer = seconds_buffer
        self.similarity_top_k = similarity_top_k
        self.path = path
        self.vector_store: Optional[VectorStore] = self._create_client()

    async def _embed_and_augment_nodes(
        self, nodes: List[TextNode]
    ) -> Sequence[BaseNode]:
        "Embeds and augments nodes"
        return await embed_and_augment_nodes(nodes)

    def _create_client(self) -> ChromaVectorStore:
        """returns vector store. Creates vector store if they haven't been already."""
        chroma_client = chromadb.PersistentClient(path=self.path)
        chroma_collection = chroma_client.get_or_create_collection(self.client_id)
        vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
        return vector_store

    async def _check_and_add_nodes_from_transcriptions(
        self, transcripts: List[Transcription]
    ) -> Tuple[bool, str]:
        from uuid import UUID
        "Adds nodes to the vector store if they haven't been already. Returns a boolean and a string indicating the status of the operation."
        vector_store = self.vector_store
        if vector_store is None:
            raise ValueError("Vector store is None")
        transcripts_to_add: List[Transcription] = []
        nodes: List[TextNode] = []
        augmented_nodes: List[BaseNode] = []
        for transcript in transcripts:
            if transcript.embedded is False:
                transcripts_to_add.append(transcript)
        if len(transcripts_to_add) == 0:
            return True, "No nodes were added"  # early return if no need to add nodes
        nodes = await get_nodes_from_transcripts(transcripts_to_add)
        unique_transcript_ids: Set[str] = set()
        for node in nodes:
            unique_transcript_ids.add(node.metadata["transcript_id"])
        for transcript_id in unique_transcript_ids:
            if not self.db:
                raise ValueError("Database is None")
            self.db.update_transcription(UUID(transcript_id), {"embedded": True})
        augmented_nodes = await embed_and_augment_nodes(nodes)  # type: ignore
        vector_store = self._create_client()
        try:
            vector_store.add(augmented_nodes)
            return True, "all nodes added"
        except Exception as e:
            return False, str(e)

    def _make_query(
        self, query: str, transcriptions: List[Transcription]
    ) -> QueryBundle:
        "Makes a query bundle from a query and a list of transcripts"
        transcript_ids = [str(transcript.id) for transcript in transcriptions]
        return ExtendedQueryBundle(query_str=query, transcription_ids=transcript_ids)

    async def get_utterances_from_query(
        self, query: str, transcripts: List[Transcription]
    ) -> List[Utterance]:
        "Returns time-sorted utterances from a query"
        vector_store = self.vector_store
        if vector_store is None:
            raise ValueError("Vector store is None")
        try:
            status, message = await self._check_and_add_nodes_from_transcriptions(
                transcripts
            )
            if status is False:
                raise ValueError(message)
        except Exception as e:
            pprint(e)
        index = TranscriptIndex.from_vector_store(vector_store)

        query_engine = index.as_retriever()
        query_bundle: ExtendedQueryBundle = self._make_query(query, transcripts)
        query_bundle.seconds_buffer = self.seconds_buffer
        query_bundle.similarity_top_k = self.similarity_top_k
        result = query_engine.retrieve(query_bundle)
        utterances: List[Utterance] = []
        for node_with_score in result:
            node = node_with_score.node
            utterances.append(
                Utterance(
                    id=node.id_,
                    text=node.text,
                    confidence=node.metadata["confidence"],
                    start=int(node.metadata["start_seconds"]),
                    end=int(node.metadata["end_seconds"]),
                    speaker=node.metadata["speaker"],
                    transcription_id=node.metadata["transcript_id"],
                )
            )
        return utterances
