# name: CI/CD
# on: [push, pull_request]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     env:
#       DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}
#     steps:
#       - name: Checkout the repository
#         uses: actions/checkout@v3
#       - name: Intall dotenvx
#         run: curl -sfS https://dotenvx.sh/install.sh | sh
#       - name: Install FFmpeg and imagmagick deps
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y ffmpeg
#           sudo apt-get install ghostscript
#           sudo apt-get install fonts-freefont-otf
#       - name: Install the latest version of rye
#         uses: eifinger/setup-rye@v4
#         with:
#           enable-cache: true
#       - name: Install project
#         run: |
#           PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -r requirements.lock
#           pip install -e .
#       - name: Set PYTHONPATH
#         run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
#       - name: Sync dependencies
#         run: dotenvx run -f .env.ci -- rye sync
#       - name: Fix ImageMagick security policy
#         run: sudo sed -i 's/rights="none" pattern="@\*"/rights="read|write" pattern="@*"/' /etc/ImageMagick-6/policy.xml
#       - name: Setup environment
#         run: |
#           dotenvx run -f .env.ci -- python $(pwd)/scripts/setup_env.py
#       - name: Run tests
#         run: dotenvx run -f .env.ci -- rye run nbdev_test --skip_file_re "07_db\.ipynb" --do_print

  # deploy-fly:
  #   needs: test
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: superfly/flyctl-actions/setup-flyctl@master
  #     - name: Deploy to fly.io
  #       run: flyctl deploy --build-secret dotenv_key="${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }}" --strategy immediate
  #       env:
  #         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  
  # deploy-cf-worker:
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install dotenvx
  #       run: curl -sfS https://dotenvx.sh/install.sh | sh
  #     - name: Install Wrangler
  #       run: npm install -g wrangler
  #     - name: Deploy CF Worker
  #       run: |
  #         cd workers
  #         dotenvx run -f ../.env.ci -- npx wrangler deploy
  #       env:
  #         CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #         DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}