name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Intall dotenvx
        run: curl -sfS https://dotenvx.sh/install.sh | sh
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
      - name: Sync dependencies
        run: rye sync
      - name: Run tests
        run: rye run test