name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Intall dotenvx
        run: curl -sfS https://dotenvx.sh/install.sh | sh
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
      - name: Install project
        run: |
          PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -r requirements.lock
          pip install -e .
      - name: Sync dependencies
        run: dotenvx run -f .env.ci -- rye sync
      - name: Setup environment
        run: |
          dotenvx run -f .env.ci -- python $(pwd)/scripts/setup_env.py
      - name: Run tests
        run: dotenvx run -f .env.ci --rye run test